### ISSUE TITLE
Support of the 'newpage' plantuml keyword

### ISSUE THREAD

**Issue by biddaputzese** [qjebbs/vscode-plantuml#1]
Hello ;-)

I can't export multiple images while using the newpage keyword.

Is this on the roadmap ?

Thank you.

Kind regards,
Bruno

**Comment by qjebbs** [comment]
Thanks for the feedback, I should firstly see how `newpage` acts, I haven't ever used it .

**Comment by qjebbs** [comment]
I only see 1 output from `stdout` when export multi-page diagram, but it's OK with command line.
Seems I can't find a way to do it. Any ideas or pull requests will be appreciate.

**Comment by arkoak** [comment]
newpage makes more than one diagram from the same uml code. The following should be on 2 pages but only one page is displayed.
```
@startuml
a->b: hello;
newpage newpagetitle
b->a : back on new page;
@enduml;
```
 the tool only shows the first diagram. I faced the same problem with a similar tool using atom so I believe it is relevant to how the library can be implemented

**Comment by qjebbs** [comment]
Yes. Execute directly in command line is OK, but the exports are not managed by code in this way.

**Comment by biddaputzese** [comment]
OK, so I am using this syntax:

```
@startuml
a->b: hello;
@enduml
```

```
@startuml
b->a : back on new page;
@enduml
```
