### ISSUE TITLE
Several syntax highlights are not valid

### ISSUE THREAD

**Issue by koara-local** [qjebbs/vscode-plantuml#10]
Hello. I found a case that is not syntax highlighting.

+ `repeat while (condition)`
+ `while (condition)`
+ `end while`

![image](https://cloud.githubusercontent.com/assets/6697113/23704823/0d7d09ee-044a-11e7-984a-98112ea09310.png)

http://plantuml.com/activity-diagram-beta

Thanks.

**Comment by koara-local** [comment]
How is conversion from `diagram.yaml-tmLanguage` to` diagram.tmLanguage`?
I think trying to fix, but did not know the way.

**Comment by qjebbs** [comment]
thank you! I use sublime text + packageDev. vscode has simillar plugin, but doesn't work.

**Comment by koara-local** [comment]
![image](https://cloud.githubusercontent.com/assets/6697113/23751908/ac138da4-0516-11e7-9f29-62f497a378d8.png)
![image](https://cloud.githubusercontent.com/assets/6697113/23751927/b9c197ca-0516-11e7-8fef-a7c5eae86980.png)
![image](https://cloud.githubusercontent.com/assets/6697113/23751951/cb863e5c-0516-11e7-9e37-a0da3c717685.png)

TestData:
[test_diagram.txt](https://github.com/qjebbs/vscode-plantuml/files/830943/test_diagram.txt)

**Comment by koara-local** [comment]
Should be OK.

**Comment by qjebbs** [comment]
I'm adding translations to all display text, besides menu captions. Can you help translate to Japanese? the language file `lang.nls.json` is in `develop` branch, `langs` folder.

Thanks a lot!
