### ISSUE TITLE
Syntax highlighting for linking types is incomplete

### ISSUE THREAD

**Issue by SanderSmee** [qjebbs/vscode-plantuml#100]
According to http://plantuml.com/deployment-diagram#linking e.g. `--#` and `--^` can be used as link types. Highlighting of several types is not complete.

![screen shot 2018-02-27 at 10 58 40](https://user-images.githubusercontent.com/165428/36722403-b6bb41f8-1bad-11e8-959f-113a0bc9e606.png)

**Comment by qjebbs** [comment]
PlantUML syntaxes are to flexible, some of the is out of the capability that REGEXP can handle, in my opinion. A single dot could be link too...
```
@startuml
    a.b:asd
@enduml
```
Some syntaxes are conflict with each other for REGEXP. eg,
```
'Note the : used to define actors and also comments.
@startuml
    :a:.:b::test
@enduml
```

So I am not promise to support all syntaxes, I can only provide basic highlights support. I will work on this issue and others later, including #99, #101, #102, but no promises that all of them can be fixed.

If someone else could offer better syntax file, many thanks!

**Comment by SanderSmee** [comment]
Looking at the definitions (and regexes) I already suspected this to be the hardest issue to resolve. 
Since the most used ones are recognised, I won't be to disappointed if you won't resolve this specific issue.

**Comment by qjebbs** [comment]
@SanderSmee Thanks for the understanding, I'll try fixing them ASAP.

**Comment by qjebbs** [comment]
![image](https://user-images.githubusercontent.com/16953333/36930640-5097eed6-1ee0-11e8-80f6-09909d92df8f.png)
