### ISSUE TITLE
Syntax highlighting of some common commands is missing

### ISSUE THREAD

**Issue by SanderSmee** [qjebbs/vscode-plantuml#101]
According to http://plantuml.com/commons keywords as `header` and `footer` can be used as keywords for respective elements in a diagram. Positioning of these elements can be done by the `left`, `right` or `center` keyword. 

- The keywords `left`, `right` and `center` are not highlighted
- The `caption` keyword is not highlighted

![screen shot 2018-02-27 at 11 00 26](https://user-images.githubusercontent.com/165428/36722683-7b48ae8e-1bae-11e8-8b37-bf78896f91ad.png)

**Comment by qjebbs** [comment]
![image](https://user-images.githubusercontent.com/16953333/36766744-2a392496-1c72-11e8-8094-86b2e72513d6.png)

**Comment by SanderSmee** [comment]
Thank you, it looks great.
