### ISSUE TITLE
Syntax highlighting of skinparam with role is incorrect

### ISSUE THREAD

**Issue by SanderSmee** [qjebbs/vscode-plantuml#102]
See the accompanying image. Syntaxhighlighting is incorrect for skinparam if the correct plantuml markup `item<<role>>` is used for items with a role. If the incorrect markup `item <<role>>` is used, highlighting is presumably correct. Note the difference of the one space character between `item` and `<<`.

![screen shot 2018-02-27 at 11 41 43](https://user-images.githubusercontent.com/165428/36724361-4aae8686-1bb3-11e8-9387-4cb1e2927ef6.png)

**Comment by SanderSmee** [comment]
I think this can be resolved by removing the `\s+` from the regexes for inline and block skinparam definitions.
 
I have no experience developing a vscode plugin, but am willing to try and provide a PR if you can't spend time on this issue.

**Comment by qjebbs** [comment]
Yes, you're right. Thanks for feedback.

![image](https://user-images.githubusercontent.com/16953333/36765893-6bfc3c82-1c6e-11e8-8b32-be5eda31ccc7.png)

**Comment by SanderSmee** [comment]
Thank you, a great improvement. 
I noticed the last line in your example and expected it to be invalid plantuml, but it is accepted (and doesn't apply to the stereotype because of the space character).

**Comment by qjebbs** [comment]
Yes, you are right. In last line, I intentionally made them so, to show how new syntax behaves: `asdasd` is the param, while the whole `<<asd>> #red` is the value.
