### ISSUE TITLE
Include preprocessor gives error

### ISSUE THREAD

**Issue by lakshmantgld** [qjebbs/vscode-plantuml#103]
Plantuml supports some preprocessor such as `!include a.puml`, but the `vscode-plantuml` shows error. Check out the error:
![plantuml preprocessor error](https://user-images.githubusercontent.com/6481030/36886168-58c778a4-1e2e-11e8-83b8-48ffaa60b37c.png)

Is it **plantuml-server** error? or am I doing something wrong?

**Comment by qjebbs** [comment]
Yes, server cannot include files in your local storage(how can server fetch file from your device?), I described this limit in README. It's not a bug, and cannot resolve.

**Comment by lakshmantgld** [comment]
Oh sorry. I didn't know this.

**Comment by qjebbs** [comment]
My pleasure.

**Comment by lakshmantgld** [comment]
Hey @qjebbs, just figured out, the atom plugin(https://atom.io/packages/plantuml-viewer) actually previews the `.puml` file that contains the `!include` preprocessors. To make it possible in vscode, where should we start? (Is it the capability of the plantuml-server?)

**Comment by qjebbs** [comment]
plantuml-viewer doesn't provide server render, does it? That is why it doesn't have this problem. If you want include, please switch to local render.

**Comment by qjebbs** [comment]
closed due to inactivity
