### ISSUE TITLE
Bad formatting for curly braces relationship

### ISSUE THREAD

**Issue by neonailol** [qjebbs/vscode-plantuml#108]
Consider this example

```
@startuml Hello
Class25 }-- Class26
class Class01 {
}
@enduml
```

After formatting with this plugin it becomes:

```
@startuml Hello
Class25
}
-- Class26
class Class01 {
}
@enduml
```

Which is not correct. I use version `2.5.5` and vs code editor version `1.21.1`

**Comment by qjebbs** [comment]
should have fixed
