### ISSUE TITLE
PlantUML can not find java

### ISSUE THREAD

**Issue by MaSven** [qjebbs/vscode-plantuml#112]
Plantuml can not find java even though the javahome is set and java bin folder is in the path. Is there a way i can figure out how the extension is looking for the path?

**Comment by qjebbs** [comment]
Plug in don't looking for any path. Make `java -version` works in terminal, the it works with the plugin.

**Comment by MaSven** [comment]
This is the problem java -version works in the terminal. Maybe there is a problem, that my java version is behind a symlink? I use sdkman to switch the java version frequently. So the actual java version is behind a symlink.

**Comment by qjebbs** [comment]
Maybe it is the problem, that the child_process module behaves different in this case, I guess. Can you try testing with no-symlink-java?

**Comment by qjebbs** [comment]
If you still cannot locate the problem, try to configure java path with latest release.

**Comment by MaSven** [comment]
With the newest version it works after declaring the path to the java executable in the new setting. It also follows the symlink. Thank you for the fast fix.

**Comment by huangshuai-IOT** [comment]
你好，我使用 PlantUML Visual Code Extension Version 2.11.0，报错" Cannot find java!
If you've installed java, please add java bin path to PATH environment variable.
Or, configure java executable path with "plantuml.java"."

我将java bin path添加到PATH 环境变量，在终端中可以使用 java -version，还是同样的错误。

然后修改了settings中的Java executable location 为 C:\Program Files\Java\jdk-12.0.1\bin\

还是报错，请问怎么处理？

**Comment by qjebbs** [comment]
@huangshuai-IOT `plantuml.java` should be like `c:/path/to/your/java.exe`, yours, is just a folder.

**Comment by huangshuai-IOT** [comment]
@qjebbs 你好，我分别尝试设置 `plantuml.java` 为 `C:/Program Files/Java/jdk-12.0.1/bin/java.exe`  和  `C:\Program Files\Java\jdk-12.0.1\bin\java.exe`  , 但还是同样的错误  `Cannot find java!
If you've installed java, please add java bin path to PATH environment variable.
Or, configure java executable path with "plantuml.java".`  我是Windows10。

**Comment by juergs** [comment]
This works for me: 
Enter only java.exe as "java executable location" without any path => works !
;-)

**Comment by mewhuan** [comment]
Add the extension globally works for me. 
Tried to install plantuml in the first window of vscode, instead of in my sub window solve the problem.

**Comment by coutamg** [comment]
Fill in Java.exe in java executable location, then it work!@huangshuai-IOT

**Comment by mjjackey** [comment]
> @qjebbs 你好，我分别尝试设置 `plantuml.java` 为 `C:/Program Files/Java/jdk-12.0.1/bin/java.exe` 和 `C:\Program Files\Java\jdk-12.0.1\bin\java.exe` , 但还是同样的错误 `Cannot find java! If you've installed java, please add java bin path to PATH environment variable. Or, configure java executable path with "plantuml.java".` 我是Windows10。

your path configuration is incorrect, you should configure the jre path in the system environment as follows sequentially:
1. JAVA_HOME
2. CLASSPATH
3. Path
Then in `plantuml.java`  fill 'java'.

**Comment by wYaobiz** [comment]
> 

Great! Solved this issue!
