### ISSUE TITLE
Syntax Error when using connector in Activity Diagram

### ISSUE THREAD

**Issue by luisgustavossdd** [qjebbs/vscode-plantuml#114]
Trying to use a connector as follows:
```
:Act1;
(A)
detach
(A)
:Act2;
```

Howerver, I always get a "Syntax Error?" in any line with the (A). Also tested removing the (A), as shown below:
```
:Act1;
detach
:Act2;
```
In the example above there is no "Syntax Error?" message.

**Comment by qjebbs** [comment]
Sorry, I don't know what `(A)` mean, and I am only working on the PlantUML plugin for VSCode, not the PlantUML language. You'd better turn to [plantuml issues](https://github.com/plantuml/plantuml/issues) for this problem.

**Comment by luisgustavossdd** [comment]
(A) is the syntax for a connector in anexo Activity Diagram.

An example can be found in PlantUML website in the Connector section (http://plantuml.com/activity-diagram-beta)

**Comment by qjebbs** [comment]
Just found it'a new syntax provided by later version of `plantuml`. I will update the embedded `plantuml.jar` to solve this problem, no code altering needed.

**Comment by qjebbs** [comment]
please update
