### ISSUE TITLE
No valid diagram found here

### ISSUE THREAD

**Issue by silva6** [qjebbs/vscode-plantuml#115]
![image](https://user-images.githubusercontent.com/2333255/39346220-8cfc8764-4a1f-11e8-9a85-46dcfa615467.png)

press `alt + p` , occur this error

**Comment by silva6** [comment]
macos 10.12.2    vscode 1.22.2  plantuml 2.5.10     2.5.9   and 2.5.8 the same

**Comment by qjebbs** [comment]
please write down the steps to reproduce the problem.

**Comment by qjebbs** [comment]
the only way I can get `no diagram` tip is that placing cursor outside the diagram block. But it's reasonable.
![image](https://user-images.githubusercontent.com/16953333/39347288-b9a20eba-4a24-11e8-9bfc-a1bfe4bce612.png)

**Comment by silva6** [comment]
![qq20180428-114007](https://user-images.githubusercontent.com/2333255/39391639-83530d72-4ad9-11e8-8f1f-0f7e07ddc153.gif)

**Comment by silva6** [comment]
@qjebbs

**Comment by qjebbs** [comment]
please try the latest release.

**Comment by GSRLW** [comment]
the latest release  has the same problem .  ]
![image](https://user-images.githubusercontent.com/35130268/131275817-2005d35d-4038-42b5-9d4b-47c1ada55215.png)
