### ISSUE TITLE
Code formatting on save breaks diagram

### ISSUE THREAD

**Issue by chbndrhnns** [qjebbs/vscode-plantuml#116]
With the plugin enabled, if I paste the snippet from the official website to VS Code and hit save, it gets reformatted so that it cannot be rendered anymore by the PlantUML server:

```
if (test) then
  -[#blue]->
  :foo2;
  -[#green,dashed]-> The text can
  also be on several lines
  and **very** long...;
  :foo3;
else
  -[#black,dotted]->
  :foo4;
endif
```

The first lines are on save changed to

```
if (test) 
   then
  -[#blue]->
  :foo2;
```

which shows an error when pressing alt+d to render a preview

**Comment by qjebbs** [comment]
please update
