### ISSUE TITLE
plantuml source files won't save when preview is open

### ISSUE THREAD

**Issue by nextdude** [qjebbs/vscode-plantuml#118]
I've noticed that if my cursor is in a plantuml source and a preview of that plantuml file is also open and I make a change in the diagram's source, the preview properly updates, but the source document won't save, either via a keyboard shortcut, or selecting save from the vs code menu until I click out of the source file and then back into it.

Using 
- mac os 10.13.3
- vscode-plantuml version 2.6.1
- vs code version 1.23
- graphviz 2.40.1
- local previews (no server)

**Comment by qjebbs** [comment]
I think it's a small bug of VSCode: https://github.com/Microsoft/vscode/issues/49338
