### ISSUE TITLE
the preview function sometimes will not preview whole document

### ISSUE THREAD

**Issue by Verten** [qjebbs/vscode-plantuml#119]
when i trigger ALT + D, some time it can not preview whole document,

there is the screenshot for you

![image](https://user-images.githubusercontent.com/3843953/39684816-28666cfa-51f1-11e8-9b1b-3c0d1c0ffedd.png)

the whole file has 394 lines, but when i delete some lines, the preview can work.

so i not sure is there has some configuration for the max line?

**Comment by qjebbs** [comment]
You may try the following setting:

`plantuml.commandArgs`: commandArgs allows you add command arguments to java command, such as `-DPLANTUML_LIMIT_SIZE=8192`.

I am not sure if this could solve your problem, and neither know what the really causes to your issue.
But my extension doesn't limit lines or sizes, you may turn to plantuml forum for help.

**Comment by Verten** [comment]
@qjebbs thanks, it works! i'll close this issue
