### ISSUE TITLE
Modify path/set environment variable GRAPHVIZ_DOT

### ISSUE THREAD

**Issue by tim-rohrer** [qjebbs/vscode-plantuml#121]
I think my issue may be similar to #94.

 I'm on a Mac, and a bit new with VS Code.

I can set GRAPHVIZ_DOT to /opt/local/bin/dot in Terminal.app, so I know my setup works.

But, I'm not clear where in `vscode-plantuml` I can set the path for Graphviz? And how do I do this?

**Comment by qjebbs** [comment]
```json
"plantuml.commandArgs": [
    "-DGRAPHVIZ_DOT=/opt/local/bin/do",
]
```

try this

**Comment by tim-rohrer** [comment]
Let me document what I did to get the *real issue* resolved, namely, I wanted to use PlantUML inside of VS Code on a Mac OS platform running High Sierra.

Because I didn't see any way to add a command-line switch for MacOS, I focused on how to set the environment variable (GRAPHVIZ_DOT) at the start of VS Code execution. I could have set it from Terminal, and then run VS Code from that Terminal, but I wanted a more permanent solution.

Following a quick Google, I learned we can create a `/etc/launchd.conf` file and add `setenv GRAPHVIZ_DOT /opt/local/bin/dot`, then save the file. At that point, we need to get `launchctl` to see that. This can be done by rebooting the system, or this worked for me as an admin user:

`grep -E "^setenv" /etc/launchd.conf | xargs -t -L 1 launchctl`

After that, restart VS Code and use alt-D to build the diagram.

Worked for me, but YMMV.

**Comment by qjebbs** [comment]
Please notice that you wrote `-GRAPHVIZ_DOT` instead of `-DGRAPHVIZ_DOT`.

**Comment by qjebbs** [comment]
and, you should not change `package.json`, but put it in user settings.

**Comment by tim-rohrer** [comment]
Thank you. For some reason I missed the user settings when I was searching for them.

**Comment by qjebbs** [comment]
my pleasure

**Comment by smil2k** [comment]
I needed to add the following lines:

`  "plantuml.jarArgs": ["-DGRAPHVIZ_DOT=/use/bin/dot"]`
