### ISSUE TITLE
preview error

### ISSUE THREAD

**Issue by dylanleung** [qjebbs/vscode-plantuml#123]
<img width="1440" alt="default" src="https://user-images.githubusercontent.com/1852360/40340306-d497d41c-5db0-11e8-8b9f-228e1a379492.png">

new version when I preview can see the image.
and then after loading  can't see like this

<img width="1250" alt="default" src="https://user-images.githubusercontent.com/1852360/40340341-0f3e0f64-5db1-11e8-9424-d634f40fa375.png">

export is ok.
<img width="382" alt="default" src="https://user-images.githubusercontent.com/1852360/40340401-554ea4d2-5db1-11e8-9810-6403458396a3.png">

my os is mac os 10.13.4

**Comment by qjebbs** [comment]
can you post the source, so that I can reproduce it in my ENV?

**Comment by dylanleung** [comment]
ok
@startuml

class AppDevice{
    __app_device: table__
    - deviceId: String // 设备号唯一
    - lastRequestTime: LocalDateTime
    - device: String //类型
    - userId: Long //关联用户Id
    - created: LocalDateTime //创建时间
    __匿名设备记录表__
}


class ExperienceHomeworkState{
    --experience_homework_state: table--
    - id: Long  //ID
    - deviceId: String //儿童Id
    - userId: Long //注册后填写
    - homeworkId: Long //作业Id
    - type: HomeworkItemTypeEnum //作业类型Id
    - created: LocalDateTime //创建时间
    __匿名作业状态表(done)__
}


class ExperienceHomework{
    --anonymous_homework: table--
    - id: Long //Id
    - deviceId: String //儿童Id
    - homeworkId: Long //作业Id
    - score: Integer //分数
    - duration: Long // 学习时长
    - lookTimes: Integer //看动画次数
    - listened: Long //音频听的下标
    - created: LocalDateTime //创建时间
    - modified: LocalDateTime //修改时间
    __匿名作业表(done)__

}


class ExperienceHomeworkSubjective{
   --children_homework_subjective: table--
   - id: Long //Id
   - deviceId: String //儿童Id
   - classId: Long //班级Id
   - homeworkId: Long //作业Id
   - examId: Long  //测试Id
   - rank: Integer // 排名
   - childrenAudio: String //儿童音频
   - created: LocalDateTime //创建时间
   __匿名作业记录(done)__
}


class User{
    --user: table--
    - id: Long // ID
    - avatar: String //头像
    - phone: String//手机号 唯一
    - nickname: String //昵称
    - realname: String //真实姓名
    - knship: KnshipTypeEnum //关系
    - device:String //类型
    - deviceId: String // 设备号
    - last_login_time: LocalDateTime
    - created: LocalDateTime //创建时间
    - modified: LocalDateTime //修改时间
    -- 用户登录表信息(done)--
}

enum KnshipTypeEnum{
    MYSELF,MOTHER,FATHER,TEACHER
    --关系类型枚举--
}


class Children{
    --children: table--
    - id: Long //id
    - nickname: String //昵称
    - realname: String //真实姓名
    - birthday: LocalDate //生日
    - type: ChildrenTypeEnum //学员状态
    - admissionDate: LocalDate//入学时间
    - created: LocalDateTime //创建时间
    - modified: LocalDateTime //修改时间
    __儿童信息表(done)__
}




enum ChildrenTypeEnum{
    REGISTERED,STUDENT
    __学生类型__
}



class UserChildren{
    --user_children: table--
    - id: Long
    - user_id: Long
    - children_id: Long
    - created: LocalDateTime
    __用户儿童关系表(done)__
}

class EnjoyClass{
    --enjoy_class: table--
    - id: Long //ID
    - avatar:String //班级图片
    - name: String //班级名称
    - title: String //班级标题
    - state: Boolean //状态
    - created:LocalDateTime //创建时间
    - modified:LocalDateTime //修改时间
    - operator: String 
    -- 班级信息(done)--
}

class ChildrenClass{
    -- children_class: table--
    - id: Long //ID
    - childrenId: Long //学生id
    - classId: Long //班级id
    - created: LocalDateTime //创建时间
    - operator: String  //操作人
    __学生班级关联表(done)__
}

class ChildrenHomeworkResult {
    --children_homework_result--
    - id: Long //分享Id
    - childrenId :Long //学生Id
    - homeworkId: Long// 作业ID
    - childrenName:String //学生名称
    - childrenAvatar:String // 头像
    - title: String// 标题
    - image:String //图片地址
    - rank:Integer //排名
    - studyDays:Integer //学习天数
    - score:Integer // 分数
    - duration:Long //时间
    - lookTimes:Integer 观看次数
    - audio:String //作业音频
    - childrenAudio:String //学生音频
    - url:String //地址
    - version:Long //版本
    - created:LocalDateTime//创建时间
    __学习结果分享__
}



class TeacherClass{
    --teacher_class: table--
    - id: Long// ID
    - userId: Long //老师id
    - classId: Long //班级id
    - created: LocalDateTime //创建时间
    - operator: String  //操作人
    __老师和班级关联表(done)__
}

class SysUserClass{
    --sys_user_class:table--
    - id: Long //ID
    - sysUserId: Long //系统用户Id
    - classId: Long //班级id
    - created: LocalDateTime //创建时间
     - operator: String  //操作人
    __老师和班级关联表(TEMPdone)__
}


class Feedback{
    --feedback: table--
    - id: Long //ID
    - deviceId: String //设备ID
    - userId: Long //用户Id
    - content: String  //内容500字符
    - created: LocalDateTime //创建时间
    __反馈表(done)__
}

class FeedbackImage{
    --feedback_image: table--
    - id: Long //ID
    - feedbackId: Long //反馈id
    - image: String // 图片地址
    - created: LocalDateTime //创建时间
    __反馈图片(done)__
}



class SysUser{
    --sys_user: table--
    - id: Long //Id
    - username: String //登录帐号
    - password: String //密码
    - email: String // 邮件
    - created: LocalDateTime  //创建人
    - modified: LocalDateTime //修改人
    __后台用户表(done)__
}

class SysRole{
    --sys_role: table--
    - id: Long //Id
    - name: String //权限码
    - alias: String //别名
    - comment:String // 备注
    - created: LocalDateTime //创建日期
    - modified: LocalDateTime //修改日期
    __系统权限(done)__
}

class SysAuthorize{
    --sys_authorize--
    - id: Long //Id
    - name: String //权限码
    - alias: String //别名
    - created: LocalDateTime //创建时间
    - modified: LocalDateTime //修改时间
    __授权集合(done)__
}

class SysUserRole{
    --sys_user_role: table--
    - id: Long //Id
    - userId: Long 用户Id
    - roleId: Long //权限Id
    - created: LocalDateTime //创建时间
    __系统用户权限关联(done)__
}

class SysRoleAuthorize{
    --sys_role_Authorize: table--
    - id: Long //ID
    - roleId: Long //权限ID
    - authorizeId: Long //权Id
    - created: LocalDateTime //创建时间
    --系统权限权值关联(done)--
}



class SysHomework{
    --sys_homework: table--
    - id: Long //ID
    - class_id: Long //班级Id
    - type: HomeworkTypeEnum //作业类型
    - state: HomeworkState //作业状态
    - image: String //图片,下级都不填写默认用它
    - title: String //标题
    - subtitle: String //副标题
    - published: LocalDate //发布日期
    - created: LocalDateTime //创建时间
    - modified: LocalDateTime //修改时间
    - operator: String //操作人
    __后台录入作业(done)__
}

enum HomeworkState{
    EDIT,PREVIEW,PROD
    __作业状态__
}
enum HomeworkTypeEnum{
    HOMEWORK,EXPERIENCE
    __作业类型__
}



class SysHomeworkLook{
    --sys_homework_look:table--
    - id: Long // Id
    - classId: Long //班级Id
    - homeworkId: Long //作业Id
    - video: String //视频地址
    - cover: String //封面
    - image: String //图片地址
    - title: String //标题
    - created: LocalDateTime //创建时间
    - modified: LocalDateTime //修改时间
    - operator: String //操作人
    __后台作业视频(done)__
}



class SysHomeworkListen{
    --sys_homework_lesson: table--
    - id: Long //ID
    - classId: Long //班级Id
    - homeworkId: Long //作业Id
    - audio: String //音频地址
    - title: String //标题
    - image: String  //音频图片,不填用作业图片
    - sorter: Integer // 排序
    - created: LocalDateTime  //创建日期
    - modified: LocalDateTime //修改日期
    - operator: String //操作人
    __系统作业听力表(done)__

}

class SysHomeworkExam{
    --sys_homework_exam: table--
    - id: Long //ID
    - classId: Long //班级ID
    - homeworkId: Long //作业Id
    - type: HomeworkExamTypeEnum //作业测试类型
    - title: String //标题
    - audio: String //音频
    - image: String  //图片
    - content: String //内容
    - sorter: Long //排序
    - itemId: Long //正确答案id
    - created: LocalDateTime //创建时间
    - modified: LocalDateTime //修改时间
    - operator: String //操作人
    __系统测试表(done)__
}

enum HomeworkExamTypeEnum{
    READ,CHOICE,SUBJECTIVE
   __作业测试类型__
}

class SysHomeworkExamItem{
    --sys_homework_exam_item--
    - id: Long //ID
    - classId: Long //班级ID
    - homeworkId: Long //作业ID
    - examId: Long //测试Id
    - audio: String //音频地址
    - content: String //内容
    - created: LocalDateTime //创建时间
    - modified: LocalDateTime //修改时间
    - operator: String //操作人
    __系统选择题目(done)__
}


class Homework{
    --homework: table--
    - id: Long //ID
    - class_id: Long //班级Id
    - homeworkId: Long// 作业id
    - type: HomeworkTypeEnum //作业类型
    - image: String //图片,下级都不填写默认用它
    - title: String //标题
    - subtitle: String //副标题
    - published: LocalDate //发布日期
    - created: LocalDateTime //创建时间
    - operator: String //操作人
    __后台录入作业(done)__
}

class HomeworkLook{
    --homework_look:table--
    - id: Long //Id
    - classId: Long //班级Id
    - homeworkId: Long //作业Id
    - lookId: Long //系统视频id
    - video: String //视频地址
    - cover: String //视频封面
    - image: String //图片地址 不填用作业默认
    - title: String //标题
    - created: LocalDateTime //创建日期
    - operator: String //操作人
    __前端作业视频(done)__
}

class HomeworkListen{
    --homework_lesson: table--
    - id: Long //ID
    - classId: Long //班级Id
    - homeworkid: Long //作业Id
    - listenId: Long//系统听力id
    - audio: String //音频Id
    - title: String //标题
    - image: String  //图片地址
    - sorter: Integer //排序
    - created: LocalDateTime //创建时间
    - operator: String //操作人
    __前端听音频(done)__
}


class HomeworkExam{
    --homework_exam: table--
    - id: Long //Id
    - classId: Long //班级Id
    - homeworkId: Long //作业Id
    - examId: Long //对应Id
    - type: HomeworkExamTypeEnum //作业测试类型
    - title: String //标题
    - audio: String // 音频地址
    - image: String  //图片地址
    - content: String // 文本
    - itemId: Long //正确Id
    - created: LocalDateTime //创建时间
    - operator: String //操作人
    __前端测试(done)__
}



class HomeworkExamItem{
    --homework_exam_item: table--
    - id: Long //Id
    - classId: Long //班级Id
    - homeworkId: Long //作业Id
    - examId: Long //测试Id
    - audio: String //音频地址
    - content: String //文本
    - created: LocalDateTime //创建时间
    - operator: String //操作人
    __前端选择题内容(done)__
}


class ChildrenHomework {

    --children_homework: table--
    - id: Long //Id
    - childrenId: Long //儿童Id
    - classId: Long //班级Id
    - homeworkId: Long //作业Id
    - score: Integer //分数
    - duration: Long // 学习时长
    - lookTimes: Integer //看动画次数
    - listened: Long //音频听的下标
    - created: LocalDateTime //创建时间
    - modified: LocalDateTime //修改时间
    __儿童作业表(done)__

}

class ChildrenHomeworkDaily{
    --children_homework_daily--
    - id: Long //ID
    - timeDate: String //日期
    - childrenId: Long //孩子Id
    - homeworkId: Long // 作业Id
    - classId: Long //班级Id
    - duration: Long // 学习时长
    - created: LocalDateTime //创建时间
    - modified: LocalDateTime //修改时间
    __儿童每日学习记录__
}

class ChildHomeworkSubjective{
   --children_homework_subjective: table--
   - id: Long //Id
   - childrenId: Long //儿童Id
   - classId: Long //班级Id
   - homeworkId: Long //作业Id
   - examId: Long  //测试Id
   - rank: Integer // 排名
   - childrenAudio: String //儿童音频
   - created: LocalDateTime //创建时间
   __儿童作业记录(done)__
}

class ChildrenHomeworkState{
    --children_homework_state: table--
    - id: Long  //ID
    - childrenId: Long //儿童Id
    - classId: Long //班级Id
    - homeworkId: Long //作业Id
    - type: HomeworkItemTypeEnum //作业类型Id
    - created: LocalDateTime //创建时间
    __儿童作业状态表(done)__
}


enum HomeworkItemTypeEnum{
    LOOK,LISTEN,EXAM
    __作业类型__
}


class TeacherChildrenHomeworkReply{
    --teacher_children_homework_reply: table--
    - id: Long //Id
    - childrenHomeworkId: Long //儿童作业Id
    - teacherName:String //老师名称
    - audio: String //老师音频
    - content: String //老师回复
    - created: LocalDateTime //创建时间
    - modified: LocalDateTime //修改时间
    __老师回复记录(done)__
}
 



User o-- KnshipTypeEnum
User o-- UserChildren
UserChildren o-- Children
Children o-- ChildrenTypeEnum

Children o-- ChildrenClass
ChildrenClass o-- EnjoyClass

SysUser o-- SysUserRole
SysUserRole o-- SysRole
SysRole o-- SysRoleAuthorize
SysRoleAuthorize o-- SysAuthorize


SysUserClass o-- EnjoyClass

SysHomework o-- SysHomeworkLook

SysHomework o-- SysHomeworkListen

SysHomework o-- SysHomeworkExam


SysHomework o-- HomeworkState

SysHomework o-- HomeworkTypeEnum


SysHomeworkExam o-- HomeworkExamTypeEnum
SysHomeworkExam o-- SysHomeworkExamItem



Homework o-- HomeworkLook
Homework o-- HomeworkListen
Homework o-- HomeworkExam



HomeworkExam o-- HomeworkExamItem

HomeworkExam o-- HomeworkExamTypeEnum


Children o-- ChildrenHomeworkState
Children o-- ChildrenHomework
ChildrenHomework o--ChildHomeworkSubjective

ChildrenHomework o--ChildrenHomeworkDaily

ChildrenHomeworkState o-- HomeworkItemTypeEnum

ChildrenHomework o-- TeacherChildrenHomeworkReply

AppDevice o-- ExperienceHomework
ExperienceHomework o-- ExperienceHomeworkState
ExperienceHomework o-- ExperienceHomeworkSubjective
ExperienceHomeworkState o-- HomeworkItemTypeEnum


ChildrenHomeworkResult o-- ChildrenHomework

Feedback o-- FeedbackImage
@enduml

**Comment by qjebbs** [comment]
Weird. It's all good here. can the � characters be the problem? Can you send a minimal file that can reproduce this problem? (qjebbs@gmail.com)

**Comment by qingshannet** [comment]
@dylanleung , how do you address the issue? I've met the same problem. thanks
