### ISSUE TITLE
Disrupting autocompletions with recent update

### ISSUE THREAD

**Issue by sandersaares** [qjebbs/vscode-plantuml#124]
A recent update to the plugin appears to have added some autocompletion snippets that really interfere with typing.

Here I am trying to define a new component in a component diagram. As I type it, the autocompletion list in the screenshot shows up:

![](https://i.imgur.com/rJNCALH.png)

I now press enter because I am finished typing my line. BLAM! Suddenly my "as A" is replaced by some `:do something;` snippet I care nothing about. This change disrupts my work quite a lot. I request that this interruption to my typing experience be eliminated. Snippets should not automatically come into being just by normal typing. I should not need to do some special keystrokes (ESC) to get the text that I typed on my keyboard to actually stay in the document.

**Comment by qjebbs** [comment]
Added `;` to snippets prefixes, I searched whole PlantUML document, the symbol is only used in activity definition (`:action;`), and always appears at line end, so it has no chance disrupting your typing now.
