### ISSUE TITLE
Preview failed

### ISSUE THREAD

**Issue by qingshannet** [qjebbs/vscode-plantuml#125]
When new version applied, my preview simply gone. Even a very simple file

![4edc67fc-ce9f-4a0b-929e-1772f2298f07](https://user-images.githubusercontent.com/38913225/40760823-22f9d602-64cb-11e8-8f52-2d53c277396e.jpg)

![3461ff28-2d46-4e78-bdc5-93d60aba29a6](https://user-images.githubusercontent.com/38913225/40760893-7e1e46d0-64cb-11e8-87c1-945e7a7bb420.jpg)

**Comment by qingshannet** [comment]
Export is fine

**Comment by qingshannet** [comment]
Here is my file
[prj_process.wsd.zip](https://github.com/qjebbs/vscode-plantuml/files/2056620/prj_process.wsd.zip)

**Comment by qjebbs** [comment]
It took me long time to locate the problem.
I don't know how, but you put `\x08` between `(` and `不`, and many of others,  which cause the problem.

Following is the text I copy&paste directly from your file:

```js
repeat while (不满足开发需求)
```

 So your svg export won't be fine:
![2018-06-01 2 05 45](https://user-images.githubusercontent.com/16953333/40823976-e83ea468-65a4-11e8-867d-d3da21bb685c.png)

So as the https://github.com/qjebbs/vscode-plantuml/issues/123.
