### ISSUE TITLE
Use $PATH to look for dot binary

### ISSUE THREAD

**Issue by pasqui23** [qjebbs/vscode-plantuml#126]
Nixos is a peculiar distribution,whit all software outside of either `/bin`or `/usr/bin`.
This mean that whenever I try to do a local preview I get an error that `/usr/bin/dot` is not found,even through  I have `dot` in my `$PATH` and I can call it normally from my command line

**Comment by qjebbs** [comment]
Try (https://github.com/qjebbs/vscode-plantuml/issues/94):
```json
"plantuml.commandArgs": [
    "-DGRAPHVIZ_DOT=path/to/dot",
]
```
