### ISSUE TITLE
no preview and export

### ISSUE THREAD

**Issue by brammieboy12** [qjebbs/vscode-plantuml#127]
when i make a UML diagram i get no preview. ]after i export, i get a runtime error: " A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f233598a009, pid=9806, tid=9807

 JRE version: OpenJDK Runtime Environment (9.0) (build 9-internal+0-2016-04-14-195246.buildd.src)
 Java VM: OpenJDK 64-Bit Server VM (9-internal+0-2016-04-14-195246.buildd.src, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
 Problematic frame:
 C  [libjava.so+0x1d009]  JNU_GetEnv+0x19

 Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/student/core.9806)

 An error report file with more information is saved as:
 /home/student/hs_err_pid9806.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug."

i have graphviz installed just as JRE 9

![image](https://user-images.githubusercontent.com/28558841/41656645-006a42ae-7491-11e8-9323-f53ba20b39cb.png)

**Comment by qjebbs** [comment]
hmmm...It seems that it is out of scope of this extension implementation. The calling stack is:

1. This extension
2. Java
3. plantuml.jar
4. graphviz or other native code?

The error is likely happened in the 4th part, too far away to reach. Please search the web to see if there is any answer.
