### ISSUE TITLE
Disable editor.formatOnSave only for PlantUML

### ISSUE THREAD

**Issue by gnaeus** [qjebbs/vscode-plantuml#130]
I have the following code:

![good](https://user-images.githubusercontent.com/4706707/42690162-f2280802-86ab-11e8-80be-858f81346669.png) 
![res](https://user-images.githubusercontent.com/4706707/42690186-022c3796-86ac-11e8-896a-800d78b421e6.png)

But when I save the document, extension formats it as:

![bad](https://user-images.githubusercontent.com/4706707/42690367-955ac136-86ac-11e8-91e6-84f171e4edae.png)

It seems that JSON-like string `{ Id: 1 }` breaks auto formatting.
How can I completely disable `editor.formatOnSave` only for PlantUML files?

**Comment by qjebbs** [comment]
I cannot distinguish the format request is from user or `onSave`, so I just simply disabled formatter if `editor.formatOnSave` is on.

**Comment by gnaeus** [comment]
Thanks! It's very helpful.
