### ISSUE TITLE
Unable to open in visio format

### ISSUE THREAD

**Issue by jgothoskar** [qjebbs/vscode-plantuml#132]
Hi i am trying to export a file in .vdx format and it generate the file successfully. But when i open the same in visio everything is coming as blank and only shapes are displayed but it does not show the interaction or names or any other comments entered during the creating of this diagram.
Please see attached file.
[test.zip](https://github.com/qjebbs/vscode-plantuml/files/2211722/test.zip)

**Comment by qjebbs** [comment]
Can you try direct export with command line: http://plantuml.com/command-line

The extension is just an agent helps you work with plantuml in vscode, so you have to make sure if the plantuml works as expect.

**Comment by jgothoskar** [comment]
Yes i tried that just now and same issue now
[test.zip](https://github.com/qjebbs/vscode-plantuml/files/2215206/test.zip)

**Comment by qjebbs** [comment]
Please post feedbacks to http://forum.plantuml.net/, this issue is out of scope of the extension.
