### ISSUE TITLE
User snippets support

### ISSUE THREAD

**Issue by c835722** [qjebbs/vscode-plantuml#133]
Hi @qjebbs ,
When I have the plugin installed I don't seem to be able to create a User snippet for a diagam.puml file.
When I do an F1 Insert snippet all I see is the Extension Snippets but not my User snippets from my plantuml.json snippet file.

Questions.
Do User snippets work with this plugin? (If so how).
Is the plugin is in some way interfering with this vscode native facility and it so can we develop a fix? (happy to work with you on that)

Cheers.

**Comment by qjebbs** [comment]
I think user snippets is globally supported by VSCode, nothing to do with this extension, you'd better make sure add them in right way...

**Comment by c835722** [comment]
Fair enough. Agree its a little tricky.
I'm pretty sure I'm adding them the right way because it is working for javascript and typescript for both User and Extention snippets (in the fashion I described above). Just not working for me for plantuml. (thus my query here) Thanks for the help. I'll keep trying to get it to trigger and report back if I determine what works.

**Comment by qjebbs** [comment]
Probably the snippet language problem. When select language, choose `diagram`, I don't see `plantuml` here..

**Comment by qjebbs** [comment]
PS: I tried to add user snippet for `diagram` and it works as expected.

**Comment by c835722** [comment]
Tried diagram (rather than plantuml (which I assumed for plantuml diagrams)) and it also worked for me!
Awesome. 🥇 👍 
Thanks.
