### ISSUE TITLE
Large diagram looks fine on preview, but cut off on export

### ISSUE THREAD

**Issue by kenorb** [qjebbs/vscode-plantuml#136]
This is problem with large diagrams. They look fine on the preview, but when exported to PNG, it looks cut off.

Example file: [Binance.wsd.zip](https://github.com/qjebbs/vscode-plantuml/files/2238396/Binance.wsd.zip)

**Comment by qjebbs** [comment]
This a known limit by plantuml, not the extension. Please search `DPLANTUML_LIMIT_SIZE ` on [this page](http://plantuml.com/faq). Or, just export svg the avoid the limit.

**Comment by arnauldvm** [comment]
Would it be possible to add a configuration parameter for the extension, for example `plantuml.limitSize` (defaulting to 4192), and use it when invoking java : `java -DPLANTUML_LIMIT_SIZE={plantuml.limitSize} ...`?

It would be cleaner than modifying the global environment variable!

**Comment by qjebbs** [comment]
see 
https://github.com/qjebbs/vscode-plantuml#extension-settings

**Comment by ScissorHill** [comment]
I tried changing the settings.json thus, but it seems to have no impact, the PNG is still cut off:
```
{
    "workbench.colorTheme": "Default Light+",
    "window.zoomLevel": 1,
    "security.workspace.trust.untrustedFiles": "open",
    "-DPLANTUML_LIMIT_SIZE": 8192
}
```
Am I missing something? I tried removing the `-D` as well.

**Comment by shin5884** [comment]
try this in settings.json
```
{
    "plantuml.commandArgs": [
        "-DPLANTUML_LIMIT_SIZE=8192"
    ]
}
```
