### ISSUE TITLE
Support for +- as alias for activate/deactivate

### ISSUE THREAD

**Issue by unmultimedio** [qjebbs/vscode-plantuml#137]
Hello, as you can see in the site https://www.websequencediagrams.com/, you can activate a participant and deactivate it just by appending a + and - to the arrow, so something like:

```
Server -> API: Check code
activate API
API -> Server: Code verification
deactivate API
```

Could become

```
Server -> +API: Check code
API -> -Server: Code verification
```

![untitled](https://user-images.githubusercontent.com/4431392/43650775-48212148-9706-11e8-96df-cff795532402.png)

**Comment by qjebbs** [comment]
Hi, this project is only an extension which helps you use PlantUML in VSCode, not the PlantUML itself. Please submit requests to PlantUML project.

**Comment by unmultimedio** [comment]
Thanks for your response @qjebbs , you know where they host it? Is it on github?
