### ISSUE TITLE
Preview not  available

### ISSUE THREAD

**Issue by NTPLThavarajan** [qjebbs/vscode-plantuml#143]
Issue Type: <b>Bug</b>

create a simple class diagram try the preview

Extension version: 2.8.5
VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570T CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (3.54GB free)|
|Process Argv|C:\Users\thavarajan.m\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe --folder-uri file:///e%3A//Projects/POCS/Maf%20FrontEND||Screen Reader|no|
|VM|0%|

</details>

**Comment by qjebbs** [comment]
I don't have insider installed, not sure if it's a temporary bug of insider or not. Better to wait for 1.28 stable to see what happens.

PS: Works fine in latest 1.27 stable.

**Comment by NTPLThavarajan** [comment]
yes, it might be a temporary,  it got fixed
