### ISSUE TITLE
Setting plantuml.jar has no effect

### ISSUE THREAD

**Issue by RedX2501** [qjebbs/vscode-plantuml#147]
Using

    @startuml
    version
    @enduml

I can see that the version i have set in `settings.json` is not picked up:

{
    "plantuml.jar": "${workspaceFolder}/.vscode/plantuml.1.2018.10.jar"
}

It seems it does work but a full path must be specified.

It would be nice if the variable ${workspaceFolder} could be used so the settings file is agnostic of the PC it is running on. Or event if relative paths to the workspace could be given.

Plugin version: 2.9.0

**Comment by RedX2501** [comment]
I'm still having troubles with this in 2.10.6

Now I added some debug code in config.js:

```
let jar = this.read('jar', uri, (folderUri, value) => {
                if (!value)
                    return "";
                if (!path.isAbsolute(value))
                    value = path.join(folderUri.fsPath, value);
                return value;
            });
            console.log(jar);
            let intJar = path.join(common_1.extensionPath, "plantuml.jar");
            console.log(intJar);
            if (!jar) {
                jar = intJar;
            }
            else {
                if (!fs.existsSync(jar)) {
                    vscode.window.showWarningMessage(common_1.localize(19, null));
                    jar = intJar;
                }
            }
            this._jar[folderPath] = jar;
            return jar;
```
I'm always getting the cannot resolve plantuml.jar setting message (Id 19).
What I see in the console is the unresolved `${workspaceFolder}` variable in the file I provided.

**Comment by qjebbs** [comment]
My fault that I removed the eval feature by this commit: https://github.com/qjebbs/vscode-plantuml/commit/7bd077d91fe71b9e813e1fb52c0ae04bbcd9078b
because it brings unwanted behavior to windows paths.

But the following should still work:


```json
{
    "plantuml.jar": ".vscode/plantuml.1.2018.10.jar"
}
```

Can you try it?

**Comment by RedX2501** [comment]
I'm trying to use `tools/plantuml.1.2018.10.jar` and it does not. Because path.isAbsolute seems to be returning true and thus the workspaceFolder is not being prepended.

**Comment by qjebbs** [comment]
1. You have to open the folder, `folderUri` won't be null then.
1. make sure the relative path is correct, becuase:

```js
if (!fs.existsSync(jar)) {
                    vscode.window.showWarningMessage(localize(19, null));
                    jar = intJar;
                }
```

I test a relative jar path works as expected here.

**Comment by RedX2501** [comment]
I'm opening a folder with a .vscode directory in it.

![Image](https://pasteboard.co/I5mc7ao.png)

I have added more debug info.

**Comment by qjebbs** [comment]
@RedX2501 Doesn't see anything..

```
Project
|__.vscode
   |__settings.json
|__tools
   |__plantuml.jar
|__src
   |__diagrams.puml
```
Make the following setting in workspace setting (`Project/.vscode/settings.json`). Edit in user setting also do the job, but not recommended, which means all projects use their own jar in `tools` folder.

```json
{
    "plantuml.jar": "tools/plantuml.jar",
}
```

Should work as expected.

**Comment by RedX2501** [comment]
@qjebbs  I was having problems uploading. It should work now.

**Comment by qjebbs** [comment]
OK, good to hear..

**Comment by RedX2501** [comment]
I mean the image should work, the problem is still there.

**Comment by RedX2501** [comment]
Ok, I think i see know what is going on.

When I start it will try to get the config for Uri null, which results in folderPath being empty. So a config is cached for the empty folderPath which does not find the jar file because it cannot resolve the relative path.

When i then press 'alt+d' to see the preview for the file it will now try with a proper uri and the cache will not have the entry for the new folderPath, now it will try to resolve and it will work.

**Comment by qjebbs** [comment]
@RedX2501 I see, it a false alarm, if you preview or export, you setting should have been applied. I'll fix it in next release.
