### ISSUE TITLE
Support for VS 2015

### ISSUE THREAD

**Issue by rhodrycz** [qjebbs/vscode-plantuml#15]
Hi!

I really like the idea of this extension. However, would it be possible to support also Visual Studio 2015? I am working on a small for fun project with friends and we decided to use PlantUML for our modeling. I would very appreciate to have possibility to edit directly in VS instead of some external tool.

Can this be done? I honestly have no idea how these extensions are made, if there is some compatibility between VS2015 and VSCode or it needs to be completely rewritten.

**Comment by qjebbs** [comment]
I have no idea about VS plugin API, it may be hard to port to VS (totally rewrite needed) since I am very busy working.

Anyway, this plugin (and its thoughts) is open source, hope someone who familiar with VS will do this job.

**Comment by qjebbs** [comment]
I've no idea either. Dot net JavaScript engine like [jurassic](https://github.com/paulbartrum/jurassic) may help.
