### ISSUE TITLE
!include with PlantUML Version 1.2018.11 doesn't work

### ISSUE THREAD

**Issue by zimtkeks** [qjebbs/vscode-plantuml#150]
Hi, I highly appreciate your work and I'm using this plugin regularly.

I tried out the latest PlantUML-release 1.2018.11 (which I prefer due to improvements in the preprocessor) with your plugin by swapping the plantuml.jar of v2.9.2 with PlantUML Version 1.2018.11 downloaded from plantuml.com.
I noticed that include-files are not found anymore in at least some cases. The simplest case consists of two files in the same directory: _A.puml_ and _inc.iuml_. A includes inc like this: `!include_many inc.iuml`. When _A.puml_ is rendered in VSCode, I get an error about not being able to include _inc.iuml_.

Maybe something changed in PlantUML to require a different kind of invocation. However, if I render _A.puml_ using 1.2018.11 from the command-line, !include works just fine.

Thanks for taking a look!

**Comment by qjebbs** [comment]
Same here, I guess the latest release has broke the `user.dir` environment setting logic, I cannot find any change notice (or anyone can tell?). Better to open a issue in [plantuml forum](http://forum.plantuml.net/)

**Comment by qjebbs** [comment]
Wait for the `Plantuml` Project to fix:

http://forum.plantuml.net/8338/latest-plantuml-version-1-2018-11-cannot-include-with-pipe
