### ISSUE TITLE
Bug - Simple Use Cases are not Working

### ISSUE THREAD

**Issue by LEsperanca** [qjebbs/vscode-plantuml#151]
use cases are not working

```
@startuml
actor user
user -> (Get Error Metadata)
@enduml
```

**Comment by qjebbs** [comment]
what do you mean by not working?

Here what I got
![image](https://user-images.githubusercontent.com/16953333/46510351-0712b800-c87b-11e8-8b42-9f184e7ffbc2.png)

**Comment by qjebbs** [comment]
Not much information provided, closing now. Suggest give more detail and reopen it, if still have problem.
