### ISSUE TITLE
Can't export to HTML and PDF

### ISSUE THREAD

**Issue by zoulja** [qjebbs/vscode-plantuml#154]
Win7X64, VS Code 1.27.2, vscode-plantuml 2.9.4
By some reason export to HTML and PDF doesn't work for me.
I use default settings (I believe it means local render)
**HTML**
> Error found in diagram X
> java.lang.UnsupportedOperationException: HTML
> 	at net.sourceforge.plantuml.ugraphic.ImageBuilder.createUGraphic(ImageBuilder.java:390)
> 	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:236)
> 	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:177)
> 	at net.sourceforge.plantuml.sequencediagram.graphic.SequenceDiagramFileMakerPuma2.createOne(SequenceDiagramFileMakerPuma2.java:234)
> 	at net.sourceforge.plantuml.sequencediagram.SequenceDiagram.exportDiagramInternal(SequenceDiagram.java:249)
> 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:231)
> 	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
> 	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
> 	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:100)
> 	at net.sourceforge.plantuml.Run.managePipe(Run.java:290)
> 	at net.sourceforge.plantuml.Run.main(Run.java:141)
> Exception in thread "main" java.lang.UnsupportedOperationException: HTML
> 	at net.sourceforge.plantuml.ugraphic.ImageBuilder.createUGraphic(ImageBuilder.java:390)
> 	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:236)
> 	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:177)
> 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:284)
> 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:246)
> 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:239)
> 	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
> 	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
> 	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:100)
> 	at net.sourceforge.plantuml.Run.managePipe(Run.java:290)
> 	at net.sourceforge.plantuml.Run.main(Run.java:141)
> 
_Since it doesn't work so I'm not sure what kind of HTML is expected here.
Actually for my needs single file with embedded SVG would be optimal choice_

**PDF**
> java.lang.ClassNotFoundException: org.apache.batik.apps.rasterizer.SVGConverter
> 	at java.net.URLClassLoader.findClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Unknown Source)
> 	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:53)
> 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:366)
> 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:227)
> 	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
> 	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
> 	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:100)
> 	at net.sourceforge.plantuml.Run.managePipe(Run.java:290)
> 	at net.sourceforge.plantuml.Run.main(Run.java:141)
> Exception in thread "main" java.lang.UnsupportedOperationException
> 	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:72)
> 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:366)
> 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:227)
> 	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
> 	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
> 	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:100)
> 	at net.sourceforge.plantuml.Run.managePipe(Run.java:290)
> 	at net.sourceforge.plantuml.Run.main(Run.java:141)

**Comment by qjebbs** [comment]
It's out the scope of this extension development. 

For PDF, you should use custom jar, together with many dependency jars. See http://plantuml.com/pdf
For HTML, you'd better search by yourself, or send feedbacks to http://forum.plantuml.net/

**Comment by wyz2019** [comment]
Since PDF cannot be exported, why add the PDF option

**Comment by matthewberryman** [comment]
> Since PDF cannot be exported, why add the PDF option

PDF can be exported, just not by the embedded copy of PlantUML.
Changing the embedded copy to the version that supports PDF would add another ~12MB to the size of the extension.
Steps to get PDF export going:
1. Look for the latest release on https://github.com/plantuml/plantuml/releases
2. Click to on the arrow next to "assets" to expand the list of assets.
3. Look for the one named plantuml-pdf-[version_string].jar and download.
4. In VScode settings set 
```json
"plantuml.jar": "/path/to/downloaded.jar",
```

Or point the extension at a server with PDF support.

**Comment by wyz2019** [comment]
![1](https://github.com/qjebbs/vscode-plantuml/assets/57739555/51243a70-71a3-4e5f-853e-29c7b51175eb)
![2](https://github.com/qjebbs/vscode-plantuml/assets/57739555/405e5a66-d39e-42ff-9fd1-8b2c53ed101b)
I am not particularly familiar with vscode, can you guide me on where this configuration should be written
I will copy the downloaded plantuml pdf SNAPSHOT. jar here
C:\Users\28601\.vscode\extensions\jebbs.plantuml-2.18.1
Setting.json added a line like this, but reported an error
"SettingsSync. ignoredSettings":[
"- plan. exportCurrency",
"- plantuml. jar",
"- plantuml. java",
"- plantuml. server",
"- plantuml. extender"
],
"Plantuml. jarArgs":[
],
**"Plantuml. jar": "/plantuml pdf SNAPSHOT. jar",**
"Plantuml. extender": "Local",
"Plantuml. server":“ https://www.plantuml.com/plantuml ",",
"Editor. largeFileOptimizations": false,
"Python. formatting. provider": "none",
"Python. autoComplete. extraPaths":[
        
],
"Python. analysis. extraPaths": [],
"Typescript. local": "zh CN",
"Plantuml. commandArgs":[
        
]

**Comment by matthewberryman** [comment]
a) You probably don't want to place it inside the same folder as used by the extension, since when the extension gets upgraded you might lose it? It should be placed somewhere outside of the extension folder, say `C:\Users\myusername\Documents\plantuml-pdf-SNAPSHOT.jar`
b) You need to specify the full path to the file for `"plantuml.jar"`, including (on Windows) the drive letter, e.g `"C:/Users/myusername/Documents/plantuml-pdf-SNAPSHOT.jar"`
Note the `\` needs to be replaced either by `/` or `\\`

**Comment by wyz2019** [comment]
[](url)Thank you.
This error has been eliminated, but there is a new issue where the text in the exported PDF is garbled
I have tried using garbled characters in both Chinese and Japanese.
And if encountering a newpage
The task of exporting the PDF will [terminate]()
I also installed the Times Bold font
![Snipaste_2024-06-22_12-36-10](https://github.com/qjebbs/vscode-plantuml/assets/57739555/b42e5b7d-c14c-4b87-b9d1-e7ef49124376)
![Snipaste_2024-06-22_12-36-55](https://github.com/qjebbs/vscode-plantuml/assets/57739555/56779c50-4426-4091-b531-2b7ff1b28fd1)
![Snipaste_2024-06-22_12-44-13](https://github.com/qjebbs/vscode-plantuml/assets/57739555/bbec06dc-e459-4133-a7a0-11b40399013a)

**Comment by matthewberryman** [comment]
PlantUML doesn't yet support Chinese characters when exporting direct to PDFs. https://github.com/plantuml/plantuml/issues/1426

You might be better off exporting to SVG and then using another tool to convert to PDF
