### ISSUE TITLE
How to check plantuml.jarArgs really works?

### ISSUE THREAD

**Issue by zoulja** [qjebbs/vscode-plantuml#155]
I'm experiencing issues with encoding of my diagrams.
Steps:
1. Create diagram
2. Export as PNG
3. Now extract diagram source from image

Expected result: all text is readable.
Actual result: text in local encoding is unreadable. Description after extraction says "Default Encoding: Cp1252"

After reading PlantUML FAQ I tried to add "plantuml.jarArgs": ["-charset","UTF-8"] (also I tried to set LANG in "plantuml.commandArgs"), but result still the same.

Any ideas how it can be fixed and how I can verify work of plantuml.jarArgs?

**Comment by qjebbs** [comment]
Please use command line (with args you want) to extract the source, if the extension behaviors different, then report issues here.
