### ISSUE TITLE
Using teoz will incorrectly show info/debug messages as errors

### ISSUE THREAD

**Issue by ginomempin** [qjebbs/vscode-plantuml#156]
When using the teoz architecture (http://plantuml.com/teoz), plantuml will output/print-out info/debug messages, and the preview displays them as errors.

![plantuml-teoz-shows-info-messages](https://user-images.githubusercontent.com/6091865/46705839-4ae73200-cc6c-11e8-898d-e42befa459f7.jpg)

Depending on the contents of the .plantuml file, there can be a lot of info/debug messages. They don't seem to be errors because the image is generated successfully and correctly. Putting the `-failfast` or `-failfast2` switch also doesn't abort the image generation. Putting `-quiet` does not silence them. 

I reported this to PlantUML (http://forum.plantuml.net/8340/how-turn-off-info-messages-when-generating-image-using-teoz), and they released a beta version to fix this:  http://beta.plantuml.net/plantuml.jar (V1.2018.12beta6). I currently set the `"plantuml.jar"` setting to point to this new JAR.

I think it will be a good idea to integrate this new JAR with the plugin for a future release.  

---

PlantUML VS Code extension 2.9.4
VS Code 1.28.0
Ubuntu 16.04

**Comment by qjebbs** [comment]
Thanks for feedback, I'll upgrade it on their official release, in case more issues are fixes (Like https://github.com/qjebbs/vscode-plantuml/issues/150, and others), and be more stable.
