### ISSUE TITLE
Sequence diagram doesn't work anymore

### ISSUE THREAD

**Issue by bovandersteene** [qjebbs/vscode-plantuml#159]
Since the latest version I'm unable to regenerate my sequence diagrams anymore.
I use for example 'box' to combine some participants that are under the same hierarchy, also the usage of alt else is broken

For example: 
Example code taken from plantuml
```

@startuml
actor Foo1
boundary Foo2
control Foo3
entity Foo4
database Foo5
collections Foo6
Foo1 -> Foo2 : To boundary
Foo1 -> Foo3 : To control
Foo1 -> Foo4 : To entity
Foo1 -> Foo5 : To database
Foo1 -> Foo6 : To collections

@enduml

```
generates: 
![image](https://user-images.githubusercontent.com/1673799/46865561-419dc700-ce1e-11e8-84ad-d49c5e716699.png)
instead of ![image](http://s.plantuml.com/imgw/sequence-diagram-p6n6vmze.png)

With box
``
@startuml

box "Internal Service" #LightBlue
	participant Bob
	participant Alice
end box
participant Other

Bob -> Alice : hello
Alice -> Other : hello

@enduml

``
gives:
![image](https://user-images.githubusercontent.com/1673799/46865619-7447bf80-ce1e-11e8-9826-4e1aa3a9a2d4.png)

alt else example
``
@startuml
Alice -> Bob: Authentication Request

alt successful case

	Bob -> Alice: Authentication Accepted

else some kind of failure

	Bob -> Alice: Authentication Failure
	group My own label
		Alice -> Log : Log attack start
	    loop 1000 times
	        Alice -> Bob: DNS Attack
	    end
		Alice -> Log : Log attack end
	end

else Another type of failure

   Bob -> Alice: Please repeat

end
@enduml

``
gives 
![image](https://user-images.githubusercontent.com/1673799/46865672-9f321380-ce1e-11e8-820b-d2558770200a.png)

**Comment by qjebbs** [comment]
I tested OK with integrated jar, you may use another version of `plantuml.jar`, if that version didn't work, please report to [this forum](http://forum.plantuml.net)

**Comment by bovandersteene** [comment]
Ok thx I've found the issue,

It was because I was using 
```left to right direction```
in my plantuml.config file

**Comment by qjebbs** [comment]
Happy you located the problem, closing..
