### ISSUE TITLE
More detailed install instructions

### ISSUE THREAD

**Issue by StefanSchubert** [qjebbs/vscode-plantuml#16]
Hi, 

to make more users utilize the solution could you provide a fool prove install instruction.
I already use plantuml frequently in IntelliJ but would love to do so also for c# projects on visual studio (2015).

However I'm running in some probs here. 
What is the extension root and where to find it? 
Launching VS Code Quick Open (CTRL+P) launches the printer menu...where to find it?
You see, I'm rather new to VS.

Anyway thanks for the plugin ;-)

**Comment by qjebbs** [comment]
Thank you for your suggestion. I'll try to make it more detailed.

Actually I publish plugin with plantuml.jar, user don't have to find the extension root path.

**Comment by onovotny** [comment]
@qjebbs how often do you update the embedded plantuml jar?

**Comment by qjebbs** [comment]
@onovotny Not very often in the past, I will update it in next release. Thanks for your reminder.

**Comment by onovotny** [comment]
Might be nice to have a setting to specify an alternate location for the jar...

**Comment by qjebbs** [comment]
@onovotny Good idea.
