### ISSUE TITLE
关于导出和预览问题

### ISSUE THREAD

**Issue by CRAZYFAKE** [qjebbs/vscode-plantuml#161]
使用插件预览时, 图片非常清晰, 但是导出png却模糊的不行, 请问需要设置什么参数吗?

**Comment by CRAZYFAKE** [comment]
@qjebbs

**Comment by qjebbs** [comment]
你可以尝试导出为 `svg` 是否满足需求。更多的，建议你查下`位图`和`矢量图`的区别，预览实际上用的是svg，可以无限放大。

或者：

在代码中加入 `scale 2` 把图放大2倍。

**Comment by CRAZYFAKE** [comment]
👌 Thank you very much~~

**Comment by challenger0119** [comment]
修改下默认的dpi

skinparam dpi 150
