### ISSUE TITLE
ditaa diagrams not working on md

### ISSUE THREAD

**Issue by paulbombarde** [qjebbs/vscode-plantuml#162]
Hello,

ditaa diagrams are not rendered in md preview anymore, while they are still ok with Alt-d preview.
dot diagrams are ok though.

Sample ditaa (from the plantuml website):

```plantuml
@startditaa
+--------+   +-------+    +-------+
|        +---+ ditaa +--> |       |
|  Text  |   +-------+    |diagram|
|Document|   |!magic!|    |       |
|     {d}|   |       |    |       |
+---+----+   +-------+    +-------+
	:                         ^
	|       Lots of work      |
	+-------------------------+
@endditaa
```

Best regards,
Paul

**Comment by qjebbs** [comment]
It's a problem that PlantUML doesn't support `svg` output for `ditaa` diagrams

**Comment by paulbombarde** [comment]
Works now 👍 

Thanks a lot for the quick support !
