### ISSUE TITLE
"Syntax error: salt" when trying to preview salt diagram

### ISSUE THREAD

**Issue by sandersaares** [qjebbs/vscode-plantuml#164]
I am trying to make a salt diagram. Here is my file (the first example from plantuml.com):

```
@startuml
salt
{
  Just plain text
  [This is my button]
  ()  Unchecked radio
  (X) Checked radio
  []  Unchecked box
  [X] Checked box
  "Enter text here   "
  ^This is a droplist^
}
@enduml
```

Here is the preview result:

![image](https://user-images.githubusercontent.com/9914262/47547961-0f04cb80-d900-11e8-9d28-823e381eb6c9.png)

(The skinparam is config-specified to work around a PlantUML defect for component diagrams).

Also cross-posted to PlantUML forums since I suspect this is more a PlantUML issue: http://forum.plantuml.net/8491/skinparam-from-command-line-breaks-salt-diagrams

**Comment by qjebbs** [comment]
I think they didn't realize you put (by all means) this param for all type of diagrams.

The `plantuml` strictly checks for the first content line to be `salt` for Salt, when you include some other things, it violates the rule... Nothing I can help within the scope of this extension development. I suggest you to replace another jar with setting `plantuml.jar`. 

Let me know if any latest release of jar solve your problem, and I'll update the integrated.

**Comment by sandersaares** [comment]
OK. I'll mark this as closed then and report back if there is anything I see that you could do here. Hopefully PlantUML developers can make it so that the skinparam argument and the salt syntax are not in conflict - that seems the most universal solution.
