### ISSUE TITLE
[Poll] includeSearch default setting

### ISSUE THREAD

**Issue by qjebbs** [qjebbs/vscode-plantuml#166]
Sorry about frequently change of `plantuml.includeSearch` setting, but seems it cannot satisfy all users.

`plantuml.includeSearch` specifies the base directory of include files search.

- `DiagramsRoot`: use the 'diagramsRoot', including path is consistent for all files workspace folder.
- `SourceFileDir`: the directory of source file, including path may change between files.

`DiagramsRoot` makes including path consistent for all files in workspace folder, much easier to manager. 

`SourceFileDir` is the traditional way that existing projects rely on it, and someone gives another scenes, to be compatible with other plantuml editors, beacuse they still use the  traditional way.

Which one should be made default, please share your idea...

**Comment by HugoTigre** [comment]
For me it makes sense the 'SourceFileDIr' it's what I basically assume when I think of relative path, "from where I am", sort of way. 

Has an example this is how the plugin PlantUML for intellij works.

Sharing a root path from all workspaces doesn't seem that useful or intuitive, I'm sure there are some use cases, but this will also break if you open the diagram from anywhere else.

**Comment by qjebbs** [comment]
@HugoTigre I'll keep the pool open, but here I want to supplement some idea:

1. Besides easy to write, consistent including path makes it painless when you re-construct your folders. Think about the `SourceFileDir ` way, you may have to modify many many affected files. That's why I made `DiagramsRoot` the default.
1. For any other concerns like yours, someone may want the traditional way, it's still easy to accomplish(without any change to the extension):
    1. Config the user setting to `SourceFileDir `, which applies to all your projects, this is your default setting personally.
    1. Config the workspace setting to override the user setting if needed

**Comment by HugoTigre** [comment]
hello,

I understand that, that's why I updated to 5 stars. I still think
SourceFileDir should be the default, but it's not really a problem either
since it can be changed.

Keep up the good work and thanks for this anwesome plug-in.

**Comment by qjebbs** [comment]
Switch to new logic presented in #221, this poll is not needed anymore.
