### ISSUE TITLE
PlantUML Preview spams creation of Java processes

### ISSUE THREAD

**Issue by coldacid** [qjebbs/vscode-plantuml#168]
When editing a diagram being previewed, the PlantUML plugin creates a new Java process for PlantUML every time the diagram code is changed, without cleaning/killing any existing Java processes. This causes a lot of resource contention and slows down the computer, sometimes to the point of unusability (depending on resources available and/or user's typing speed).

Whenever updating a preview, the plugin needs to kill off any other Java processes it has already created for that preview window. It may also be good to wait until there have been no changes for half a second before starting up a Java process for PlantUML.

**Comment by coldacid** [comment]
And no, "upgrade your computer" is not a valid response to this, especially when the computer I experience this on the most is provided by my employer and not mine to upgrade.

**Comment by qjebbs** [comment]
Processes clean & update delay are all implemented at the very beginning of this project...And it works as expected here.

**Comment by coldacid** [comment]
Well, it's not happening on latest VSCode release on my work machine. And closing the preview wouldn't stop it, either. Instead, the preview would open back up whenever one of the Java processes finished.

**Comment by coldacid** [comment]
Unfortunately it doesn't look like your plugin leaves any relevant log messages, if any messages at all. Nothing in the console log output from `code --verbose --log debug` and nothing in the Output pane for PlantUML inside VS Code either. The plugin needs to log what it's doing if I'm to be able to provide more helpful data.

**Comment by qjebbs** [comment]
Can you leave the extension, software, os versions? Or you can clone and debug in your own environment, key code here:

https://github.com/qjebbs/vscode-plantuml/blob/d8f73ee1f12c9e0da22f668c9e43b4a4f1081b58/src/providers/previewer.ts#L103-L108

**Comment by qjebbs** [comment]
closed due to no more feedback..

**Comment by rspielmann** [comment]
I'd like to request that this issue be reopened. I am facing the same problem with the following setup:

Linux Mint 19.1 Tessa

Info from VS Code:

    Version: 1.34.0
    Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
    Date: 2019-05-15T21:55:35.507Z
    Electron: 3.1.8
    Chrome: 66.0.3359.181
    Node.js: 10.2.0
    V8: 6.6.346.32
    OS: Linux x64 4.15.0-50-generic

Extension version 2.11.0

I have the preview open, then I type things into the plantuml file I'm editing. It seems like a new Java process is launched for each character I enter. The CPU load goes to 100% and in top I can see an uncountable number of java processes.

**Comment by qjebbs** [comment]
@rspielmann See if v2.11.1 helps to your issue.

**Comment by rspielmann** [comment]
@qjebbs I've tried v2.11.1 and it works a lot better in this regard. Thanks for the fix and for the notification!

**Comment by maxtar** [comment]
Version 2.11.2 has the same problem!
Please reopen issue.
