### ISSUE TITLE
It's very slow to get preview updated

### ISSUE THREAD

**Issue by yaphper** [qjebbs/vscode-plantuml#172]
When i update my .wsd file, I have to wait about 10 seconds to see the preview.
Here is my system info:
macOS 10.14
VSCode 1.29.1
JRE: build 1.8.0_191-b12

**Comment by qjebbs** [comment]
well, it's not a problem of this project. here is something you may want to see:

https://github.com/qjebbs/vscode-plantuml#use-plantuml-server-as-render
