### ISSUE TITLE
Using preprocessor breaks autocomplete

### ISSUE THREAD

**Issue by FlorianKempenich** [qjebbs/vscode-plantuml#174]
Hi,

First of all, thanks for the amazing job. This plugin, especially in combination with the PlantUml server is incredible!

I have a problem however when using the preprocessor, it seems to break autocompletion of local variables.

---

## Problem:
* Using `!define VARIABLE VALUE` to set variable **breaks autocompletion**
* ### Showcase
  * Before using `!define`
![before_define](https://user-images.githubusercontent.com/10831649/49012707-25f24400-f172-11e8-83d8-0793cea08276.png)
  * After using `!define` --> **`User` is no more autocompleted**
![after_define](https://user-images.githubusercontent.com/10831649/49012712-2a1e6180-f172-11e8-875a-037d9def2dfb.png)

## Expected Behavior:
* `!define VAR VAL` should have no impact on autocompletion.
* _Edge case:_ It's totally fine (to me) if VAR or VAL are not completed properly.

**Comment by qjebbs** [comment]
Thanks for feedback, I need to investigate.

**Comment by FlorianKempenich** [comment]
You're welcome 🙂 I'd give you a hand but after peeking in the source I realized I just don't have the time to familiarize myself with how VSCode extensions are built.
On the flipside, I'm working on a basic translation of the extensions to French, I'll open a PR once I'm done ;)

**Comment by zimtkeks** [comment]
Thanks for reporting. I noticed the lack of auto-completion as well and was wondering about the cause.
Thanks @qjebbs for taking a look! And you work at large :-) 👍

**Comment by qjebbs** [comment]
Please update to latest, the issue should've solved, coming with more auto completion support.

@FlorianKempenich Looking forward your translation, thanks.

**Comment by FlorianKempenich** [comment]
Hey :)
I've been slightly overbooked these last couple of days. I'll check that around mid-next week. The translation is almost done but will as well be stuck until then.
Thanks for the amazing work!

**Comment by qjebbs** [comment]
@FlorianKempenich I totally understand. Thanks again.

**Comment by FlorianKempenich** [comment]
@qjebbs The last 2 months have been crazy but I finally found some time to complete my work on the translation 😃 
It's here #193 😉
