### ISSUE TITLE
Markdown preview broken

### ISSUE THREAD

**Issue by Endyl** [qjebbs/vscode-plantuml#177]
In versions

```
Version: 1.30.0-insider
Commit: d3bb20c3fd1f23c369b80dca2ed25d54efd664e2
Date: 2018-11-27T08:21:55.919Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-38-generic
```

and

```
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

neither of the markdown preview features are working.

A fenced code block with tag `plantuml` or `plantumlcode` just shows up as uncolored code block in the preview (my impression is that the former should show a rendered diagram while the latter should show syntax highlighted code (as with other languages)). In the markdown file itself a fenced code block with tag `plantuml` is syntax highlighted properly, while a code block with tag `plantumlcode` is uncolored.

Did I configure something improperly that can cause this, or did something change in vscode that makes these features not work anymore?

Thanks for your help!

ps: I use a local plantuml jar (latest version downloaded from plantuml.com) for rendering diagrams, and the Alt-D preview feature works fine.

**Comment by qjebbs** [comment]
Please make sure if any conflicts with other markdown plugin. Work good here with 1.29.1:

    ```plantuml
    @startuml
    Alice -> Bob : hello
    Alice <- Bob : hi
    @enduml
    ```

Source:

![image](https://user-images.githubusercontent.com/16953333/49555433-cf87c100-f93a-11e8-8de6-6b166f004fae.png)

Rendered:

![image](https://user-images.githubusercontent.com/16953333/49555444-d7dffc00-f93a-11e8-8d37-86dd2c91d010.png)

**Comment by Endyl** [comment]
In 1.29.1 I have no other extensions enabled. See the screenshot below of the situation:

![plantuml](https://user-images.githubusercontent.com/1752273/49573619-c26cd100-f93e-11e8-9c8e-1634445ec029.png)

**Comment by Endyl** [comment]
I have set `plantuml.render` to `PlantUMLServer` (`plantuml.server` is 'https://www.plantuml.com/plantuml'), but the markdown preview still does not work. The standalone diagram preview is also broken with `PlantUMLServer`.

**Comment by qjebbs** [comment]
Sure it doesn't, I just want you to verify the error msg while using server.😃

**Comment by qjebbs** [comment]
You can temporary change the server to 'http://www.plantuml.com/plantuml' to bypass the problem, before the workaround fix is published.

**Comment by Endyl** [comment]
The standalone diagram preview works with 'http://www.plantuml.com/plantuml', but the markdown preview is still broken. So the situation is the same as with local rendering.

Can the markdown preview work with local rendering? I'd rather not send my diagrams over the wire, or set up a JEE server just for diagram rendering.

**Comment by qjebbs** [comment]
Please try the latest to see what happens

**Comment by Endyl** [comment]
Now the preview works, but it uses the plantuml server even if I set rendering to local. This is misleading and raises privacy concerns. If the preview does not work in local mode, the extension should disable preview in that mode. But it would be nicer, if the preview in local mode would use data URIs to render images (ie: use plantuml -pipe option to generate png data and convert that to data URLs).

**Comment by qjebbs** [comment]
Unfortunately, it's not possible, because markdown-it doesn't allow async functions. I'm considering disable markdown integration if user don't have their own server set: 
https://github.com/qjebbs/vscode-plantuml/issues/175
