### ISSUE TITLE
command 'plantuml.exportWorkspace' not found

### ISSUE THREAD

**Issue by dbarzdys** [qjebbs/vscode-plantuml#178]
I get this error when I try to export all diagrams:
"Command 'plantuml.exportWorkspace' not found"

I get the same with other commands except "plantuml.preview" which seems to work fine.

PlantUML extension version: 2.10.1
VSCode version: 1.29.1

**Comment by dbarzdys** [comment]
```
notificationsAlerts.ts:38 Error: command 'plantuml.exportWorkspace' not found
    at t._tryExecuteCommand (commandService.ts:55)
    at commandService.ts:48
    at <anonymous>
t.onDidNotificationChange @ notificationsAlerts.ts:38
(anonymous) @ notificationsAlerts.ts:26
e.fire @ event.ts:145
t.notify @ notifications.ts:113
t.error @ notificationService.ts:48
t.onError @ commandsHandler.ts:326
(anonymous) @ commandsHandler.ts:311
Promise rejected (async)
(anonymous) @ commandsHandler.ts:307
setTimeout (async)
t.runAction @ commandsHandler.ts:297
t.run @ commandsHandler.ts:281
e.run @ quickOpenModel.ts:587
t.elementSelected @ quickOpenWidget.ts:556
(anonymous) @ quickOpenWidget.ts:235
```

**Comment by dbarzdys** [comment]
This did work yesterday, but today I cannot not get it working. I tried reinstalling plantuml extension, upgraded vscode but it did not help.

**Comment by qjebbs** [comment]
Those msg doesn't help..can you try remove `~/.vscode/extensions/jebbs.plantuml*`, restart VSC, and re-install?

**Comment by dbarzdys** [comment]
Nope, does not help. I will try to install the older version of this extension and see if it helps.

**Comment by dbarzdys** [comment]
Update:
Installed 2.9.10 and it works fine. Seems like this issue only exists in new v2.10.0 release.

**Comment by rohel01** [comment]
Hello,

I witness exactly the same behavior on VSCode 1.29.1 with PlantUML 2.10.0

**Comment by qjebbs** [comment]
I think I've located the problem, the latest version should've fixed it.

**Comment by dbarzdys** [comment]
I upgraded to the latest version and I can confirm that all commands are working again.
Thanks for fixing this issue  :+1:

**Comment by qjebbs** [comment]
Good to hear, sorry for the inconvenience.
