### ISSUE TITLE
Errors when use https server render

### ISSUE THREAD

**Issue by qjebbs** [qjebbs/vscode-plantuml#179]
Since the commit 8d764db301ea12248a953726783cf214cac076b4 (Use https instead of http for default online render server url), it's considered to be reasonable move, but problems surfacing.

The issue is: https://github.com/request/request/issues/2505

As a result, in some platform (Like win7, not all platforms):

- The preview reports `Error: unable to verify the first certificate` (can bypass via `strictSSL: false`)
- The markdown integration reports `Failed to load resource: net::ERR_INSECURE_RESPONSE` (cannot bypass).

Since I don't see a solid method to solve it, I'm considering roll back to HTTP server by default. Users can change to HTTPS, if they don't encounter these problems.

**Comment by ChrisMuc** [comment]
Wouldn't it be better to just disable strictSSL, than using http by default?
HTTPS without strict certificate validation does not prevent man-in-the-middle attacks; but these kind of attacks at least require some effort. Using plain HTTP, everyone can read the traffic.

**Comment by qjebbs** [comment]
But we don't have solution for markdown integartion, if https.

**Comment by qjebbs** [comment]
I'll keep the `https` as server default, if anyone had encountered this issue, please consider switch to `http` via user setting.
