### ISSUE TITLE
Zoom in and out the generated diagram

### ISSUE THREAD

**Issue by ignacy130** [qjebbs/vscode-plantuml#18]
I read [the comment](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml), but I think that it would be a great feature as well.

1. To check whether the diagram is correct without generating it.
2. I use VS Code as viewer of the diagrams and don't want to generate them, just browse via the editor and generator.

Maybe there is a way? :) Unfortunately, I use VS Code for a few days now and cannot even suggest another extension where something similar works.

**Comment by qjebbs** [comment]
To tell you the truth, I've been tried, but it does not work. If anyone has any idea will be appreciated.

**Comment by kiebor** [comment]
The preview pane is just an html layout, right? Can the zoom controls not be implemented via html + css? Or perhaps integrate some library like this one:
https://github.com/timmywil/jquery.panzoom

**Comment by qjebbs** [comment]
jquery.panzoom need jquery, which is JavaScript, which is disabled in preview. I don't know a way only via html+css, and I'm not good at it. If anyone does, and he / she wrote me a page, will be appreciated.

https://github.com/qjebbs/vscode-plantuml/blob/develop/templates/preview.html

**Comment by qjebbs** [comment]
But even zoom is implemented, it comes with other problems, how about preview page reloaded after you zoomed in? Zoom status will be lost...
The only way to update preview is reload the page, and I cannot replace part of it.

**Comment by kiebor** [comment]
I tried this html + css solution: https://codepen.io/Remedy/pen/ZYJrpp 
It does a zoom on hover as expected, but I think to achieve proper zoom and pan type control, you'll need events -- I can't see a non-javascript solution in preview tbh.

**Comment by kiebor** [comment]
perhaps a new pane is needed instead. When preview is loaded a smaller window docked beneath it can track cursor by X-Y in preview and display the blown-up portion?

**Comment by qjebbs** [comment]
Hmm...I don't know a pane provided by vscode can do it. Or do you mean by interact with an app outside vscode, I think it's too ugly to use.

**Comment by kiebor** [comment]
You don't want to introduce external apps and dependencies... messy. The cleanest solution would be the jquery/js route. With that disabled in the html preview, this becomes a nice to have feature which may or may not realistically be realized.

I'll look at putting together some pure css options so you can determine if it's a viable alternative.

**Comment by qjebbs** [comment]
Thanks, looking forward your results.

**Comment by kiebor** [comment]
html + css only is not going to do the job. Essentially all we can do with just those 2 is 'grow' the image within a static frame, or shift and align it respectively with an outer div.  

Because js is not possible, what we actually need instead is a parent set of controls that apply zoom and scrolling to the html preview as if it were a image loaded into a container. If the previewed content is an html page, the outer pane must be some kind of browser control' -- when you change the splitter position, the content auto-fits to pane, when you move the preview to its own tab, the content resizes to fit the entire pane; this all indicates to me there must be a way to plumb into the zoom level of the 'browser'.

That's what we need to investigate, I think.

**Comment by qjebbs** [comment]
So far as I know, there is no way to plumb into the 'browser'. We can only feed the 'browser' with HTML page to show the preview, and feed it with new page to update preview. Not to mention how to zoom, how can we keep zoom status between page refreshing?

So I think this is an impossible mission. I will keep this issue for more couple of days, and then give up and close if no more ideas given.
