### ISSUE TITLE
Extract plantuml code into another package

### ISSUE THREAD

**Issue by chulkilee** [qjebbs/vscode-plantuml#180]
Found that vscode-plantuml has own plantuml related code, such as detecting the type of diagram, generating uml code, etc.

It would be great if we have standalone library to handle plantuml text, since it allows other libraries can rely on this, without rebuilding it.

**Comment by qjebbs** [comment]
Thanks for the suggestion, but the detecting code is not reliable enough, and only applicable to restricted use cases in my extension. If anyone think this detecting code useful, just take it 😀
