### ISSUE TITLE
Mix different diagrams  

### ISSUE THREAD

**Issue by kasra0** [qjebbs/vscode-plantuml#182]
Thanks a LOT , Great job !!

I have a questions though

 Is it possible to mix into one @startuml ... @enduml scope syntaxes from different diagrams ?
for example if i do something like  : 
	**@startuml
	(uc1)--> (uc2)
	class c 
	@enduml**
this is not currently working ( my plugin version is  2.10.1, vscode version 1.29.1 )

if not, is it a plantUML limitation ? 
 
thanks again for your work!
Kasra

**Comment by qjebbs** [comment]
You're right, it a plantUML limitation.

**Comment by kasra0** [comment]
thanks for your answer.
