### ISSUE TITLE
after using newpage, Class diagram can not refresh, even by Alt +D

### ISSUE THREAD

**Issue by jwbecalm** [qjebbs/vscode-plantuml#184]
there's no error hint, I must restart the visual studio code after I add some new graph

**Comment by qjebbs** [comment]
Cannot reproduce, can you give more detail?

**Comment by KaiMildner** [comment]
Hi,

same here. The preview doesn't update after a while. Also when i close the preview and try to reopen it, nothing happens. I have to restart VS Code.

Some example:

`@startuml Class 1
title class 1
skinparam classAttributeIconSize 0
class Test {
    - {field} var
    + {Method} getVar()
    + {Method} setVar()
}
newpage
title class 2
class Test2 {
    - {field} var2
    + {Method} getVar2()
    + {Method} setVar2(value)
}
newpage
title relations
Test2 <|-- Test
@enduml`

When i add a new page nothing will happen and i have to restart. There is no entry in errors, deabug or output.

Graphviz is 2.38
Java is 1.8.0_191

**Comment by lsouchet** [comment]
I encounter the same issue using version 2.13.13 on Ubuntu 18.04  in VS code 1.49.0.
I use this sample code:
`@startuml
A->B: Hello
newpage
B->C: Hello
newpage
C->A: Hello
A->A: back
@endum`

When I open VS code, and press Alt+D, the preview is generated once, after that, when I update the file, I cannot update the preview, nor by using Alt+D or Ctrl+Maj+P>"PlantUML: Preview current diagram".
I need to restart VS code to have it working again.

Note that when using plantuml files without newpage commands I have no problem
