### ISSUE TITLE
Plantuml code as comment in any file extension can preview as plantuml

### ISSUE THREAD

**Issue by d0uub** [qjebbs/vscode-plantuml#187]
**it is feature request**
i always use plantuml to replace my code comment in program. is it possible to generate UML if code comment is plantuml code?
for example
```
//start
//:initialize;
  var a=1;
  var b=2;
  var c=3;
//  var d=4; <-- do not generate as plantuml if pattern is "//  " but not "//" (no space after //)
//:run program;
if (a==b) {
console.log(c)
}
//end
```
filter "^\/\/[^ ]" with regex to keep begin with // line
```
//start
//:initialize;
//:run program;
//end
```
finally, replace "//" at beginning to be complete plantuml
```
start
:initialize;
:run program;
end
```

of course, "//" is editable regex pattern would be nice

**Comment by qjebbs** [comment]
Try like this (JS for example):

```js
// @startuml
// :initialize;
// :run program;
// @enduml
function name(params) {
    // do somthing
}
```

**Comment by d0uub** [comment]
thanks jebbs
what if i want to write comment like this to explain exactly on each line?
https://www.dropbox.com/s/6znbirherofgrp0/code-comment.png?dl=0

**Comment by qjebbs** [comment]
Thanks for the information, `@append` is a brilliant solution!
