### ISSUE TITLE
bug: \u0008 cause preview blank

### ISSUE THREAD

**Issue by jiangjianbo** [qjebbs/vscode-plantuml#189]
I use macbook, and Chinese-Input-Method Sogou will insert a hidden char \u0008 before I type chinese, after I typed, the \u0008 will be removed from vscode. But when I type some chinese text then use backspace to delete them all, flag \u0008 will stay in editor buffer. then Alt-D preview will return blank image without any error message. I usually use Find \u0008 to high-light the char, and remove it by hand.

**Comment by qjebbs** [comment]
Same problem with https://github.com/qjebbs/vscode-plantuml/issues/125.

The extension only pipes source to `PlantUML.jar` and shows the result. In this case, `PlantUML.jar` doesn't handler special chars for `svg`. I think it's better `PlantUML` project solves this, than me.

I suggest you post an issue to http://forum.plantuml.net/
