### ISSUE TITLE
Diagram error when env variable JAVA_TOOL_OPTIONS is defined

### ISSUE THREAD

**Issue by apawelec** [qjebbs/vscode-plantuml#19]
When `JAVA_TOOL_OPTIONS` environment variable is defined plugins says that there is error in diagram.

Steps to reproduce:

1. (OS Windows 10)
2. Define `JAVA_TOOL_OPTIONS` environment variable 
(mine is `JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true`)
3. Try go generate preview for any diagram, ie:
  ```
  @startuml
  class Foo {
  }
  @enduml
  ```
4. The preview looks like this:

![diagram error](https://cloud.githubusercontent.com/assets/1340207/24810737/a77cc92c-1bc3-11e7-9b1f-f9355bbc51c7.JPG)

Same things happens for diagram exporting.

Steps to reproduce:
1. Try to export diagram to file.
2. Following error appear in Output tab:
```
Error found in diagram test@1-6
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
 ```

After unsetting this variable everything works fine.

**Comment by qjebbs** [comment]
Yes, I search the web, this is an error happens a lot in many environments. It seems like it's a problem with Java, simply type this command you will encounter this error too:
```
> java -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) Client VM (build 25.91-b14, mixed mode)
```
So this problem can not and should not solved by my plugin.

Fortunately, this error won't stop you from export or preview in latest plugin version.

**Comment by karthil** [comment]
It seems the error does prevent the tool from showing anything but the first page of a multi-page document.  Do you think this is something that could be addressed?  Thanks!

**Comment by happycoder97** [comment]
It is an informative message, which the plugin should ignore, right?

**Comment by qjebbs** [comment]
@happycoder97 OK, I see your situation.

I will filter out `JAVA_TOOL_OPTIONS` errors, but I have to say, personally I think it's really not a standard practice, for java reporting this.
