### ISSUE TITLE
Suggestion list problem when using `note`

### ISSUE THREAD

**Issue by wduminy** [qjebbs/vscode-plantuml#194]
The `note` keyword seems to break the suggestion list. I noticed this problem on version 2.10.3.

To reproduce, use this snippet:

```
@startuml class_diagram 

note "add some note" as note123

package package1 {
	class Hello1
}

He
@enduml
```

Now go to the last line and type `l`.  You would expect to see the word `Hello1` in the suggestion list, but it is not there.

If you remove the `note` line and do the same thing, `Hello1` is displayed in the suggestion list.

```
@startuml class_diagram 

package package1 {
	class Hello1
}

He
@enduml
```

By the way: thank you for developing this excellent extension!

**Comment by qjebbs** [comment]
My intention is to keep the note texts out from the suggestion, but `plantuml` syntax is so flexible that with simple rules, I cannot exactly tell the kind of a code block. 

So it may be better, to let note texts appears in the the suggestion list.
