### ISSUE TITLE
Ability to scroll in the image

### ISSUE THREAD

**Issue by renedescartes** [qjebbs/vscode-plantuml#195]
I am using 2.10.3 and I believe I see the same issue as https://github.com/qjebbs/vscode-plantuml/issues/117 when an image preview is rendered in VSCode the diagram is too small. I can only click on Zoom in/out however once zoomed in I cannot scroll the image to see the right portion. I can use the mouse scroll to move up/down but I cannot move left to right.

**Comment by qjebbs** [comment]
Use right button drag please, just like some design software does.

More info:

- Zoom operations (since version 2.7.0): 
    - Zoom to select area
    - Pinch to zoom (TouchPad)
    - Click to zoom in, alt + click to zoom out
    - Ctrl + mouse scroll to zoom in/out
    - Middle mouse button click to toggle zoom
    - Zoom in / zoom out / toggle buttons of the controls bar.
- Pan operations (since version 2.7.0):
    - Right mouse button drag
    - Two-finger move to pan (TouchPad)
    - Mouse scroll
- Snap to border (since v2.8.0):
    - Scroll to most bottom/right/top/left, preview will snap to that border. 
    > e.g. Snap to Bottom is useful while writing long activity diagrams, which helps you keep focus in the latest part in the bottom.

**Comment by renedescartes** [comment]
I see! This looks good. I did not know about the Pan operations which is precisely what I want. Perhaps in the preview of VS Code window you can add a "?" icon which when you click opens up this information !

Thank you again and this issue can be closed (but a ? help icon will be very useful)
