### ISSUE TITLE
Support for specifying filename of exported diagram

### ISSUE THREAD

**Issue by dicastro** [qjebbs/vscode-plantuml#2]
It would be nice to be able to specify filename of exported diagram

```
@startuml diagram1
title Diagram 1
@enduml
```
File extension should be picked while exporting or from configuration

**Comment by qjebbs** [comment]
Good idea, this could be done in the next release. For now, the plugin only uses title string as filename.

**Comment by qjebbs** [comment]
It supports your proposal now, and it has higher priority than naming by title:
```
@startuml diagram_name
sudoku
@enduml
```

**Comment by dicastro** [comment]
I've just upgraded the plugin and tried it.

It works like a charm.

Thank you for developping and publishing so fast!

**Comment by rcdailey** [comment]
Sorry to dig up an old issue, but it's relevant so I thought I'd ask here. Is there a mechanism to automatically use the name of the `*.plantuml` file instead of a custom name (as was supported here) or title?

**Comment by marsh-circle** [comment]
+1 for this, it's hard with spaces on filenames, and just as hard with _'s in titles!
I might be missing something that would help here, so apologies if that's the case, but I can't seem to see how to save with the same filename as the source.

**Comment by qjebbs** [comment]
If the diagram not named, and it's the first of the file, it's named with the filename
