### ISSUE TITLE
Preview gets stuck when used New Page in VSCode

### ISSUE THREAD

**Issue by NandhanThiravia** [qjebbs/vscode-plantuml#201]
I am using "newpage" attribute to create multiple pages to demonstrate multiple scenarios. The moment I start adding pages to the PUML code the Preview stops refreshing and the only recovery is to close the VSCode App and re-open it.

Can this be fixed ?

**Comment by useltmann** [comment]
There seems to be an issue with `newpage` overall. When exporting a diagram with multiple pages it exports only the first page - but multiple times.

**Comment by qjebbs** [comment]
@NandhanThiravia Can you provide the source, help me reproduce it?

@useltmann Server render doesn't support multi-page diagrams: https://github.com/plantuml/plantuml-server/issues/7#issuecomment-348100354

**Comment by qjebbs** [comment]
close due to inactivity.
