### ISSUE TITLE
Support for Mindmaps

### ISSUE THREAD

**Issue by flxo** [qjebbs/vscode-plantuml#202]
Recently `plantuml` added support for [Mindmaps](http://plantuml.com/mindmap-diagram). Seems like the plugins previewer doesn't support that.  Mine complains about a missing `@startuml` tag.

I'm using the extension version `2.10.7`.
Not sure about the versioning: The GH release page ends at `2.9.7`. The changelog says `2.10.7` and the committed changelog says `2.10.6` - so I think I'm on the latest.

**Comment by kyleboyle** [comment]
I think this is basically a request for the newest plantuml jar build to be included in the plugin. for now you can download the jar and set your "plantuml.jar" : ".." user setting to use the newer version explicitly.

**Comment by flxo** [comment]
Ok. Thanks! I assumed the plugin uses my system `plantuml` installation. Sorry for the noise.
