### ISSUE TITLE
No dot executable found on specific file

### ISSUE THREAD

**Issue by tekord** [qjebbs/vscode-plantuml#203]
I have the following code:
```
@startuml

object firstObject
object "My Second Object" as o2

@enduml

```
I have blank line at the end of the code. If text cursor is set outside of `enduml` then I got 'No valid diagram found here`. I see issue https://github.com/qjebbs/vscode-plantuml/issues/62, it closed, but NOT fixed in current version 2.10.7.

Further, if I set text cursor inside startuml/enduml then I got `No dot executable found`. But other UML files work fine, dot executable does exist. Only this specific file unable to find dot executable.

**Comment by tekord** [comment]
I fixed this by downloading fresh plantuml.jar and setup path to it in plugin's settings.

**Comment by qjebbs** [comment]
#62 is about don't display the alert when you already have a preview result, and the cursor temporarily move to outside. But if you place the cursor outside of a valid diagram, and explicitly ask me to show the preview at current cursor (by pressing Alt+D), of course I tell you `No valid diagram found here`.
