### ISSUE TITLE
Try calling dot from path instead of requiring manual config

### ISSUE THREAD

**Issue by LunarLanding** [qjebbs/vscode-plantuml#205]
What the title says. This would be an usability improvement. In my specific case I installed dot via anaconda, and that places a dot.bat on path linking to the actual executable. However that is not sufficient for vscode-plantuml to use it. I'm using the config option mentioned in https://github.com/qjebbs/vscode-plantuml/issues/126 and others for now.

**Comment by qjebbs** [comment]
I agree, but this is should be done by the `plantuml.jar`, not the extension. I cannot control the behavior of the `plantuml.jar`, expect I can told it by `-DGRAPHVIZ_DOT`.😅

**Comment by LunarLanding** [comment]
Thanks, I'll take it up with plantuml.jar .
