### ISSUE TITLE
Support @startmindmap tag

### ISSUE THREAD

**Issue by meldavis** [qjebbs/vscode-plantuml#206]
From the command-line, plantuml can generate mindmaps from files using the `@startmindmap` tag.  However, the plugin reports `No @startuml found`.

See: [plantuml mindmaps](http://plantuml.com/mindmap-diagram)

**Comment by meldavis** [comment]
I am using VSCode Version 1.32.3 and the latest PlantUML V1.2019.3.

I was able to fix the problem by building `vscode-plantuml`

- with all dependencies updated to their latest version,  and 
- changing `src/plantuml/common.ts` so that the `nls.config` and `localize` statements worked with VSCode's updated `nls` library. 

For anyone else having problems, I changed the last two lines of https://github.com/qjebbs/vscode-plantuml/blob/046afb813c6598605a515775454993e58b04fe1a/src/plantuml/common.ts#L11-L12 to

```typescript
nls.config(<nls.Options>{ locale: vscode.env.language, messageFormat: nls.MessageFormat.file});
export var localize:any = nls.loadMessageBundle( join(extensionPath, "langs", "lang.json"));
```

**Comment by qjebbs** [comment]
It's not about the code, but the jar. See #202. I'll update integrated jar in next release.
