### ISSUE TITLE
includesearch diagramsRoot does not work correct

### ISSUE THREAD

**Issue by anotherandi** [qjebbs/vscode-plantuml#209]
Inclusion from included files does not work correct. Error message:  "Cannot include [filename]"

When I include a file that contains macros an the macro include yet another file.
It looks like the includepath only works correct for the currently opened/edited plantuml file but not for included files. When I use !include in an included file I still have to use relative paths.

BTW: Generating the image works fine when I use the plantuml.jar and set the include.path to the same folder as diagramsRoot.

Having a common base directory for inclusion I basically consider a good idea. But I wood prefer to specify an include folder and still be able to use relative paths in a plantuml file. Similar to the way C/C++ behaves. First try in the folder of the current file and then proceed with the include paths.

**Comment by qjebbs** [comment]
Thanks for the report, and the solution (`-Dplantuml.include.path`), the fix goes with next release.

About the `C/C++ behaves`, I'm afraid it's hard to do, because the `plantuml.jar` is an outside dependency, to this extension, that I cannot control it finely.
