### ISSUE TITLE
'vscode.previewHtml' command deprecated

### ISSUE THREAD

**Issue by JirkaDellOro** [qjebbs/vscode-plantuml#214]
Extension 'jkeys089.plantuml' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.

**Comment by qjebbs** [comment]
It’s a fork and published by jkeys089, please try to contact him, or switch to the release of this repo

**Comment by JirkaDellOro** [comment]
Already did the matter, sorry for the irritation
