### ISSUE TITLE
Configuring include path

### ISSUE THREAD

**Issue by anotherandi** [qjebbs/vscode-plantuml#221]
Hallo,

I did not find any possibility to configure an include path.
It is only possible to configure files and folders that are automatically included.
With the implementation of #209 it is not possible to configure the include path with "plantuml.commandArgs": [
        "-Dplantuml.include.path=\"path1:path2\""
    ], 
anymore.

I suggest to set the include path (using -Dplantuml.include.path) in the follwing order:
* the path of the converted plantuml
* the diagrams root
* the path of included files (I think this will no be possible with plantuml and can be ommited)
* a new setting: plantuml.includepaths (support relative paths to the workspace folder and resolving variables such as ~ for home dir.

The setting plantuml.includeSearch may becomes obsolete with this behavior.

BR Andreas

------------
Thank for your great work. This extension is awesome.

**Comment by qjebbs** [comment]
Thanks for your brilliant idea!  Busy these months, do you mind to start a PR?

**Comment by anotherandi** [comment]
I have absolutely no experience in developing vscode extension nor java script at all.
Otherwise I would be glad to contribute. May I have a look if I can do it with some copy and paste and adapting.

**Comment by anotherandi** [comment]
I think I've implemented the main parts. But I'm not able to build run the extension.
I get the following output:
src/commands/common.ts(1,38): error TS2307: Cannot find module 'vscode'.
src/extension.ts(4,25): error TS2307: Cannot find module 'vscode'.
src/extension.ts(5,22): error TS2307: Cannot find module 'vscode-nls'.
src/markdown-it-plantuml/render.ts(1,28): error TS2307: Cannot find module 'markdown-it'.
src/markdown-it-plantuml/rule.ts(1,28): error TS2307: Cannot find module 'markdown-it'.

How can I install all required dependencies?

**Comment by anotherandi** [comment]
Please merge pull request

**Comment by anotherandi** [comment]
Thank you for merging.
