### ISSUE TITLE
keywords can't auto complete

### ISSUE THREAD

**Issue by ycjcl868** [qjebbs/vscode-plantuml#222]
like I type `title` 

![image](https://user-images.githubusercontent.com/13595509/57008078-2bbbec00-6c20-11e9-8f11-7e84c9465711.png)

**Comment by qjebbs** [comment]
![image](https://user-images.githubusercontent.com/16953333/57008202-07acda80-6c21-11e9-8b09-c8623c42fe80.png)
Cannot reproduce here.

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/57008549-8c005d00-6c23-11e9-8e90-492150ff0b29.png)

ok, thanks. It's attributed to my language setting, it's `diagram` not `plantuml` type.
