### ISSUE TITLE
Using plantuml server as renderer

### ISSUE THREAD

**Issue by Kevintjeb** [qjebbs/vscode-plantuml#224]
Hello,

I wanted to use plantuml-server as renderer and therefore I followed the instructions in the readme of this repository after starting the plantuml-server docker container.

I came across the following issue:

When using this configuration, the server can't be used:
```
"plantuml.server": "http://<ip | localhost>:8080/plantuml",
"plantuml.render": "PlantUMLServer"
```

The example URL is (I'm guessing here) not the default anymore, as I only received errors while trying to render diagrams. After changing the URL to : 
`"plantuml.server": "http://<ip | localhost>:8080/" `
 It worked.

I looked at the instructions from the plantuml-server repository, but they also say that `/plantuml` is the correct route. However, after starting their docker container this route gives a 404 and the baseroute '/' shows you their UI.

**Comment by qjebbs** [comment]
Seem that they had changed the route of the docker release. Thanks for feedback, I'll update the readme.
