### ISSUE TITLE
Latest include failure

### ISSUE THREAD

**Issue by Kf-GaryNewport** [qjebbs/vscode-plantuml#227]
Hi,
Just updated with the latest version and my diagrams have suddenly developed errors.
I've included an example below that includes some external images from Ricardo Niepel.

@startuml Hello World
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/1-0/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Databases/all.puml
!includeurl AzurePuml/Compute/AzureFunction.puml

actor "Person" as personAlias
AzureFunction(functionAlias, "Label", "Technology", "Optional Description")
AzureCosmosDb(cosmosDbAlias, "Label", "Technology", "Optional Description")

personAlias --> functionAlias
functionAlias --> cosmosDbAlias
  
@enduml

**Comment by qjebbs** [comment]
But I tested it good..
![image](https://user-images.githubusercontent.com/16953333/57664630-93fccb80-762b-11e9-8986-6e5a58dabd1b.png)

**Comment by adrianvlupu** [comment]
Hi, the PlantUML version changed to **1.2019.6**. This breaks `!define` and `!definelong`. They are still supported (for now) but when calling stuff like `LAYOUT_WITH_LEGEND` you have to use `LAYOUT_WITH_LEGEND()` just like a method call.

So in case you are using the PlantUML server as render, diagrams are going to break.
