### ISSUE TITLE
PlantUML version 1.2019.6

### ISSUE THREAD

**Issue by adrianvlupu** [qjebbs/vscode-plantuml#230]
Hi,

PlantUML recently switched to V1.2019.6 adding some breaking changes to !define and !definelong. You can still use them but when calling you have to add () method call (http://plantuml.com/preprocessing)

Considering they updated their server to use the new version there are going to be inconsistencies between diagrams generated online and ones generated locally.

Maybe you could update the internal plantuml.jar file to the latest version

**Comment by qjebbs** [comment]
Thanks, please update.
