### ISSUE TITLE
Please include latest plantuml.jar because the current one has a bug

### ISSUE THREAD

**Issue by rogierschouten** [qjebbs/vscode-plantuml#231]
The plantuml.jar delivered with the plugin gives a syntax error on my .puml files. This syntax error is removed when I use the latest plantuml.jar file, version 1.2019.6.  So maybe it's time to upgrade to the latest plantuml in the plugin too?

**Comment by adrianvlupu** [comment]
Update the extension from VSCode. It now uses 1.2019.6

**Comment by rogierschouten** [comment]
It doesn't. I have v2.11.1  and it has the syntax error. Pointing explicitly to downloaded 1.2019.6 jar fixes the issue. Are you sure the included jar file isn't mixed up?

**Comment by rogierschouten** [comment]
My bad.  The switch from 1.2019.5 to 1.2019.6 INTRODUCES the bug. I'll file an issue with PlantUML
