### ISSUE TITLE
style render problem

### ISSUE THREAD

**Issue by Using1174** [qjebbs/vscode-plantuml#233]
i got this.
![image](https://user-images.githubusercontent.com/16488261/58948632-1efd5b80-87bd-11e9-8a06-cf85a1d3cdb9.png)
 with my code:
```
@startuml
!include /path/to/jebbs.plantuml-2.11.0/includes/styles/blue.wsd

start
if (cond?) then (val1)
    :do something 1;
else (val2)
    :do something 2;
endif
end
@enduml
```
but the example color shows like this:
![image](https://user-images.githubusercontent.com/16488261/58949015-02155800-87be-11e9-9482-3792bf56cda4.png)

it's that right?

**Comment by Using1174** [comment]
i think there is a new skinparam called "DiamondBackgroundColor" can fix it.
it can be used as:
```
skinparam {
    Activity {
        DiamondBackgroundColor AliceBlue
    }
}
```
or 
```
   skinparam  ActivityDiamondBackgroundColor AliceBlue
```
https://plantuml-documentation.readthedocs.io/en/latest/diagrams/activity.html

**Comment by qjebbs** [comment]
#232 will solve this issue, until next release.
