### ISSUE TITLE
vizualization not working

### ISSUE THREAD

**Issue by marcusbesjes** [qjebbs/vscode-plantuml#234]
When generating the preview I see this error message:

![image](https://user-images.githubusercontent.com/3897729/59088942-39445000-8909-11e9-8ffd-dda8648d4440.png)

I have installed graphviz, the dot executable seemt to be where it should be (see lower part) the error message also seems to say everything is in order as far as I can tell (Installation seems OK, File generation OK) it can even find the graphviz version.. but it doesn't work.

**Comment by qjebbs** [comment]
I don't understand what your situation is...What do you get trying this:

```
@startuml
a->b:c
@enduml
```

**Comment by marcusbesjes** [comment]
lol this is the test working.. previewing real puml files works now

**Comment by marcusbesjes** [comment]
I started from an actual puml file not working, then debugging with this testdot puml.. when all was fixed, I mistakenly expected a full blown diagram to pop up but this test of course only produces test output.. I mistook it for error output :P

**Comment by qjebbs** [comment]
See..😅
