### ISSUE TITLE
preview window steals focus from editing document

### ISSUE THREAD

**Issue by marcusbesjes** [qjebbs/vscode-plantuml#235]
When I'm editing a .puml file and have the preview window next to it, every time the preview refreshes, the focus is stolen away to the preview window.

This means my carrot is gone and I have to click back into the .puml file to continue editing it, this makes it impossible to work while having the preview window open, which is the best part of having it!

**Comment by marcusbesjes** [comment]
my fix is now to download puml.jar and run the GUI next to my editor: http://plantuml.com/gui

**Comment by qjebbs** [comment]
Cannot reproduce. You don't have to press `alt D` everytime, the preview will refresh when you document change.

**Comment by Mark90** [comment]
Make sure you're running the latest version of VSCode.

Being on MacOSX, I had both VSCode 1.24 installed from a manual download and 1.42 from brew cask. With the former I had the focus-stealing issue, with the latter I don't.

**Comment by marcusbesjes** [comment]
I stopped using plantuml a while ago, recently installed it again and the issue is gone 👍
