### ISSUE TITLE
Use java.home setting instead of a specific one

### ISSUE THREAD

**Issue by KuSh** [qjebbs/vscode-plantuml#236]
Hi,

The Language support for Java extension already define and use the generic java.home setting to configure the location of the JDK / JRE, whereas your extension use a specific plantuml.java one.
It could be great to have it configured once and used by everything instead of multiplying the same setting over and over.

You could let plantuml.java as a fallbacl to be backward compatible. (So the order of search would be java.home > plantuml.java > JDK_HOME > JAVA_HOME)

ref: https://marketplace.visualstudio.com/items?itemName=redhat.java#user-content-setting-the-jdk

related to #72 

Thanks for your work,
Regards,
Nicolas

**Comment by qjebbs** [comment]
`java.home` is not a native setting item of VSCode, but contributed by `redhat.java`, you can not assume it always exists.

Speaking of ENV support, I don't familliar with JDK / JAVA installation paths, PRs are welcome.
