### ISSUE TITLE
Export diagram to local folder on Win 10

### ISSUE THREAD

**Issue by KueWW** [qjebbs/vscode-plantuml#237]
Hi there,

I'm using Visual-Studio-Code 1.35.0 with this extension in Version 2.11.1 on Win 10 (1809).
I'ld like to export the diagrams into a subfolder _out_ without naming a folder like the diagram.
I've organized my diagrams as a subfiolder of a main project called _diagrams_.
After the export of the diagrams to PNG I expect that they're exported to 
`project/out/diagrams/diagram-name.png`.
But it's exported dot the folder
`project/diagrams/diagram-name.png`.

Using VScode on debian with the same settings it works well.

Can you give halep?

Thanks in advance.

**Comment by qjebbs** [comment]
See https://github.com/qjebbs/vscode-plantuml#notice-2

**Comment by KueWW** [comment]
Hi,

I'm very sorry. I read that and I did like this. But it doesn't work. That's why I wrote this issue.
Maybe I do not understand and I'm too blind to see.
I've set the _rootDirectory_ to `./diagrams` and the _exportOutDir_ to `./out` and I tried to 
set the _rootDirectory_ to `diagrams` and the _exportOutDir_ to `out`.
It still exports to _rootDirectory_. Is there something I have to pay attention of? E.g. Spelling or something else...
Are there conflicts with other plugins?
Your plugin is the only one installed to handle plantUML diagrams.

Thanks in advance,

**Comment by KueWW** [comment]
Hi,

I've checked `settings.json` and I found that `exportOutDir` was missing by default even though the setiing was made in th UI.
So I edited the  `exportOutDir` in `settings.json` manually. 
But it still exports to 'rootDirectory'

Here is my `settings.json`:
```
{
    "workbench.startupEditor": "newUntitledFile",
    "latex-workshop.intellisense.package.enabled": true,
    "latex-workshop.intellisense.unimathsymbols.enabled": true,
    "latex-workshop.latex.recipe.default": "lastUsed",
    "latex-workshop.view.pdf.external.synctex": {
        "command": "C:/Program Files/SumatraPDF/SumatraPDF.exe",
        "args": [
            "-forward-search",
            "%TEX%",
        "%LINE%",
        "-reuse-instance",
        "-inverse-search",
            "code \"C:\\Users\\<user>\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\cli.js\" -r -g \"%f:%l\"",
        "%PDF%",
        ]
    },
    "latex-workshop.view.pdf.viewer": "browser",
    "plantuml.exportSubFolder": false,
    "plantuml.exportFormat": "png",
    "plantuml.diagramsRoot": "diag",
    "plantuml.exportOutDir": "out"
}
```

**Comment by qjebbs** [comment]
`plantuml.diagramsRoot `, `plantuml.exportOutDir ` and `plantuml.exportSubFolder ` works as expected here, how about your problem now, solved or not?

**Comment by KueWW** [comment]
Hi there,

I'm sorry but the problem is still existing.
![2019-07-01 08_33_45-sequence-chart-standard-doorcall-simplified plantuml - Visual Studio Code](https://user-images.githubusercontent.com/7642828/60415463-81d6ec80-9bdb-11e9-95f9-08d34adf0c73.png)
Here's my folder structure:
![2019-07-01 08_39_19-D__Dokumentationen_git_sks-System_system-abstract](https://user-images.githubusercontent.com/7642828/60415697-25c09800-9bdc-11e9-8d2b-57ce2563edab.png)

**Comment by qjebbs** [comment]
Do you open the single file? Those settings are only works for workspace files. If open as a single file, it always export files along side the source file.

**Comment by KueWW** [comment]
That works!
When I save the folder within a workspace it works as expected.
I'va no idea why I didn't get that.
Thanks for your support.
