### ISSUE TITLE
Allow inserting a string behind @plantuml / regexp

### ISSUE THREAD

**Issue by cmorty** [qjebbs/vscode-plantuml#238]
Including only works locally (as far as I understood). It's also not uncommen to use different styles for rendering, especially when using MD across platforms (VS Code, github, gitlab, whatever). Thus hardcoding an `!includeurl` isn't always the best idea.
It would be nice to have a configuration option that includes a string right behind `plantuml`. This would allow to easily customize/adjust the renderings based on your locally selected skin used for markdown renderings. 
Alternatively, but more powerful and maybe easier to implement: Allow to configure a regexp that is executed before sending the data to the server. That way even URLs, etc could be rewritten based on your local requirements.

**Comment by qjebbs** [comment]
Basically, this is an extension helps you work with `plantuml.jar`, not adding specifications or extra behavior to it.
