### ISSUE TITLE
Letters 'i' and 'I' in the comments rendering like 'l'

### ISSUE THREAD

**Issue by alexzaitzev** [qjebbs/vscode-plantuml#240]
Found a strange bug: in some cases 'i' and 'I'(uppercase i) rendering as lowercase L.

```plantuml
@startuml
Bob -> Alice: Hi
@enduml
```
![image](https://user-images.githubusercontent.com/888475/59711386-57645700-920b-11e9-81eb-f978fb07c94a.png)

'i' redndering as 'i' only in combination with some other letters in the same word. Also length of the comment plays role.

```plantuml
@startuml
Bob -> Alice: iI
Bob -> Alice: iIl
Bob -> Alice: iIln
Bob -> Alice: iIlne
@enduml
```
![image](https://user-images.githubusercontent.com/888475/59712909-7d3f2b00-920e-11e9-9ba5-93f8c3259f3d.png)

Visual Studio Code - Insiders
Version: 1.36.0-insider (user setup)
Commit: 7f53e50cbf316dff94fbbe5406d8f352dac99a6b
Date: 2019-06-18T11:41:31.168Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by OwenAshton** [comment]
I've also noticed this issue.
It can be resolved by setting the fontStyle to Italics.
```
@startuml
skinparam ArrowFontStyle italic
Bob -> Alice: Hi
@enduml
```
![image](https://user-images.githubusercontent.com/28605335/60086509-14d2db00-9733-11e9-8bec-756cd3863c25.png)

**Comment by alexzaitzev** [comment]
@qjebbs issue was resolved?

**Comment by qjebbs** [comment]
it’s not the extension to blame, the extension just helps you work with plantuml.jar, you get the image, it has done its job. 

If you think it’s an issue, you should try contact the author of plantuml, though I think it’s even not a problem of plantuml, but the system default font your are using.

**Comment by ndrwrbgs** [comment]
Can we get a cross reference to a github issue in plantuml?
It must not be the system font as shown here (it's probably something to do with it trying to detect roman numerals)
"buildii"
![image](https://user-images.githubusercontent.com/10776890/103244077-70ca8100-4921-11eb-8218-225204e8cb16.png)
"buildiii"
![image](https://user-images.githubusercontent.com/10776890/103244092-7de77000-4921-11eb-9db3-3a78b016b8a6.png)
