### ISSUE TITLE
need support using Environment variables in modify "plantuml.jar"

### ISSUE THREAD

**Issue by LuoDiKaiHua** [qjebbs/vscode-plantuml#242]
"plantuml.jar": "${env:PLANT_UML_HOME}/plantuml.jar"

**Comment by LuoDiKaiHua** [comment]
> "plantuml.jar": "${env:PLANT_UML_HOME}/plantuml.jar"

It's useful when sharing configurations on multiple computers.

**Comment by anb0s** [comment]
It's not a vscode-plantuml issues, but VSCode itself, see: https://github.com/microsoft/vscode/issues/2809
