### ISSUE TITLE
Extract PlantUML Diagram source from Image seems don't work

### ISSUE THREAD

**Issue by zoulja** [qjebbs/vscode-plantuml#243]
Extension version 2.11.0
VS Code 1.36.0

Just now I found extraction doesn't work anymore, even I used it many times on previous versions without any problem. Is there some configuration parameter I must apply?

**Steps:**
1. Create sequence diagram
2. Export to PNG and close file.
3. View->Command Palette...->PlantUML:Extract PlantUML Diagram source from Image
4. Choose PNG created on step 2.

**Expected result:**
Diagram source of step 1 is extracted and available for editing

**Actual result:**
Text "No diagram found" is displayed

**Comment by qjebbs** [comment]
I think later version of `plantuml.jar` has removed the meta data in exported png. It's not a problem of this issue. You may post and issue to https://forum.plantuml.net/

**Comment by zoulja** [comment]
Thanks a lot for your analysis!
I've found it was addressed in recent beta, so everybody who also affected can solve it:
https://forum.plantuml.net/9739/why-did-output-no-diagram-found

**Comment by qjebbs** [comment]
The integrated jar has been updated to solve this issue, closing...
