### ISSUE TITLE
Zoom in preview mode is not working properly on smaller diagrams

### ISSUE THREAD

**Issue by omihalas** [qjebbs/vscode-plantuml#244]
Hello,

For example , If you make a smaller diagram like this one 

@startuml test
start
:Test test;
stop
@enduml

You will notice how zoom will go off from the view port and if i want to drag the picture not working.

Thank you !
![Screenshot_1](https://user-images.githubusercontent.com/52756478/60999280-6dc18680-a363-11e9-9d57-be099062fbf2.jpg)

**Comment by qjebbs** [comment]
Cannot reproduce here on Mac

**Comment by omihalas** [comment]
The problem I am able to reproduce on windows 10

**Comment by omihalas** [comment]
Thank you !!! 
I updated the plugin and cofirm that it works !
