### ISSUE TITLE
Use remote server even when local is selected

### ISSUE THREAD

**Issue by jcayzac** [qjebbs/vscode-plantuml#247]
![](https://i.imgur.com/XqD7en5.png)

Using version 2.11.2 with settings:

```json
{
    "plantuml.exportFormat": "svg",
    "plantuml.server": ""
}
```

I don't understand why it's going to the server. When it doesn't say `Service Overflow` it also complains about not finding the image in `/home/ec2user`.

I have no problem generating the diagram offline with plantuml.jar.

**Comment by jcayzac** [comment]
So, this works on the command line:

```sh
/usr/bin/java -jar /opt/plantuml/plantuml.jar -tsvg -graphvizdot /usr/local/bin/dot foo.puml
```

But vscode-plantuml always use the server with this settings:

```json
{
    "editor.minimap.enabled": false,
    "editor.suggestSelection": "first",
    "git.path": "/usr/local/bin/git",
    "java.configuration.checkProjectSettingsExclusions": false,
    "markdown.preview.scrollEditorWithPreview": false,
    "markdown.preview.scrollPreviewWithEditor": false,
    "markdownAutoTOC.header": false,
    "markdownAutoTOC.headerContent": "",
    "markdownAutoTOC.maximumHeadingLevel": 5,
    "plantuml.commandArgs": ["-graphvizdot", "/usr/local/bin/dot"],
    "plantuml.exportFormat": "svg",
    "plantuml.jar": "/opt/plantuml/plantuml.jar",
    "plantuml.java": "/usr/bin/java",
    "plantuml.render": "Local",
    "terminal.integrated.rendererType": "dom",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "window.zoomLevel": 1,
    "workbench.colorTheme": "Default Light+"
}
```

Please help me understand.

**Comment by qjebbs** [comment]
The markdown engine, which called MarkdownIt, doesn’t allow asynchronous calls, but the local render is sure asynchronous. I know some people concern about sharing data to plantuml sever, that’s why I am considering remove markdown support until user specifies his/her own server.

**Comment by jcayzac** [comment]
Stupid question maybe, but why isn’t vscode-plantuml spawning a local plantuml server on the local interface then?

**Comment by jcayzac** [comment]
Alternatively you can spawn a webworker and do the asynchronous work there, and wait for completion synchronously in the markdown plugin.

**Comment by qjebbs** [comment]
@jcayzac MarkdownIt doesn’t allow asynchronous calls, that means it doesn't wait for any asynchronous tasks. How can I make it wait synchronously for a asynchronous task?

**Comment by jcayzac** [comment]
@qjebbs typically by looping and sleeping indefinitely until the job in the worker is done.

**Comment by qjebbs** [comment]
@jcayzac No, it's far too not elegant.

**Comment by qjebbs** [comment]
One more thing, even if this feature implemented, do you feel ok if the markdown preview refreshing so slow? 30 seconds or more waiting, each time you type a character...

**Comment by jcayzac** [comment]
> it's far too not elegant.

A process sleeping until it gets a completion signal from another process is exactly what already happens when you make a blocking call to PlantUML server.

> One more thing, even if this feature implemented, do you feel ok if the markdown preview refreshing so slow? 30 seconds or more waiting, each time you type a character...

As opposed to no UML rendering in Preview at all because I'm getting a "Server overflow" error, like what this plugin does now? Yes, definitely.

**Comment by qjebbs** [comment]
Loop doesn't equal to sleep, or a program interrupt, or wait... Rendering markdown takes 0.1 sec, while rednering one single diagram takes 30sec. It means your CPU runs at full speed for nothing in 99% of time. 

Anyway, you can fork and try on your own PC, experiencing what I said.
