### ISSUE TITLE
Diagram with macros does not render

### ISSUE THREAD

**Issue by chbndrhnns** [qjebbs/vscode-plantuml#248]
I am trying to preview an [example](https://github.com/RicardoNiepel/C4-PlantUML/blob/master/LayoutOptions.md#layout_top_down-or-layout_left_right) and it fails with 

Example:
```
@startuml LAYOUT_TOP_DOWN Sample
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

/' Not needed because this is the default '/
LAYOUT_TOP_DOWN

Person(admin, "Administrator")
System_Boundary(c1, 'Sample') {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")
@enduml
```

Error:
```
Error found in diagram LAYOUT_WITH_LEGEND Sample
Syntax Error? (@ Diagram Line 3, File Line 4)
"LAYOUT_WITH_LEGEND"
(Error)
```

It renders fine in https://liveuml.com/.

**Comment by haakoo** [comment]
I have the same problem. It used to work, but I'm not sure when it stopped working or why.

**Comment by haakoo** [comment]
I found a fix for the problem over at https://github.com/RicardoNiepel/C4-PlantUML/issues/23

change `LAYOUT_WITH_LEGEND` to `LAYOUT_WITH_LEGEND()` - not sure why this works.

**Comment by qjebbs** [comment]
Seems it relates to plantuml.jar, not the extension.
