### ISSUE TITLE
Formatting option 

### ISSUE THREAD

**Issue by razakpm** [qjebbs/vscode-plantuml#25]
Default formatting not working with plant-UML code. Any easy way for it? 

Please find a sample 

@startuml
title A sample to show format Requirement
start
partition Sample_Partition
:Open “ABCD” downloaded file;
:In Load Sample images;
while (Some available for help?)
    :Read the complaint;
    if(need a reply”?) then(yes)
    :Add reason in File;
    else (no)
        if(need to be included?) then(yes)
            :Add reason in file;
        else (no)
            if(need to apply label?) then(yes)
                :Apply label;
            else (no)
                :No change needed;
            endif
        endif
    endif
:update pdf with proper stamping;
endwhile
stop
@enduml

**Comment by qjebbs** [comment]
Hmm...I don't have experience about formatting. Is anyone can help do this?

PS: PlantUML syntax is still increasing, and unlike common program languages, it's very hard to analysis. I deeply aware this when I was writing PlantUML syntax highlight.
