### ISSUE TITLE
Hide controls within preview

### ISSUE THREAD

**Issue by dkhanolkar** [qjebbs/vscode-plantuml#251]
Hi all,

Is there a way to hide controls within the preview window?
I typically zoom in, take a clipboard screenshot and find it annoying to have the controls in it. 

Cheers

**Comment by qjebbs** [comment]
Not yet, any PRs are welcome

**Comment by devnotfound** [comment]
Hey,

I've raised a PR, sorry it took a bit long.

**Comment by qjebbs** [comment]
Does the current behavior works for you? Move your cursor out of the preview window before a screenshot, all controls are hidden.

If we don't see the necessity, I prefer not to increase the complexity.

**Comment by qjebbs** [comment]
And even you don't want to see the controls, we can't just remove them, but hide them, and shows when users still need them sometimes. Consider a multi-page diagram, if controls are removed, how can user switch pages? 

Controls are part of the preview logic, and not dispensable.

**Comment by devnotfound** [comment]
I just noticed the show/hide controls triggered by the cursor location, thats quite handy. However completely hiding controls would be useful if someone is running a live demo (have to use the mouse to point aspects in the design) or recording their screen and has to resize the webview.

**Comment by devnotfound** [comment]
Hey mate, I've made this change. Let me know what you think. Cheers!

**Comment by qjebbs** [comment]
Let's continue our discuss here: #273
