### ISSUE TITLE
md file with plantuml code not working in preview

### ISSUE THREAD

**Issue by nwadhera** [qjebbs/vscode-plantuml#254]
Issue Type: <b>Bug</b>

alt-d works

Extension version: 2.11.2
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (19.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by qjebbs** [comment]
![image](https://user-images.githubusercontent.com/16953333/63560825-16c9e680-c58a-11e9-8c08-c4c700b1b171.png)

cannot reproduce

**Comment by nwadhera** [comment]
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299

Well working now, not sure what changed except that I closed the folder and
reopened it.
