### ISSUE TITLE
Enforce preview with white background in dark theme 

### ISSUE THREAD

**Issue by cveld** [qjebbs/vscode-plantuml#257]
Following up on https://github.com/qjebbs/vscode-plantuml/issues/52

I am looking for a way that the preview is rendering with a white background while vscode is in dark theme.
The exported svg must not contain a background directive, being just transparent for incorporating the svg in other environments.

The out of the box dark theme setup is unreadable.

![image](https://user-images.githubusercontent.com/6196260/64648592-7abe2d00-d41b-11e9-9d7a-9658bdab033d.png)

**Comment by qjebbs** [comment]
#52 is an outdated issue. What's your point? It's already the white background.

![image](https://user-images.githubusercontent.com/16953333/65115266-3a157380-da1a-11e9-98f4-5ed7a1378ef5.png)

**Comment by cveld** [comment]
Hi Jebbs, at my side it is still dark. Version 2.12.0 of the plug-in
"PlantUML". See screenshot:

[image: image.png]

Op wo 18 sep. 2019 om 07:43 schreef Jebbs <notifications@github.com>:

**Comment by qjebbs** [comment]
@cveld No screenshot found.

**Comment by cveld** [comment]
Second try:
![image](https://user-images.githubusercontent.com/6196260/65178296-bb8bf680-da58-11e9-85c3-17df2ce289f7.png)

**Comment by qjebbs** [comment]
Oh, it's not the preview, but markdown integration. Should be fixed with next release.
