### ISSUE TITLE
Markdown preview unable to render using Strict security setting

### ISSUE THREAD

**Issue by changsheng1239** [qjebbs/vscode-plantuml#258]
During markdown preview, diagram only render if **Preview Security Setting** is disabled. 

*settings.json*
```json
{
    "plantuml.render": "PlantUMLServer",
    "plantuml.server": "https://www.plantuml.com/plantuml"
}
```

Using my local plantuml.server with ssl, still getting the same result (unable to render under Strict setting). 

However, it works on version 2.11.2. Markdown preview can render the plantuml diagram with Strict security setting.

**Comment by ngeor** [comment]
Thank you for fixing this!
