### ISSUE TITLE
I write multi-space in note, but the render result is one space only.

### ISSUE THREAD

**Issue by KKKErde** [qjebbs/vscode-plantuml#259]
![Snipaste_2019-09-18_12-01-42](https://user-images.githubusercontent.com/28478390/65110804-2ebb4b80-da0c-11e9-8932-7345a79ccfa2.png)

**Comment by KKKErde** [comment]
`note left
    至此，就得到了override模块中的如下接口。
    callbacks->chi_get_num_cameras              = chi_get_num_cameras;
    callbacks->chi_get_camera_info              = chi_get_camera_info;
    callbacks->chi_initialize_override_session  = chi_initialize_override_session;
    callbacks->chi_finalize_override_session    = chi_finalize_override_session;
    callbacks->chi_override_process_request     = chi_override_process_request;
    callbacks->chi_teardown_override_session    = chi_teardown_override_session;
    callbacks->chi_extend_open                  = chi_extend_open;
    callbacks->chi_extend_close                 = chi_extend_close;
    callbacks->chi_remap_camera_id              = chi_remap_camera_id;
    callbacks->chi_modify_settings              = chi_modify_settings;
    callbacks->chi_get_default_request_settings = chi_get_default_request_settings;
    callbacks->chi_override_flush               = chi_override_flush;
end note`

**Comment by qjebbs** [comment]
It's not a bug of this extension, but the behavior of the `plantuml.jar`. I suggest you use table syntax instead. Here is an example:

```plantuml
@startuml

  title Activity
  start
  :Request;
  if (Request allowed) then (true)
      :Do things|
      note right
          Use of OpenIconic <&heart>
          this is a sprite icon <$disk>
          Click on <&wifi>
          this is &#8734; long 
          Example of simple table
          |= |= table |= header |
          | a | table | row |
          | b | table | row |
          Example of Tree
          |_ First line &#8734;
          |_ **Bom(Model)**
          |_ prop<&person>
          |_ Last line
      end note
  else (false)
  endif
  stop
  sprite $disk {
      444445566677881
      436000000009991
      43600000000ACA1
      53700000001A7A1
      53700000012B8A1
      53800000123B8A1
      63800001233C9A1
      634999AABBC99B1
      744566778899AB1
      7456AAAAA99AAB1
      8566AFC228AABB1
      8567AC8118BBBB1
      867BD4433BBBBB1
      39AAAAABBBBBBC1
  }
@enduml
```
