### ISSUE TITLE
Sequence Diagram: Syntax Highlighting for 'End Group'

### ISSUE THREAD

**Issue by kiebor** [qjebbs/vscode-plantuml#26]
![endgroup_err](https://cloud.githubusercontent.com/assets/14198213/25122701/ce25adf2-241d-11e7-8b89-28abab357c39.png)

**Comment by qjebbs** [comment]
According to plantuml document, the right syntax is:

```
@startuml
a->b:message
group 1
    a->b:message
    group 1.1
        a->b:message 
    end
end
a->b:message
@enduml
```
But your way, and even the following is good, so I think the highlight is right, isn't it?
```
@startuml
a->b:message
group 1
    a->b:message
    group 1.1
        a->b:message 
    end xxx
end yyy
a->b:message
@enduml
```
