### ISSUE TITLE
Server render: !include does not work for local files

### ISSUE THREAD

**Issue by soulim** [qjebbs/vscode-plantuml#260]
Hi,

I love the extension. Thank you a lot for amazing work! However there is one problem 😞  `~!include` does not work for local files and returns an error:

> Error found in diagram hello-world cannot include "style.puml" (@ Diagram Line 1, File Line 3) "!include "style.puml""
> (Error)

For the sake of simplicity I've created two dummy files:

**hello-world.puml**
```
@startuml hello-world
!include "style.puml"

Alice -> Bob : Hello world

@enduml
```

**style.puml**
```
skinparam {
  DefaultFontName "Fira Mono"

  monochrome true
  shadowing false
}
```

Both files are located in the same directory and the directory is configured as `diagramsRoot`.

Configuration:

```json
{
    "plantuml.server": "http://plantuml.test",
    "plantuml.render": "PlantUMLServer",
    "plantuml.diagramsRoot": "docs/diagrams/src",
    "plantuml.exportOutDir": "docs/diagrams/out"
}
```

*Note: `"http://plantuml.test"` is simply locally running PlantUML Server (in Docker container).*

For some reason the problem does not exist for remote files, e.g. `!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml` works perfectly fine.

I have tried absolute and relative file path. Nothing works 😢 

Extension information copied from VSCode:

```
Name: PlantUML
Id: jebbs.plantuml
Description: Rich PlantUML support for Visual Studio Code.
Version: 2.12.0
Publisher: jebbs
```

If you need any details, just let me know. Thank you a lot!

**Comment by qjebbs** [comment]
No, because server render cannot access your local file system. See https://github.com/qjebbs/vscode-plantuml#advantages-and-disadvantages-of-plantumlserver-render

**Comment by soulim** [comment]
Oh! I've read README few times, but somehow managed to miss this section :facepalm:

Thanks a lot for explanation and excuse me for stupid question.

The extension is amazing! Thanks! :+1:

**Comment by qjebbs** [comment]
You're welcome.😄

**Comment by anb0s** [comment]
I'm using the plugin and it works great! The include feature is really needed, also for local plantuml server. Would it be possible to do the file inclusion before sending the file content to the server?

**Comment by qjebbs** [comment]
@anb0s No, you will encounter 413 entity too large error

**Comment by anb0s** [comment]
@qjebbs ok, so there is a file size limit for upload (txt) and maybe download (png)? Do you know the numbers? I think include feature itself is not related to the limit size. I may have big diagrams without using includes...

**Comment by anb0s** [comment]
ok i've found something: https://github.com/plantuml/plantuml-server/issues/87

**Comment by anb0s** [comment]
If we are using such a version with upload file limit up to 32k usage of pre-included content would be perfect ;)

**Comment by qjebbs** [comment]
Does plantuml server support POST now? if it does, I can consider reopen this issue, though there are a lot of work to do, before server render could support include, and any PRs are welcome.

**Comment by anb0s** [comment]
Yes, plantuml supports POST: https://github.com/plantuml/plantuml-server/pull/74
and with Jetty server. we can adapt the "requestHeaderSize" to needed max value.

PR: Sorry, i've no experience with developing vscode plugins and cannot start soon. May be if our team switches from Eclipse to vscode it will change...

**Comment by qjebbs** [comment]
Things need to be correct in my former post: It's `414 URI Too Long`, not 413. 

`POST` support will likely solve most problems. But a lot if things need to be done, especially an `include` processor who behaves exactly like the `plantuml.jar`.

**Comment by qjebbs** [comment]
Please update to latest.

**Comment by anb0s** [comment]
Wow, That was fast!

I've just updated to v2.13.1 and works like expected with local (own) plant-uml server!

**Thank You!**

**Comment by Dadsh** [comment]
Hi! Is there a solution to this now? How do I get !include to work locally?
