### ISSUE TITLE
Confusing error message "no @startuml found"

### ISSUE THREAD

**Issue by DanielSundberg** [qjebbs/vscode-plantuml#265]
Copied a uml document from Jira, it lacks the @enduml tag and I get the confusing error message "no @startuml found". 

To reproduce, create a file with the following uml:
````
@startuml
:Hello world;
:This is defined on
several **lines**;
````
Then press Alt+D:

![2019-10-10 12_50_52-New Issue · qjebbs_vscode-plantuml](https://user-images.githubusercontent.com/1454200/66562808-b18f7c00-eb5c-11e9-89fd-adb9d3664405.png)

Adding the @enduml tag fixed the problem. However, for a newbie pasting some random puml this was a bit confusing.

**Comment by qjebbs** [comment]
Server behaves different with Local, within this topic.

- Same content as you provided, Local renders failed, while server renders OK.
- Remove the first line `@startuml`, Local renders OK, while server returns `500 error`

Anyway, this message is given by `plantuml.jar` or plantuml server, not the extension, it's better to improve in plantuml project's side.

**Comment by DanielSundberg** [comment]
If I try to reproduce this using the jar-file I get when I download plantuml.jar I get another error message:

````
>java -jar plantuml.jar -verbose test.puml
(0.000 - 15 Mo) 12 Mo - PlantUML Version 1.2019.12
(0.007 - 15 Mo) 12 Mo - GraphicsEnvironment.isHeadless() false
(0.012 - 15 Mo) 12 Mo - Found 1 files
(0.012 - 15 Mo) 12 Mo - Working on C:\code\plantuml\test.puml
(0.019 - 15 Mo) 11 Mo - Setting current dir: .
(0.020 - 15 Mo) 11 Mo - Setting current dir: C:\code\plantuml
(0.020 - 15 Mo) 11 Mo - Using default charset
(0.027 - 15 Mo) 11 Mo - Reading from test.puml
(0.039 - 15 Mo) 13 Mo - Reading file: test.puml
(0.039 - 15 Mo) 13 Mo - Number of image(s): 0
Warning: no image in C:\code\plantuml\test.puml
No diagram found
````

I still don't like the error message but at least it's a bit more generic.

Just trying to report on my initial experience with the extension. It wasn't a very pleasant experience. A new user that downloaded this extension 2 minutes ago has no idea about and doesn't care about server or local rendering.

**Comment by qjebbs** [comment]
Of course they don't. When I talk about renders, I'm talking about different messages the `plantuml` project (not the extension) gives. 

Please report to them. This extension just do its part of job, not to bypass, cover or change upstream project's behavior.

**Comment by fuhrmanator** [comment]
I found this issue for the same reason as @DanielSundberg (I'm trying to use it in courses with newbie students). 

I would like to report it upstream (PlantUML devs on github fix bugs very quickly). But I can't get an image with `no @startuml found` to appear when rendering locally. It's hard for me to reproduce this outside of the extension to make an issue on their github.

Can you explain how the extension shows the image with that error? Is it in a temp file on disk?

**Comment by qjebbs** [comment]
The extension sends what you're typing `as is`, to `plantuml.jar`, and shows what it gives back. Unless it's an error happens in this procedure, nothing I can do from the extension's end. 

Since I'm not the author of `plantuml.jar`, I cannot tell most details of it, all I know was posted above.

**Comment by DanielSundberg** [comment]
I also wanted to report this upstream but gave up since I could not get plantuml.jar to report the same error. 

If we reported this as is I'm pretty sure PlantUml would say it's a problem in this vscode-plantuml (since we get different behavior with plantuml command line).

**Comment by fuhrmanator** [comment]
Took me some time, but I think it's here: https://github.com/qjebbs/vscode-plantuml/blob/376caa7a89bc00f181f4ce13cc6603bc1c78c9ff/src/plantuml/renders/local.ts#L49

Here's how to reproduce it:

```bash
$ java -jar plantuml.jar -verbose -pipe < test.puml > out.png
```

Then view the `out.png`:

![image](https://user-images.githubusercontent.com/7606540/70167623-2383cd80-1695-11ea-81c1-44bffad47feb.png)

I tagged the PlantUML developer so he hopefully will see it here.
