### ISSUE TITLE
Cannot export Diagrams on macOS

### ISSUE THREAD

**Issue by CatMilk93** [qjebbs/vscode-plantuml#269]
https://github.com/qjebbs/vscode-plantuml/issues/4

vscode Version: 1.39.2
plantuml Version: 2.12.1
macOS 10.13.6 (17G4015)

I still cannot export Diagrams on my mac when i only open the file but not the folder.

**Comment by qjebbs** [comment]
Works good here. It should be exported to folder besides the file, not `exportOutDir`.
