### ISSUE TITLE
Not rendering in preview (Widows Subsystem for Linux)

### ISSUE THREAD

**Issue by MrDecisive** [qjebbs/vscode-plantuml#270]
Hi,

I'm using VSCode with Windows Subsystem for Linux (WSL). I installed the PlantUML plugin and added a test file. I tried preview and it complained about no java. I installed java. I tried preview again it complained (probably about graphviz). I installed graphviz. I tried preview, the little green processing symbol appeared animating for a second or two and then disappeared leaving only the blank preview panel with the little "broken image type icon" in the top left corner. There are no error messages now and I do not know where to look to see what is happening. Any ideas what is going on here?

![image](https://user-images.githubusercontent.com/57439965/68297392-b75e7b80-008e-11ea-8bb6-00ea65a3f332.png)

Environment details below

Cheers
Phill 

Windows 10
VSCode Version 1.39.2
WSL Ubuntu-16.04

PlantUML Plugin Version 2.12.2
Java 9
graphviz Version 2.38.0-12ubuntu2.1

Example plantuml file
---------------------
@startuml mydiagram

(*) -up-> "First Activity"
-right-> "Second Activity"
--> "Third Activity"
-left-> (*)

@enduml
-----------------------

**Comment by MrDecisive** [comment]
I used the VSCode web viewer developer tool to look at the image source (in the preview pane) it looked like this if it helps:

data:image/png;base64,IwojIEEgZmF0YWwgZXJyb3IgaGFzIGJlZW4gZGV0ZWN0ZWQgYnkgdGhlIEphdmEgUnVudGltZSBFbnZpcm9ubWVudDoKIwojICBTSUdTRUdWICgweGIpIGF0IHBjPTB4MDAwMDdmNmJlOWI0ZDAwOSwgcGlkPTI0MTAzLCB0aWQ9MjQxMDQKIwojIEpSRSB2ZXJzaW9uOiBPcGVuSkRLIFJ1bnRpbWUgRW52aXJvbm1lbnQgKDkuMCkgKGJ1aWxkIDktaW50ZXJuYWwrMC0yMDE2LTA0LTE0LTE5NTI0Ni5idWlsZGQuc3JjKQojIEphdmEgVk06IE9wZW5KREsgNjQtQml0IFNlcnZlciBWTSAoOS1pbnRlcm5hbCswLTIwMTYtMDQtMTQtMTk1MjQ2LmJ1aWxkZC5zcmMsIG1peGVkIG1vZGUsIHRpZXJlZCwgY29tcHJlc3NlZCBvb3BzLCBnMSBnYywgbGludXgtYW1kNjQpCiMgUHJvYmxlbWF0aWMgZnJhbWU6CiMgQyAgW2xpYmphdmEuc28rMHgxZDAwOV0gIEpOVV9HZXRFbnYrMHgxOQojCiMgQ29yZSBkdW1wIHdpbGwgYmUgd3JpdHRlbi4gRGVmYXVsdCBsb2NhdGlvbjogY29yZS4yNDEwMyAobWF5IG5vdCBleGlzdCkKIwojIEFuIGVycm9yIHJlcG9ydCBmaWxlIHdpdGggbW9yZSBpbmZvcm1hdGlvbiBpcyBzYXZlZCBhczoKIyAvbW50L2MvVXNlcnMvUF9MZXdpczAyLy52c2NvZGUvZXh0ZW5zaW9ucy9tcy12c2NvZGUtcmVtb3RlLnJlbW90ZS13c2wtMC4zOS45L2hzX2Vycl9waWQyNDEwMy5sb2cKIwojIElmIHlvdSB3b3VsZCBsaWtlIHRvIHN1Ym1pdCBhIGJ1ZyByZXBvcnQsIHBsZWFzZSB2aXNpdDoKIyAgIGh0dHA6Ly9idWdyZXBvcnQuamF2YS5jb20vYnVncmVwb3J0L2NyYXNoLmpzcAojIFRoZSBjcmFzaCBoYXBwZW5lZCBvdXRzaWRlIHRoZSBKYXZhIFZpcnR1YWwgTWFjaGluZSBpbiBuYXRpdmUgY29kZS4KIyBTZWUgcHJvYmxlbWF0aWMgZnJhbWUgZm9yIHdoZXJlIHRvIHJlcG9ydCB0aGUgYnVnLgojCg==

**Comment by qjebbs** [comment]
Decode the base64, you'll get:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f6be9b4d009, pid=24103, tid=24104
#
# JRE version: OpenJDK Runtime Environment (9.0) (build 9-internal+0-2016-04-14-195246.buildd.src)
# Java VM: OpenJDK 64-Bit Server VM (9-internal+0-2016-04-14-195246.buildd.src, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjava.so+0x1d009]  JNU_GetEnv+0x19
#
# Core dump will be written. Default location: core.24103 (may not exist)
#
# An error report file with more information is saved as:
# /mnt/c/Users/P_Lewis02/.vscode/extensions/ms-vscode-remote.remote-wsl-0.39.9/hs_err_pid24103.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

It looks like java+WSL doesn't work properly, additionally, they don't log to stderr, the problem is not on the extension side.

**Comment by MrDecisive** [comment]
Thanks Jebbs, That give me something to go on. I'll go poke around and see what I can find. If i do find a solution I'll post it back here. Cheers

**Comment by MrDecisive** [comment]
Sorted! - I removed the jdk 9 and went back to jdk 8 and now it works.

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

![image](https://user-images.githubusercontent.com/57439965/68375544-ef24fc00-013e-11ea-85bc-e91f35f01208.png)
