### ISSUE TITLE
Extension prevents markdown preview

### ISSUE THREAD

**Issue by garthk** [qjebbs/vscode-plantuml#271]
PlantUML extension 2.13.1

No other extensions enabled

PlantUML server running on 8080 in Docker container from image `plantuml/plantuml-server:jetty`

VS Code version details:

    Version: 1.40.0
    Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
    Date: 2019-11-06T17:09:34.601Z
    Electron: 6.1.2
    Chrome: 76.0.3809.146
    Node.js: 12.4.0
    V8: 7.6.303.31-electron.0
    OS: Darwin x64 19.0.0

Markdown document:

    # Demo

    ```plantuml
    @startuml
    testdot
    @enduml
    ```

`settings.json`:

    {
        "[markdown]": {},
        "plantuml.render": "PlantUMLServer",
        "plantuml.server": "http://localhost:8080"
    }

If I delete the fenced code block, VS code's Markdown preview works. If I put it back, the preview stops updating.

**Comment by qjebbs** [comment]
pls update
