### ISSUE TITLE
latest minor version (2.13) produces invalid png

### ISSUE THREAD

**Issue by catkins-miso** [qjebbs/vscode-plantuml#272]
Hello, I've rolled the extension back to 2.12 with no issues, but 2.13 seems to have broken png export. I had no issues with svg export, but png files were not able to be decoded.

Window 10 Pro
VS Code 1.39.2
PlantUML war  version 1.2019.11

I'm also using the extension in a remote container, but the exact config works with 2.12.

**Comment by qjebbs** [comment]
It's an unexpected behavior from the dependency `request`, when dealing with the POST body. I've remove the dependency to avoid this issue.
