### ISSUE TITLE
Render Chinese encoding error in 2.13.3

### ISSUE THREAD

**Issue by cuta** [qjebbs/vscode-plantuml#274]
After I upgraded to 2.13.3, the Chinese content is rendered as unknown characters. 

I tried to downgrade to 2.12.11, the Chinese content could be rendered well.

**Comment by cuta** [comment]
I use plant-server, and tested it separately with its web ui, it works well.

**Comment by cuta** [comment]
The VS Code Version Information list Below:

Cersion: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by qjebbs** [comment]
Waiting for upstream project to solve this issue.

https://github.com/plantuml/plantuml-server/issues/125

**Comment by fengyie007** [comment]
The plantuml server supports Chinese. 
But your plugin request does not have an Content-Type with charset in the http request header.
without charset
![image](https://user-images.githubusercontent.com/241077/68921036-4a479600-07b2-11ea-9ec1-3d355bd520be.png)
with charset
![image](https://user-images.githubusercontent.com/241077/68921056-5f242980-07b2-11ea-981a-71b0f6d65f7d.png)

**Comment by qjebbs** [comment]
@fengyie007 Thanks for pointing this out!
