### ISSUE TITLE
Error on ALT+D: command 'plantuml.preview' not found

### ISSUE THREAD

**Issue by mfmayer** [qjebbs/vscode-plantuml#275]
When pressing ALT+D I'm getting this error at the bottom right:
![image](https://user-images.githubusercontent.com/8875306/68958002-84716180-07cb-11ea-85ea-4d477e804300.png)

This happens on VSCode 1.40.1 using remote SSH and most recent PlantUML plugin (v2.13.3).

**Comment by qjebbs** [comment]
Try reconnecting to remote, I tested OK.

**Comment by mfmayer** [comment]
Reconnect didn't help. But after killing and restarting vscode remote server it worked again:

1. F1 --> Remote-SSH : Kill VS Code Server on host
1. Restart VS Code and reconnect to host (VS Code Server should automatically restarted).
