### ISSUE TITLE
Export behaves differently when working with folder

### ISSUE THREAD

**Issue by pato-p** [qjebbs/vscode-plantuml#277]
If I just open a PUML file and export a diagram, it appears in the directory where the file is located (as expected). However, if I have a folder opened in VS code, the exported file is generated in that folder, which might be different than a folder where PUML file is located. This behavior is very confusing and I have not found any way to configure this to match my expectations.

**Comment by qjebbs** [comment]
The extension is designed to work with workspace scenario, it's respect the setting `plantuml.exportOutDir`, exporting all diagrams to that dir. If you open a single file, of course, there's nowhere to go, but besides the source file.

if you want same behavior with single file scenario, just make:`plantuml.exportOutDir: ""`

**Comment by pato-p** [comment]
My settings are:
~~~
    "plantuml.exportFormat": "png",
    "plantuml.exportOutDir": "",
    "plantuml.exportSubFolder": false
~~~
Still, an `out` folder is created, and it is created in the workspace folder.
