### ISSUE TITLE
PlantUML in MD preview not working

### ISSUE THREAD

**Issue by venkateshsatharu** [qjebbs/vscode-plantuml#281]
Issue Type: <b>Bug</b>

Even though the plant uml server properly setup and then still preview not working.

Extension version: 2.13.5
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.52GB (16.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by qjebbs** [comment]
Good here, do you have steps to reproduce?

**Comment by venkateshsatharu** [comment]
Actually it is blocking to preview in a MD because our server we did setup was non secure http instead of https, but when I changed the settings to show preview from unsecure content also it started showing preview. But in that also two kinds of preview are there in VSCode , one with white background and another with black background. the black background one only working, for the white background preview it's coming as follows:
![image](https://user-images.githubusercontent.com/54305397/70778139-845d8500-1dbc-11ea-965a-1cf07733a7fd.png)

**Comment by qjebbs** [comment]
I knew it... and I guess you installed other markdown preview extensions, I have only one markdown preview command/button here

**Comment by kid1412621** [comment]
![image](https://user-images.githubusercontent.com/26278054/73717272-434a7700-4754-11ea-8f1e-a74c4f6cee72.png)

**Comment by qjebbs** [comment]
@kid1412621  Place the cursor in target diagram, and try?

**Comment by kid1412621** [comment]
> @kid1412621 Place the cursor in target diagram, and try?

I've tried on MacOS, it's fine. But It not works on Windows using Docker.
