### ISSUE TITLE
extension cannot found local java (using Remote-SSH)

### ISSUE THREAD

**Issue by narikazu58** [qjebbs/vscode-plantuml#284]
I tried this extension on below.
- host: win10
- guest: ubuntu18.04
- runs vscode in host, runs extention in guest(so using also Remote-SSH extension),

But extension cannot found java in guest, I used below when install.
  `apt-get install -y openjdk-11-jdk`
  `apt-get install -y graphviz`

Error message is 'Java not found, sets $PATH or plantuml.java ...', but I had set `/usr/bin/java` to plantuml.java.
![issue0119](https://user-images.githubusercontent.com/36873503/72682633-867cd700-3b12-11ea-8118-a7cdc2c523ed.png)

what can i do?

**Comment by qjebbs** [comment]
I tested with remote: `ubuntu`, cannot reproduce your problem. Make sure:

- install this extension in remote
- install java and graphviz in remote
- don't override `extensionKind ` setting, like:

```jsonc
{
  "remote.extensionKind": {
    "jebbs.plantuml": ["workspace","ui"] // correct
    // "jebbs.plantuml": ["ui","workspace"] // incorrect
  }
}
```

**Comment by narikazu58** [comment]
thank you for your answer.

>don't override extensionKind setting, like:

yes, I didn't override it.
so may be cause of environ...?

after all I concerned... may I use this extension like?:

<pre>
local [win10] //java not exists
  - vscode //shows plantuml tab with remote *.pu file(Alt+D) ...first capture is here!
     |
     |  ssh via Remote-SSH extension
     |
remote [ubuntu]
  - java
  - graphviz
  - vscode.extension:plantuml //this exteinsion
  - *.pu files                //plant uml sources
</pre>

**Comment by qjebbs** [comment]
Does it work according to settings in your last post? I think you had the right setup.

**Comment by narikazu58** [comment]
Unfortunately, not work.an usual, `java not found`...
I understood this setup is right, but i think cause is my environment.

i will avoid this, by setups `plantuml-server` on remote and using it.
```
plantuml.render = 'server'
plantuml.server = (plantuml-server URL on remotes)
```
thanks.

**Comment by narikazu58** [comment]
this occurred someone else? if not, will closing this issue.
