### ISSUE TITLE
Syntax-color of messages is same as of comments

### ISSUE THREAD

**Issue by AxxL** [qjebbs/vscode-plantuml#285]
Steps to reproduce

* Create a simple sequence diagram like:
``` puml
@startuml
/' 
  Block comment
 '/
Foo1 -> Foo2 : to foo2
' Comment
Foo1 -> Foo2 : to foo1
@enduml
```
* Switch to a color scheme in vscode, like Dark, Dark+, Solarized Dark, Solarized, Quiet Light.

Observed behaviour:

Notice, that the syntax color of the messages ("to foo2", "to foo1") is the same like the comments. In some color schemes of vs code (like mentioned above), where the colors of comments are grey and do not really distract the readability, also the messages are not really good to read. But since they are more important for writing the diagram, they should be in another, readable color.

Expected behaviour:

To increase the readability, the color of the messages should not be the same as of the comments and should be really readable.

Notes:

As I don't know the concept of syntax highlighting in vscode, I cannot propose an idea how to deal with that. Since you have already defined these structures in files like the  "diagram.yaml-tmLanguage", I hope it's only to change the "messages" to another color or syntax-group so that vscode highlights them in a different way.

Example screenshot:

![screenhot](https://user-images.githubusercontent.com/2235393/73348099-12b49a00-4289-11ea-974d-732e21b31150.png)

**Comment by cliffbender** [comment]
I'd like to advocate for the ability to change syntax highlighting colors. I, too, use the dark theme and I find it hard to read the messages and comments in my PUML files.

**Comment by DavidExtern** [comment]
really need it 👍

**Comment by fuhrmanator** [comment]
Related (duplicate?) of https://github.com/qjebbs/vscode-plantuml/issues/327

**Comment by AxxL** [comment]
Thanks. :)
