### ISSUE TITLE
Include on main document only previews included file 2.13.6 w/ local PlantUML Server

### ISSUE THREAD

**Issue by polobo** [qjebbs/vscode-plantuml#298]
With the following two files in the same directory on my local filesystem I get a generic diagram with the Computer agent.  If I then comment out the include I get a sequence diagram with the Person actor.

The logging shown produces 
```
inlib
inlib
``` 
when the include is present and 
```
inmain
inmain
```
when it is commented out.

I was expecting the logging to show:
```
inmain
inlib
```
I'm using:
PlantUML Server v1.2020.02 (Tomcat, Jetty gave similar results but the log file was messy due to its handling of filesystem permission)

PlantUML VSCode Extension v2.13.6

Is this supposed to work?

Thanks!

Dave

Main.plantuml
```
@startuml Main
!log inmain
!include lib.iuml
actor Person
@enduml
```
lib.iuml
```
@startuml Lib
!log inlib
agent Computer
@enduml
```

**Comment by flwidmer** [comment]
I think I have the same issue.

I checked the following:

colors.puml
``` 
@startuml
skinparam entity {
  BorderColor #0082A1
  BackgroundColor #80C1D0
  FontStyle bold
}
@enduml
``` 

diagram.puml
``` 
@startuml
!include colors.puml
title test
@enduml
``` 

Export of diagram.puml results in a white image.
Reverse of this white image (using png metadata) shows:
``` 
@startuml
skinparam entity {
  BorderColor #0082A1
  BackgroundColor #80C1D0
  FontStyle bold
}
@enduml
``` 
I also tried using two includes, to me it seems only the first gets resolved and completely replaces the content.

**Comment by qjebbs** [comment]
@polobo @flwidmer  I think it works good here

<img width="511" alt="image" src="https://user-images.githubusercontent.com/16953333/79067849-09b65f00-7cf5-11ea-9fea-176589bd858f.png">

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/16953333/79067912-9d882b00-7cf5-11ea-9daf-6c5b90d38646.png">

**Comment by flwidmer** [comment]
@qjebbs I forgot to mention that this happens with the plantuml server config:
``` 
"plantuml.render": "PlantUMLServer",
"plantuml.server": "http://localhost:9080",
"plantuml.urlResult": "SimpleURL",
"plantuml.java": "C:\\java\\jdk-11.0.5+10\\bin\\java.exe"
```
When I try with local renderer, this does work.

I might find the time later to pinpoint it in the code and provide a PR.

**Comment by NickClark** [comment]
Observing the same behavior here. Using the same logging approach as @polobo. Only the include log get's hit

**Comment by neumantm** [comment]
Same issue here. I think this is the case, because the plugin put's together the files before sending them to the server. During this operation the `@startuml` and `@enduml` tags from the included file are copied into the outer file. Therefore we end up with multiple nested `@startuml`-`@enduml`-blocks. The plantuml server seems to only evaluate the inner one. 

A workaround I found: In the inlcuded file omit the e `@startuml` and `@enduml` tags. This way the outer file compiles correctly, but the inner file cannot be compiled on its own anymore.
