### ISSUE TITLE
Impossible to generate PDF

### ISSUE THREAD

**Issue by Kroptia971** [qjebbs/vscode-plantuml#3]
Hello,

when I try to export to PDF, i got error :
`java.lang.ClassNotFoundException: org.apache.batik.apps.rasterizer.SVGConverter 
 at java.net.URLClassLoader.findClass(Unknown Source) 
 at java.lang.ClassLoader.loadClass(Unknown Source) 
 at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) 
 at java.lang.ClassLoader.loadClass(Unknown Source) 
 at java.lang.Class.forName0(N
 ative Method) 
 at java.lang.Class.forName(Unknown Source) 
 at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:48) 
 at net.sourceforge.plantum`

I saw on official website plantUml, that it needs more lib :
**Original post**
[http://plantuml.sourceforge.net/qa/?qa=4334/trying-to-produce-pdf-output-crashes-plantuml](url)

**Official Response**
[http://plantuml.com/pdf](url)

How could I activate it on your plugin ?

Regards
Marco

**Comment by qjebbs** [comment]
Yes, as I tried, export to PDF not always work. You need download libs mentioned in that post, and put them to the plugin root folder. Then, it works at least for this diagram:
```
@startuml seq
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
```
This shows that the plguin works right, so the errors is about the PlantUML implemetion, and I can't do anything about it. Sorry...

But, you can try would "download and place latest libs" help or not, cause I just used the zip package in the post, which means they may out-of-date.

**Comment by qjebbs** [comment]
closed due to no more activities.

**Comment by Kroptia971** [comment]
Hello,
Sorry for late.
I fixed it by download the package, and put all .jar into `%userprofile%\.vscode\extensions\jebbs.plantuml-***`
Then I modify file  `%userprofile%\.vscode\extensions\jebbs.plantuml-***\out\src\exporter.js` by adding all jar reference (last one is plantuml.jar) like that :

> constructor(config, context, outputPanel) {
	this.config = config;
	this.context = context;
	this.outputPanel = outputPanel;
	this.java = "java";
	this.javeInstalled = true;
	this.testJava();
	**this.jar = path.join(context.extensionPath, "ant.jar");
	this.jar = path.join(context.extensionPath, "avalon-framework-4.2.0.jar");
	this.jar = path.join(context.extensionPath, "batik-all-1.7.jar");
	this.jar = path.join(context.extensionPath, "commons-io-1.3.1.jar");
	this.jar = path.join(context.extensionPath, "commons-logging-1.0.4.jar");
	this.jar = path.join(context.extensionPath, "fop.jar");
	this.jar = path.join(context.extensionPath, "xml-apis-ext-1.3.04.jar");
	this.jar = path.join(context.extensionPath, "xmlgraphics-commons-1.4.jar");
	this.jar = path.join(context.extensionPath, "plantuml.jar");**
}

**Comment by qjebbs** [comment]
No, you don't need to modify any code. Your code above actually does nothing...
Once you place jars in root, you should be able to export PDF, at least works for the sample given in my last post. If not, then just give up, or report to http://plantuml.com.

**Comment by Kroptia971** [comment]
You've totally right.
Thank you ;)

**Comment by CarmenLee111** [comment]
I had the same question and here's what I did that fixed my problem. 
- Download the `plantuml.jar` file at https://plantuml.com/download
- Download the zip which contains the required library as instructed here: https://plantuml.com/pdf
- Unzip and move all the `jar` files including `plantuml.jar` to `$JAVA_HOME/jre/lib/ext`
Now I can export the diagram to `.pdf` format. :)

**Comment by dmitry-kabanov** [comment]
> I had the same question and here's what I did that fixed my problem.
> 
>     * Download the `plantuml.jar` file at https://plantuml.com/download
> 
>     * Download the zip which contains the required library as instructed here: https://plantuml.com/pdf
> 
>     * Unzip and move all the `jar` files including `plantuml.jar` to `$JAVA_HOME/jre/lib/ext`
> 
> 
> Now I can export the diagram to `.pdf` format. :)

Actually, as is written at <https://plantuml.com/pdf>, it is not necessary to put the `jar` files to `$JAVA_HOME/jre/lib/ext`. The main thing is that the other libraries are in the same path as the `plantuml.jar` file.
