### ISSUE TITLE
Multiline note syntax not correct

### ISSUE THREAD

**Issue by yogendra** [qjebbs/vscode-plantuml#30]
Sample code:
```
A -> B: Get Foo
note right
    Multiline Notes
    Example Here
endnote
A <- B: Return Foo
```
I expect `A <- B: Return Foo` to be highlighted just like `A -> B: Get Foo`. But Its shown in green (See attached screenshot)
<img width="232" alt="screen shot 2017-04-19 at 12 29 36 pm" src="https://cloud.githubusercontent.com/assets/793077/25163361/4219d6be-24fc-11e7-84a1-ac982b52b27d.png">

**Comment by yogendra** [comment]
Okay, I got it. `endnote` is not recognised by the plugin. Using `end note` works fine.
<img width="171" alt="screen shot 2017-04-19 at 12 40 50 pm" src="https://cloud.githubusercontent.com/assets/793077/25163507/757aa636-24fd-11e7-88ac-782b557a4173.png">

**Comment by qjebbs** [comment]
fixed.
