### ISSUE TITLE
2.13 not falling back from POST to GET

### ISSUE THREAD

**Issue by jonesmp** [qjebbs/vscode-plantuml#300]
I'm trying to render from a private server (I don't manage) that doesn't have POST enabled from what I can tell. When I try to render the diagram using 2.13, it fails with "404 not found POST https://plantuml-api...com/plantuml/svg/0/...". The server has a web UI that I can see uses a GET request instead of POST.

Is there something I need to configure on my side to make it fallback properly? Everything render fine using 2.12.

**Comment by deedf** [comment]
I'm having a different but similar problem where the plantuml-v1.2020.4.war I have downloaded fails POST with a 500, but GET works fine. It think the branch at https://github.com/qjebbs/vscode-plantuml/blob/690b57ae04106ecf49eb9a3e23629df4b6e6da98/src/plantuml/renders/plantumlServer.ts#L57 should also be taken for 404 and 5xxx, currently it seems very brittle.

**Comment by deedf** [comment]
I can do the change above if people agree it's desirable.

**Comment by abulka** [comment]
@jonesmp I ran into the same problem and same error message having vscode-plantuml talk to a new plantuml server I had deployed via [dokku](http://dokku.viewdocs.io/dokku/) - till I finally changed the url in my plantuml server address (in vscode plantuml settings) from 
`http://plantuml.dokku.me/plantuml`
to just
`http://plantuml.dokku.me`

When I was running plantuml server locally using `mvn jetty:run` the address `http://localhost:8080/plantuml` worked fine with vscode-plantuml (and indeed the `/plantuml` part of the url *is needed*), so I naturally assumed leaving the `plantuml` at the end of the dokku deployed server url would be ok, but it wasn't.

**Comment by jonesmp** [comment]
@abulka, thanks for the tip. Unfortunately, this doesn't work for me. I still get the 404 error with or without /plantuml as part of the server address.

I agree with @deedf that the current implementation seems rather brittle. I suppose it might be something that isn't configured ideally on the server I'm using, but I don't actually manage the server, so it's difficult to investigate from that end.

Looking at the code, it appears the intent was to optimize the behavior so that a server identified as a noPOSTServer won't attempt a POST on subsequent requests. This seems like something that would be best implemented as a configuration parameter as opposed to having the code gracefully handle a POST failure.

Alternative options to making POST/GET a configuration parameter would be:
- Whitelisting more exceptions, which still feels brittle since it will continue to be broken for any exceptions that aren't considered.
- Falling back to GET on any exception, which I think would cause the client to stop attempting to POST after encountering a transient error like a timeout. I'm not sure when the noPOSTServers state would get cleared, but I'm guessing you would have to close the preview tab and reopen it to reset the state.
- Remove the optimization entirely so that the logic always attempts to POST and then fallback to GET when POST fails, which will result in longer rendering times for servers without POST enabled.

https://github.com/qjebbs/vscode-plantuml/blob/690b57ae04106ecf49eb9a3e23629df4b6e6da98/src/plantuml/renders/plantumlServer.ts#L50-L66

**Comment by deedf** [comment]
@jonesmp thanks for the thoughtful comment. I mostly agree with all of it. Just 2 cents more: I think the actual logic we might is to distinguish diagram errors (syntax, etc.. ) from anything else.
If it's a diagram error, keep POSTing since the problem is in the data. If not, GET instead.
That's assuming we keep the existing guessing heuristic. But I agree a config parameter is cleaner.
Why not a (GET|POST|Detect) parameter, where 'Detect' would use the logic above of falling back to GET on non-diagram errors ?

**Comment by jonesmp** [comment]
Ah, yes. I hadn't considered that diagram errors would get caught here as well. I like the Detect option idea. The one drawback I saw to the config parameter approach is that it's an additional detail for the user to figure out when trying to connect to a new server. Having a default auto detect option would bridge that gap.

**Comment by qjebbs** [comment]
Thank you all for your ideas. 

Basically, I think, the extension should take care of as more situations as it could, so that users do not have to dig so deep to make the extension works as expected.

I wrote those code, assuming that the upstream project takes it a convention to use 405 to indicate non-POST-support. Unfortunately, it doesn't.

Two options:

1. Post an issue to upstream to unify the error code which is out of our control.
2. We cover as more codes as we collected.

**Comment by deedf** [comment]
I think posting an issue upstream is not super useful because the problem might sometimes be outside their control (ie the way the app is installed in a specific container, user configuration, etc).
I would go for a configuration option that says "GET" ,"POST", "Auto".
Where Auto defaults to POST and falls back to GET on any non-diagram errors.
And where Auto would be the default.

**Comment by jonesmp** [comment]
While I agree that it feels less than ideal for the user to need knowledge of low level details of the server API (i.e. GET/POST), I would rather (as a user) be able to dig deeper and get things working myself than to be dependent on a change to either the extension code or the upstream system. The problem with option 1 is that it may not actually be an option if the upstream team is unwilling to change for whatever reason. The problem with option 2 is that the user experience is even worse than choosing GET/POST/AUTO in the configuration settings if there are other error codes missing in the fallback logic.

I like @deedf's proposal of an Auto-Detect option as part of a configuration parameter because it feels like the best of both worlds. A default Auto-Detect option could use the existing fallback logic (with additional error codes), and it would communicate to the user that this option doesn't typically need to be changed. As a parameter, it would also give the user another setting to tweak to get things working in the event there were still missing error codes in the fallback logic.

With all that said, between options 1 and 2, my vote would be for 2. Option 1 is more likely to leave some people stuck on 2.12 because the fallback logic is essentially assuming a strict contract without any guarantee that the upstream server adheres to it. Option 2 loosens that assumption up a bit. If you were to implement it as a configuration setting, option 2 should probably still be included to ensure the Auto-Detect option has the highest chance of success.

**Comment by qjebbs** [comment]
The logic now, is to fallback if the server gave unexpected response, with codes other than 200. Post feedbacks here and reopen this issue if it doesn't work for you.
