### ISSUE TITLE
be able to show multiple diagrams on the same page

### ISSUE THREAD

**Issue by ghost** [qjebbs/vscode-plantuml#301]
Hi
I have a `test.puml` document containing this:
```
@startuml
participant a
participant b
a -> b
@enduml

@startuml
participant c
participant d
c -> d
@enduml
```

I would like the preview to show both images on the same Preview page. Currently only one diagram is shown at once, depending where I put the typing cursor in the code.

I know I can use `newpage` but `newpage` has a problem for sequence diagram, as it
would put all four `a, b, c, d` participants on every generated diagram instead of putting `a, b` on the first diagram and `c, d` in the second diagram.

**Comment by qjebbs** [comment]
No plan, since it not compatible with current UI, like zooming
