### ISSUE TITLE
Toggled line comments in markdown code fences are incorrect

### ISSUE THREAD

**Issue by andrewthauer** [qjebbs/vscode-plantuml#305]
Toggling line comments within markdown plantuml code fence adds `//` instead of a single quote.

Current Behaviour:

````
```plantuml
@startuml test
// this is toggled comment line
@enduml
```
````

Expected

````
```plantuml
@startuml test
' this is toggled comment line
@enduml
```
````

**Comment by qjebbs** [comment]
I don't know how to customize comment behavior within `Makdown` fences, from the extension's side.

If any one does, tell me, and PR is welcome. 

Thanks.

**Comment by andrewthauer** [comment]
Thanks. I’m not sure either. I would have thought this would happen by default considering the comment toggle works in dedicated plantuml files. Unless vscode doesn’t support this for extended code fence syntaxes like plantuml. I’ll do some investigation and report back.

**Comment by andrewthauer** [comment]
This is most likely relevant. https://github.com/microsoft/vscode/issues/71888

I’ll have a closer look when I get a chance and raise a PR if I figure it out.

**Comment by andrewthauer** [comment]
Turns out the issue is related to the setting `"meta.embedded.block.plantuml": "javascript"` in the `package.json` (line 68). Changing this setting from `javascript` to `diagram` will fix the issue. 

However, I question why the language grammar is identified as `diagram` rather then `plantuml` (see #306).
