### ISSUE TITLE
Grammar Language Identifier is `diagram` instead of `plantuml`

### ISSUE THREAD

**Issue by andrewthauer** [qjebbs/vscode-plantuml#306]
The language grammar for this extension is defined using a very generic identifier `diagram`. This seems ambiguous and not specific enough. This seems to be defined:

```json5
// line 55 in package.json
"grammars": [
      {
        "language": "diagram", // should be 'plantuml'??
        "scopeName": "source.wsd",
        "path": "./syntaxes/diagram.tmLanguage"
      },
}
```

Shouldn't the grammar language identifier be named `plantuml` instead? The term `diagram` seems to generic and not specific. In the `Change Language Mode` command it makes no mentioned to `plantuml` only `diagram`.

**Comment by fuhrmanator** [comment]
I agree - I was looking for PlantUML in the language of my new editor, but couldn't figure how to set it. I think many people will look for PlantUML rather than "Diagram".
