### ISSUE TITLE
Add a configuration file

### ISSUE THREAD

**Issue by purjus74** [qjebbs/vscode-plantuml#308]
Hi all,

Sorry, but I don't understand how to add a configuration file for local plantuml building.
My project folders hierarchy is:
```
.vscode
source
  | _plantuml
    | plantuml.config
    | test.puml
```

I have been tried to add the following configuration without success:
```
"plantuml.jarArgs": [
    "-config ./source/_plantuml/plantuml.config"
]
```

I obtained this error during the preview or generating:

![image](https://user-images.githubusercontent.com/30845890/79316163-41472600-7f04-11ea-9810-b0d024caf380.png)

Have you an idea?

Thank you in advance.

**Comment by GAM3RG33K** [comment]
I am having the same problem:

however my cofig file path is an absolute path, so this must be an issue in parsing the command from the settings file.

following is the setting I set for config:
```json
"plantuml.jarArgs": [
        "-config C:\\TOOLS\\PlantUML\\config\\plantuml.config"
    ],
```

**Comment by qjebbs** [comment]
try:

```
"plantuml.jarArgs": [
    "-config",
    "C:\\TOOLS\\PlantUML\\config\\plantuml.config"
],
```

**Comment by GAM3RG33K** [comment]
@qjebbs solution that you gave **works and resolved** the issue I had. 

So it seems that we have to separate the whole command into tokens, right? In my opinion, It's weird to use tokens instead of a whole string.

**Comment by qjebbs** [comment]
@GAM3RG33K You may feel it's weird, but it's the behavior of [nodejs spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options).

Anyway, this setting is for pro users.
