### ISSUE TITLE
Bug: Can't find Java with Alt + D in VSCode 1.44.0

### ISSUE THREAD

**Issue by RumSpy** [qjebbs/vscode-plantuml#309]
### Can't launch Diagrams in VSCode 1.44.0 update.

**Error:** 
```
Cannot find java!
If you've installed java, please add java bin path to PATH environment variable.
Or, configure java executable path with "plantuml.java".

```
**System Specs**
```
VSCode: 1.44.0
Electron 7.1.11
OS Win x64 10.0.18363
System Java 1.8.0.241 though User Java is 1.11.0.6
```

**Config:** fron settings.json
   ```
 // PlantUML
    "plantuml.diagramsRoot": "P:\\01 Code - REPO\\Solutions",
    "plantuml.previewSnapIndicators": true,
    "plantuml.java": "C:\\Program Files\\Java\\jdk-11.0.6\\bin",
    "plantuml.exportInPlace": true,
    "plantuml.jar": "C:\\Users\\{WINUser}\\.vscode\\extensions\\jebbs.plantuml-2.13.6\\",
    "plantuml.urlFormat": "png",
    "plantuml.previewAutoUpdate": true,
```

**Comment by RumSpy** [comment]
Tried adding java.exe
 https://github.com/qjebbs/vscode-plantuml/issues/112#issuecomment-497926414

**Comment by RumSpy** [comment]
And Java Bin folder is added to System Path
`If you've installed java, but still prompts "java not installed", please add java bin path to PATH environment variable `

**Comment by RumSpy** [comment]
And planutuml.jar from 
`C:\Users\Michael Hill\.vscode\extensions\jebbs.plantuml-2.13.6 and c> java -jar` is working

**Comment by qjebbs** [comment]
you set a java folder, not the executable
