### ISSUE TITLE
Syntax highlighting for "hnote" and "rnote" as group

### ISSUE THREAD

**Issue by hawakori** [qjebbs/vscode-plantuml#31]
In sequence diagram, keyword "hnote" and "rnote" is working right.
But, syntax highlighting seems not good at using group.

The keyword "note" is show highlight properly when using the group.

![image](https://cloud.githubusercontent.com/assets/4231701/25274703/4b22cdf2-26cc-11e7-9dd7-a63369b6ca18.png)

Thunks.

**Comment by qjebbs** [comment]
Was solved in: https://github.com/qjebbs/vscode-plantuml/issues/24
