### ISSUE TITLE
testJava not handling spaces in plantuml.java

### ISSUE THREAD

**Issue by mdonoughe** [qjebbs/vscode-plantuml#317]
I have multiple Java installations and I wanted to use the one at C:\Program Files\AdoptOpenJDK\jdk-11.0.2+9\bin\java.exe. If I enter that in the settings dialog, I get "Cannot find java!" when I try to preview my diagram.

PerfView detects the following command is being executed:

    C:\WINDOWS\system32\cmd.exe /d /s /c "C:\Program Files\AdoptOpenJDK\jdk-11.0.2+9\bin\java.exe -version"

Instead of this (strange looking) command which works:

    C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\Program Files\AdoptOpenJDK\jdk-11.0.2+9\bin\java.exe" -version"

If I put quotes around the value of plantuml.java, then PerfView sees `java --version` invoked correctly.

However, then when I preview my diagram I get a different error:

    Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at Socket._write (net.js:710:8)
    at doWrite (_stream_writable.js:418:12)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at c:\Users\mdono\.vscode\extensions\jebbs.plantuml-2.13.9\out\src\plantuml\renders\local.js:112:35
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

And PerfView does not show any further Java invocations.

ProcMon shows code.exe trying to open `C:\Users\mdono\AppData\Local\Programs\Microsoft VS Code\"C:\Program Files\AdoptOpenJDK\jdk-11.0.2+9\bin\java.exe"` as a file, but I can't tell if that's related to the failure or not.

If I replace tools.js `testJava` with `return true` and remove the quotes from plantuml.java then the preview works.

If I put the `testJava` code back and use `child_process.execFileSync(java, ["-version"]);` instead of the execSync that seems to also work and might be the correct fix?

**Comment by qjebbs** [comment]
Thanks for dig it deep, I believe your have already find the solution, while I'm have not windows environment to test this issue. So I choose to update the code, please report any later issues here if it has.

**Comment by mdonoughe** [comment]
`spawnSync` looks better, but I don't think it should work with the space before at the front of "-version". It definitely does work, but that seems like a bug in spawnSync? I get an error if I try the same thing from the command line, or even from my own copy of nodejs:

```
Welcome to Node.js v12.16.0.
Type ".help" for more information.
> child_process.spawnSync("java", [" -version"]).output.toString()
',,Error: Could not find or load main class  -version\n' +
  'Caused by: java.lang.ClassNotFoundException:  -version\n'
```

**Comment by mdonoughe** [comment]
`spawnSync` does not throw if the command returns an unsuccessful status, and `testJava` only cares about whether the call threw or not. With the space it is using Java returning an error as a sign that Java is installed.

**Comment by qjebbs** [comment]
My mistake, should take the space away.
