### ISSUE TITLE
Provide action to revert connections

### ISSUE THREAD

**Issue by svpace** [qjebbs/vscode-plantuml#328]
It would be awesome if this extension could provide an action to swap the order of elements in connections, for instance, changing `A --> B` to `B<--A`.  I find this "technique" quite useful to adjust the layout of diagrams in PlanUML. It would be great if I could acomplish that with a keystroke

**Comment by qjebbs** [comment]
Hmmm...It's so difficult to parse plantuml source code. Anyway, PRs are welcome.
