### ISSUE TITLE
macOS issue with fonts & newpage

### ISSUE THREAD

**Issue by rkayman** [qjebbs/vscode-plantuml#329]
````
@startuml
a -> b : msg 1
b -> a : msg 2
newpage
c -> d : msg 3
d -> c : msg 4
@enduml
````

results in...

<img width="1410" alt="Screen Shot 2020-07-02 at 9 22 14 PM" src="https://user-images.githubusercontent.com/372877/86431783-8cbed400-bcaa-11ea-848c-7f427b1948d2.png">

No newpages (navigation controls are not appended to usual icon helpers at bottom of screen), I get the typical set of 4 icons (zoom out, fit, zoom in, and help).

Also, you'll see the java complaints about fonts.  Is this a PlantUML issue? Do I need to post the issue there?

**Comment by qjebbs** [comment]
No. You should fix the font issue(I don't how), or report to PlantUML project. It's an error reported by `plantuml.jar`，not this extension.

**Comment by rkayman** [comment]
Thanks for fast response... As I researched more, yes this is an already reported issue in PlantUML.  It is related to OpenJDK (version 13 is latest installed by Homebrew as I write this).  Looks like OpenJDK has a fix in the pipeline.  I resolved quickly by installed Oracle's Java SE 14 which does not have the issue -- and that fixes the problem -- no font issues and newpage works as advertised.
