### ISSUE TITLE
Request to disable auto preview update for .iuml (or specified) files

### ISSUE THREAD

**Issue by dxf19** [qjebbs/vscode-plantuml#331]
I use .iuml files to contain procedures and functions.  When switching from a .puml file (with auto preview update) to a .iuml file included by it, the auto-preview tries and fails to render the .iuml file, as it has no content to render.  It would be better for the auto preview **not** to change.

Even better still would be for the auto-preview to update for the .puml file when the .iuml file included by it is updated.

(BTW, thanks for the awesome plugin.)

**Comment by qjebbs** [comment]
sorry, No plan about it
