### ISSUE TITLE
Support more predefined words on skinparam

### ISSUE THREAD

**Issue by fuhrmanator** [qjebbs/vscode-plantuml#333]
There are some missing predefined words, but I'm not sure where to add them in a PR: 

> skinparam style **strictuml**
> skinparam handwritten **true**
> skinparam ObjectAttributeFontStyle **normal**

For boolean, there is also **false**.
For font styles, there are **italic**, **bold** and **plain**.

I think these keywords are similar to **left**, **right**, **center** which are alignment keywords on skinparam. There are probably more to add; I didn't do a thorough search.

**Comment by fuhrmanator** [comment]
Some more:

> hide **circle**
> hide **empty members**
> hide **empty description**

Also, I'm happy try a PR if it's just adding them to the list at https://github.com/qjebbs/vscode-plantuml/blob/4c2ff69ac33bb4f97d104b6d587c33e675e6f13d/src/plantuml/intellisense/languageCompletion.ts#L3

**Comment by qjebbs** [comment]
@fuhrmanator Yes. PR is welcome
