### ISSUE TITLE
Additional Snippets

### ISSUE THREAD

**Issue by fuhrmanator** [qjebbs/vscode-plantuml#334]
The snippets are a great feature because the syntax of PlantUML isn't always easy to remember. Here are a couple of snippets I'd like to see added (I can do a PR if it's not a waste of my time):

* legend (applies to all diagram types I think)
* advanced syntax of messages in sequence diagrams: `A -[hidden]> B` or `A -[#red]> B` or `A -[#red,dashed]> B`
* advanced syntax of links in class diagrams: `ClassA "0..1" *-> "0..1" ClassB : "   association_name   "` or `A "1" -[#red,bold]> "1" B : creates`

Otherwise, maybe a preference to add snippets? Or is that already possible and I'm just a newbie to VSCode still? :)

**Comment by qjebbs** [comment]
The extension has included a set of snippets, if you want to define your own, see https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

**Comment by fuhrmanator** [comment]
Thanks! I played around with the following to embed a lot of the association syntax (even with choices):
```javascript
"Domain model association": {
	"scope": "plantuml",
	"prefix": "domain>association",
	"body": "${1:ClassA} \"${2:0..1}\" ${3|*,o|}-[${4:color},${5|bold,dashed,dotted|}]-${6|*,o|} \"${7:0..1}\" ${8:ClassB} : ${9:Verb}",
	"description": "Adds an association with lots of options."
}
```

**Comment by qjebbs** [comment]
If you find some snippets really useful, and willing to share, PRs are welcome
