### ISSUE TITLE
Won't send requests to HTTP servers

### ISSUE THREAD

**Issue by future-cyborg** [qjebbs/vscode-plantuml#336]
Despite the example, when plantuml.server is set to an HTTP address, no request is ever sent. This took me way to long to figure out, but looking through wireshark logs shows NO traffic whatsoever if the address is HTTP and not HTTPS. I have tried multiple different solutions, include hostnames, IP addresses and `localhost`. None of them work.

I can't simply change `http` to `https` since I don't have SSL setup.

Issue with 2.13.13, though I tried multiple versions as far back as 2.8. Same problem. Windows and linux.

**Comment by qjebbs** [comment]
Cannot reproduce. What can you see when hover to the red alert icon in preview? 
![image](https://user-images.githubusercontent.com/16953333/89964697-79296480-dc7d-11ea-87ef-ab6fa9e1d245.png)

**Comment by future-cyborg** [comment]
Thanks for the quick response. This was a false flag, I apologize.

I didn't have the red alert icon, so I kept looking. From a different computer the problem was obvious. I must have set `Disable preview security warning in this workspace`. Embarrassing (ー_ー﹡ )

**Comment by qjebbs** [comment]
I see, you were talking about markdown integration 😀
