### ISSUE TITLE
Error: Write EPIPE

### ISSUE THREAD

**Issue by parthsaxena1909** [qjebbs/vscode-plantuml#337]
![image](https://user-images.githubusercontent.com/51674408/90112075-27600780-dd6d-11ea-8ad1-ae43767eea95.png)

**Comment by parthsaxena1909** [comment]
could anyone help asap!?

**Comment by Alex-Jongman** [comment]
I have the same problem see #330.

**Comment by RonnyWeitzman** [comment]
Had the same problem. Copied the original plantuml.jar to c:\users\<username>\.vscode\extensions\jebbs.plantuml-2.13.13  and all came back to normal.

**Comment by hendrickh** [comment]
@parthsaxena1909 - I've just added a suggestion on [#330](https://github.com/qjebbs/vscode-plantuml/issues/330), hope this would helps your case

**Comment by Vivraan** [comment]
Reporting from #330 - this erro still persists. Please advise.

**Comment by Hadsch** [comment]
I had this problem too, just to recognize that I am the one to blame ;)

I specified the path to java directly like this:
`
  "plantuml.java": "C:/env/tools/jdk-11/bin/",
`
But it is not necessary to specify the folder, but the Java exe directly!

`
  "plantuml.java": "C:/env/tools/jdk-11/bin/java",
`

**Comment by Vivraan** [comment]
Seems like the problem is just lack of documentation.

**Comment by n-irwin** [comment]
+1 for lack of documentation

**Comment by parthsaxena1909** [comment]
Issue Solved :)
