### ISSUE TITLE
Lower-case "i" Displays as Capital in Arrow Text

### ISSUE THREAD

**Issue by tapiester** [qjebbs/vscode-plantuml#338]
Examples (using plantuml.com as the server):

```plantuml
@startuml
Bob --> Alice : hillo
@enduml
```

![image](https://user-images.githubusercontent.com/49066264/91304467-86634a80-e777-11ea-9742-4511f174f430.png)

```plantuml
@startuml
[Bob] --> [Alice] : hillo
@enduml
```

![image](https://user-images.githubusercontent.com/49066264/91304416-72b7e400-e777-11ea-9553-6e0dd9b5ea62.png)

Here is one of those examples rendered on plantuml.com directly in my web browser:

![image](https://user-images.githubusercontent.com/49066264/91304173-0f2db680-e777-11ea-8815-5bd0fdabb806.png)

**Comment by qjebbs** [comment]
The extension helps you work with plantuml project. It presents the result image, the job is done well. You should report any other issue to the plantuml project.

BTW: I'm using plantuml.com as server render, but I get the right look. You should check your system fonts
