### ISSUE TITLE
plantuml.jar does not work for new unsaved files

### ISSUE THREAD

**Issue by RedX2501** [qjebbs/vscode-plantuml#339]
I've tried with VS Code: 1.47.2 and Plantuml plugin 2.13.13.

To reproduce open a folder that contains a .vscode folder with a settings.json with a path to a plantuml.jar that can be found.

Now open a new file and paste some valid plantuml code.

See a message come up stating that the plantuml.jar specified cannot be found.

Save the file and see that plantuml.jar is used and found.

**Comment by qjebbs** [comment]
It's expected. Your settings.json contains settings for files inside this folder (workspace), now that your new file is not save to it, settings not applied.
