### ISSUE TITLE
Preview not updated when using newpage command

### ISSUE THREAD

**Issue by lsouchet** [qjebbs/vscode-plantuml#341]
Hello,

This issue is similar  to #184 that is supposed to be fixed since v2.10.13.

I encounter the issue using version 2.13.13 on Ubuntu 18.04 in VS code 1.49.0.
I use this sample code:
```
@startuml 
A->B: Hello 
newpage
 B->C: Hello 
newpage 
C->A: Hello 
A->A: back 
@enduml
```

When I open VS code, and press Alt+D, the preview is generated once, after that, when I update the file, I cannot update the preview, nor by using Alt+D or Ctrl+Maj+P>"PlantUML: Preview current diagram".
I need to restart VS code to have it working again.

Note that when using plantuml files without newpage commands I have no problem

**Comment by qjebbs** [comment]
![image](https://user-images.githubusercontent.com/16953333/93563589-ce623f80-f9ba-11ea-9ca1-31d1a652edc0.png)

I guess you forgot to switch pages..
