### ISSUE TITLE
Export diagrams create wrong folder

### ISSUE THREAD

**Issue by weismantelf** [qjebbs/vscode-plantuml#342]
I set in settings for the PlantUML plugin the Export Out Dir to the value "images"
and the Diagrams Root to "sequence_diagrams".

When I know export all diagrams of the workspace, the plugin is generating now the images for
the diagrams in the folder "images\_WorkspaceFolder_\sequence_diagrams" and not under the folder
"images".

Do I something wrong or is it a bug in the plugin?

This are my current user settings:

```
{
    "http.proxy": "http://ccapp_jupiter:8080",
    "editor.largeFileOptimizations": false,
    "http.proxyStrictSSL": false,
    "editor.renderControlCharacters": true,
    "plantuml.render": "PlantUMLServer",
    "plantuml.server": "http://localhost:8080",
    "plantuml.exportSubFolder": false,
    "plantuml.commandArgs": [

    
    ],
    "explorer.confirmDelete": true,
    "plantuml.diagramsRoot": "sequence_diagrams",
    "plantuml.exportOutDir": "images",
    "plantuml.exportFormat": "png"
}

**Comment by qjebbs** [comment]
See https://github.com/qjebbs/vscode-plantuml#typical-files-organization

`_WorkspaceFolder_` created only when your src files placed outside the `plantuml.diagramsRoot`

**Comment by weismantelf** [comment]
Hi,

my folder structure looking like this:

doc
  +---sequence_diagrams
  |           + diagram1.plantuml
  |           + diagram2.plantuml
  |
  + images

I have set the following values relative to my workspace folder:

   "plantuml.diagramsRoot": "sequence_diagrams"
    "plantuml.exportOutDir": "images"

In the beginning, I made the changes of the extensions setting on USER level. With this settings,
the generation of the images was working perfectly. After applying the values to the workspace
setting and removing them from the user settings, the problem was starting as described.

Then I was reverting everything and removed the settings from the workspace. But I have
still the same result, that the __workspaceFolder__ is created.

**Comment by weismantelf** [comment]
Now it is working for me. I have now uninstalled the extension and clean up everything in the user profile folder.
After a new installation of the extension everything is working. So I think there was something wrong in the
settings of the extensions.
