### ISSUE TITLE
Gantt diagram : Tasks or Milestones on the same line  on Error

### ISSUE THREAD

**Issue by kasra0** [qjebbs/vscode-plantuml#346]
Hi,

I'am trying to display 2 taks on the same line in a gantt diagram 

here is the sample code

```
@startgantt
[A] lasts 10 days
[B] lasts 5 days 
[B] starts  2 days after [A]'s end
[B] displays on the same row as  [A]
@endgantt
```
but i an getting a Syntax Error .

here is the working exemple in plantuml website
[http://www.plantuml.com/plantuml/uml/ZP6n3e9044Hxlc8wQmxj-GGBkml59hSY4UykjviG_buymCIWn7hUlDbaQr5Asf9NBUmv1GqwHePZwLhVe2THGLd1qIY5lR0euagjyJ6d8EzGOc2-Ry6y8akSIREKhie9s-M3WBtRYbmdiNyLWuVGWv72098lXiAcii6DOcIVyTD_Yydij2RbcwlsEFFX-tdrv9jDkqGzYUONFG40](url)

Does the  vscode extension implements this  functionnality or it's  an issue ?

my vscode-plantuml extension is the  2.13.13

thanks.

**Comment by qjebbs** [comment]
This may be relative to a outdated jar, you can:
- use and update your own copy of jar, see #349
- use a plantuml server, make sure someone updates the server in time

**Comment by kasra0** [comment]
i updated the plantuml.jar file  that was in the extension folder ( for me :  ...vscode\extensions\jebbs.plantuml-2.13.11) and
everything is perfect now.

thanks a lot.
