### ISSUE TITLE
[Question] Why is image quality of preview is much better than exported diagram?

### ISSUE THREAD

**Issue by stfsy** [qjebbs/vscode-plantuml#347]
I have noticed that the exported png diagrams have a much lower quality, than the previewed diagrams. Why is that? I'm using v2.13.13 of vscode-plantuml, the integrated plantuml.jar, and local render.

On the left you see the exported diagram, on the right you see the vscode preview. 

![image](https://user-images.githubusercontent.com/2894615/94790219-462a6400-03d6-11eb-969c-e5794cf60690.png)

**Comment by stfsy** [comment]
I used costum colors in the previous screenshot. here's one with default colors:

![image](https://user-images.githubusercontent.com/2894615/94790851-2b0c2400-03d7-11eb-83da-6a5b3aec575a.png)

Here's the code:

```
@startuml medium

left to right direction

rectangle User {
    rectangle id as "id : uuid" {

    }
    rectangle name as "name : encrypt(string)" {

    }
    rectangle email as "email : encrypt(string)" {

    }
}


@enduml
```

**Comment by qjebbs** [comment]
It’s simple, preview uses svg instead of png. You can export to svg to get same quality.

**Comment by stfsy** [comment]
Thank you 🙂
