### ISSUE TITLE
Nested !include not working

### ISSUE THREAD

**Issue by chrsch** [qjebbs/vscode-plantuml#348]
Given Scenario:
Diagram-A.puml
Diagram-B.puml
Diagram-C.puml

Diagram-A includes Diagram-B which includes Diagram-C.

On rendering Diagram-A with ALT-D Diagram-B is embedded correctly but Diagram-C is not rendered - But if Diagram-B is rendered on its own using ALT-D Diagram-C is embedded correctly. 

I would expect Diagram-B and the subsequently included Diagram-C are rendered correctly when rendering Diagram-A.

**Comment by qjebbs** [comment]
You may need to provide more information to reproduce:
- settings: where did it happen, Local render or Server
- codes
