### ISSUE TITLE
How to update embedded plantUML Jar?

### ISSUE THREAD

**Issue by leth** [qjebbs/vscode-plantuml#349]
How do you update the embedded plantUML jar file?

I'd like to upgrade to take advantage of the fix mentioned here: https://forum.plantuml.net/11606/full-opacity-alpha-compositing-support-for-svg-and-png for SVG/PNG transparency!

**Comment by qjebbs** [comment]
Before the extension update its embedded jar, you can change the user settings of `plantuml.jar` to use your own copy, and update it at your own pace
