### ISSUE TITLE
About PLANTUML_LIMIT_SIZE.

### ISSUE THREAD

**Issue by HrsYsn** [qjebbs/vscode-plantuml#35]
Hi,

When I had tried to display large diagrams and to export, the image was only partially displayed.
I found that the upper limit of the output size of the image is written in PlantUML FAQ.
http://plantuml.com/faq
But I could not understand how to change it on this plugin.

Could anyone add explanations or functions to deal with it?

Thanks.

**Comment by qjebbs** [comment]
In next release, you can config like:
```
"plantuml.commandArgs": [
     "-DPLANTUML_LIMIT_SIZE=8192"
]
```
