### ISSUE TITLE
Export diagrams to same folder as source file

### ISSUE THREAD

**Issue by janhieber** [qjebbs/vscode-plantuml#352]
Can I somehow get it to export diagrams in the exact same folder?

So when my source is:
`some/folder/sequene_diagram.wsd`
that the output is then:
`some/folder/sequene_diagram.png`

**Comment by qjebbs** [comment]
"plantuml.exportSubFolder": false

**Comment by janhieber** [comment]
Got it, additionally setting the exportOutDir to "." did the trick.
Thanks!
