### ISSUE TITLE
Can not generate preview any longer

### ISSUE THREAD

**Issue by moehlone** [qjebbs/vscode-plantuml#353]
Hi,

I recently updated to WSL2 and are using VSCode with a remote environment (Ubuntu-20.04).

Updated VSCode itself to 1.50.1, PlantUML plugin version is v2.13.14,

This is the preview result now:

![28-10-_2020_14-10-06](https://user-images.githubusercontent.com/5398340/97440446-c4235180-1927-11eb-96c7-9ba8641d81e3.png)

An export of the diagram works just fine.

- gd and graphviz is installed via linuxbrew
- VSCode information
    ```
    Version: 1.50.1 (user setup)
    Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
    Date: 2020-10-13T15:06:15.712Z
   Electron: 9.2.1
   Chrome: 83.0.4103.122
   Node.js: 12.14.1
    V8: 8.3.110.13-electron.0
   OS: Windows_NT x64 10.0.18363
   ```
- no errors within developer tools

Do you have any hints? Thanks!

**Comment by asos-robbell** [comment]
I'm having a similar issue after updating VS Code, but I get no preview tab whatsoever. As above, there's no output in the dev logs, and I can still export images successfully using the extension.

**Comment by clipka** [comment]
Same for me (on Windows), export does not work as well.

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Preview just says: "Cannot find java!
If you've installed java, please add java bin path to PATH environment variable.
Or, configure java executable path with "plantuml.java"."

**Comment by lefig** [comment]
Same here. What do you think please?

**Comment by ntmggr** [comment]
Experiencing the same with

VSCode: Version: 1.51.1
PlantUML extension 1.8.1
It does not work also with external server rendering

**Comment by qjebbs** [comment]
1.81？You downloaded the old, unmaintained fork of `NG PlantUML`(not by me)... The current version is 2.13.16

😅😅😅😅😅
