### ISSUE TITLE
Corrupted SVG with some characters like 🔌

### ISSUE THREAD

**Issue by bflorat** [qjebbs/vscode-plantuml#354]
vscode-plantuml 2.13.14
VSCode 1.50.1
Ubuntu

```
@startuml
        A -> B : "🔌 text"
@enduml
```

-> PNG rendering with vscode-plantuml is OK, SVG with vscode-plantuml is rendered without error but is corrupted (see attachment) :
[diag.zip](https://github.com/qjebbs/vscode-plantuml/files/5478192/diag.zip)

Note: No problem with the last plantuml standalone jar (the SVG  is OK):
```
java -jar ~/Downloads/plantuml.jar -tsvg diag.puml
```
Result : 
[diag_ok.zip](https://github.com/qjebbs/vscode-plantuml/files/5478207/diag_ok.zip)

Note 2 : no problem with some others unicode symbols like ⎚. 
🔌 is the only character I found with this issue.

**Comment by qjebbs** [comment]
It's not the extension, but the upstream `plantuml.jar` who generate the svg, consider post an issue to plantuml forumn.

**Comment by qjebbs** [comment]
It's not the extension, but the upstream `plantuml.jar` who generate the svg, consider post an issue to plantuml forumn.
