### ISSUE TITLE
Extension cannot find java when absolute path set in plantuml.java

### ISSUE THREAD

**Issue by DeltaRazero** [qjebbs/vscode-plantuml#355]
After the latest update (v2.13.15) the extension is no longer able to find the java executable whenever the absolute path is set with the ``plantuml.java`` setting.
Extra information: I'm running VSCode 1.51 and my java installation is OpenJDK 15.

**Comment by atomsfat** [comment]
I got the same problem on OS X

the installation was done using the following commands:
```
brew install graphviz
sdk install java 14.0.2-zulu
```
I can confirm that the Path contains the Java bin.

I tried to set the java binary using the plantuml.java  setting but that doesn't work, seems that for osx it will use https://github.com/qjebbs/vscode-plantuml/blob/cb4b53f22d456424a913a9010db0afe377283acf/src/plantuml/tools.ts#L162

think that it will fail also if you use `brew install openjdk`  to install java

it will suggest to  rely on the full path  and  adding logic to support  $JAVA_HOME env variable

**Comment by qjebbs** [comment]
@DeltaRazero  There's a bug error checking 'java' command for absolute path setting. Should've fixed.

@atomsfat The extension checks for `java` command (In `PATH`) only, no other additional logic applied here, like  `$JAVA_HOME`, to not make things complicated.

That is, `java` command, or java executable path.

**Comment by DeltaRazero** [comment]
Can confirm my problem has been fixed, thanks! Closing this issue.

**Comment by atomsfat** [comment]
I can confirm that putting the full path for Java, works on osx, thanks
