### ISSUE TITLE
Diagram does not generate in VS code

### ISSUE THREAD

**Issue by UTPALBHATT** [qjebbs/vscode-plantuml#359]
The error is:
Error: write EPIPE
	at afterWriteDispatched (internal/stream_base_commons.js:146:25)
	at writeGeneric (internal/stream_base_commons.js:137:3)
	at Socket._writeGeneric (net.js:696:11)
	at Socket._write (net.js:708:8)
	at doWrite (_stream_writable.js:417:12)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at c:\Users\XXXXX\.vscode\extensions\jebbs.plantuml-2.13.16\out\src\plantuml\renders\local.js:112:35

any inputs?

**Comment by ignatshilov** [comment]
Go to settings in PlantUML plugin and find
Plantuml: Jar
Alternate plantuml.jar location. Leave it blank to use integrated jar.

set it to something like C:\JavaThirdParty\PlantUML\plantuml.jar

You can get plantuml.jar from official plantuml site.

**Comment by UTPALBHATT** [comment]
This is the current content of the settings.json file:

{
    "workbench.colorTheme": "Default Light+",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "plantuml.exportFormat": "svg",
    "plantuml.java": "C:\\Program Files\\Java\\jdk1.8.0_202\\bin",
    **"plantuml.jar": "C:\\AAAA\\plantUML\\plantuml.jar",**
    "JAVA_HOME": "C:\\Program Files\\Java\\jdk1.8.0_202",
}
is it correct?

It is still not working actually.

**Comment by ignatshilov** [comment]
I actually set plantuml.java to just java.exe, as environment variable has been setup by java installer. here is my json:
    "plantuml.java": "java.exe",
    "plantuml.jar": "C:\\JavaThirdParty\\PlantUML\\plantuml.jar",
    "plantuml.previewSnapIndicators": true

**Comment by UTPALBHATT** [comment]
Let me try.
I used Atom and it worked perfectly

**Comment by qjebbs** [comment]
@UTPALBHATT 
"plantuml.java": "C:\\Program Files\\Java\\jdk1.8.0_202\\bin\\java.exe",

**Comment by UTPALBHATT** [comment]
Yes, it worked:
{
    "workbench.colorTheme": "Default Light+",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "plantuml.exportFormat": "svg",
    "plantuml.java": "C:\\Program Files\\Java\\jdk1.8.0_202\\bin\\java.exe",
    "window.zoomLevel": 1,
    "plantuml.jar": "C:\\ABCD\\plantUML\\plantuml.jar",
    "plantuml.previewSnapIndicators": true
}

many many thanks!!

**Comment by skalolaskovy** [comment]
I had problem with rendering. I changed render-server to plantuml.com. Local server doen't want to render :(((
Ref.: https://skalolaskovy.ru/analytics/65-system-analytics/603-vs-code-does-not-generate-diagram (russian lang.)
