### ISSUE TITLE
Update embedded JAR 

### ISSUE THREAD

**Issue by eladeyal-intel** [qjebbs/vscode-plantuml#361]
I think the embedded JAR is PlantUML v1.2020.18

Starting with PlantUML v1.2020.21, the JAR includes a minimal GraphViz deployment, so if you upgrade the embedded JAR to a newer version, then the perquisite for GraphViz can be removed.

> If you use a recent version (that is at least version 1.2020.21), you don't need to manually install GraphViz anymore !
> A minimalistic graphviz dot.exe is packed into PlantUML and will be automagically unzipped in some temporary folder if needed (that is, if no installed GraphViz is available).
> This is really the prefered option under Windows.
> 

source: https://plantuml.com/graphviz-dot

**Comment by qjebbs** [comment]
pls update

**Comment by eladeyal-intel** [comment]
@qjebbs thanks this works great!

I guess the perquisite for GraphViz in README.md can be deleted now
