### ISSUE TITLE
Can't render following image

### ISSUE THREAD

**Issue by Yavari** [qjebbs/vscode-plantuml#363]
This code works on the [server ](http://www.plantuml.com/plantuml/uml/ut8eBaaiAYdDpU4gIaqkISnBpqbL0B4C5QAvR6qXJ2uzFQxgQYu51OIIlDJYajGKGonYHborjLonN0wfUIb0Km40)but is not rendered using the plugin.

```
@startuml
rectangle rect1 [
== rect1
..
{{
  rectangle nested1
  rectangle nested2
}}
]
@enduml
```

![bild](https://user-images.githubusercontent.com/1221772/103088840-60966700-45ec-11eb-9cc6-5bba01357944.png)

**Comment by qjebbs** [comment]
That's because the output of your specific diagram lacks `<?xml version="1.0" encoding="UTF-8" standalone="no"?>`, while others not. I don't know why `PlantUML` behaves different between different diagrams.

I've change the detecting method to bypass it.

**Comment by Yavari** [comment]
Thank you. That was fast. I am looking forward to test this in the next release.
