### ISSUE TITLE
Copy diagram to clipboard

### ISSUE THREAD

**Issue by eladeyal-intel** [qjebbs/vscode-plantuml#364]
I wish there was an easy way to copy the diagram (from the preview windows) to clipboard so it can be pasted where needed.

**Comment by qjebbs** [comment]
welcome PR

**Comment by visma-kimhjortholm** [comment]
It's possible to pass diagram info in the URL, try  this example http://www.plantuml.com/plantuml/png/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

**Comment by fuhrmanator** [comment]
Duplicate of #288 ?
