### ISSUE TITLE
any thoughts on supporting json display?

### ISSUE THREAD

**Issue by LucasDove** [qjebbs/vscode-plantuml#365]
as what is described in [here](https://plantuml.com/en/json)，plantuml can display json string in a more visible and beautiful way. I am now using v2.14.1 and find it cannot draw the json diagram(correct me if I am wrong). 

I have donated by Alipay, hope you guys can make it a better exetension. And I'm really loving it

**Comment by qjebbs** [comment]
If you're using
- server render, it's already supported
- local render, before I update the embedded jar(if not updated to support), you can download & use latest jar with `plantuml.jar` setting

![image](https://user-images.githubusercontent.com/16953333/103398943-bf725800-4b79-11eb-91d7-af7422f0b5bc.png)

See also: [Use PlantUML Server as Render](https://github.com/qjebbs/vscode-plantuml#use-plantuml-server-as-render)

**Comment by LucasDove** [comment]
thanks!
