### ISSUE TITLE
state diagram not working 

### ISSUE THREAD

**Issue by peter-zyj** [qjebbs/vscode-plantuml#367]
![image](https://user-images.githubusercontent.com/5926142/104823196-50456680-57fd-11eb-9411-6cc8c66d97fc.png)

**Comment by visma-kimhjortholm** [comment]
Do you have any diagram working?

Error text indicates you miss Graphviz installed 
See requirement for PlantUML extension

Note; unless you call a PlantUML server you will need all required components for Plantuml installed, e.g. java and Graphviz

**Comment by peter-zyj** [comment]
thanks

________________________________
