### ISSUE TITLE
`java.lang.IllegalStateException` in new version

### ISSUE THREAD

**Issue by matthid** [qjebbs/vscode-plantuml#368]
## Description

On any puml file for example a simple:
```puml
@startuml
state "Test State" as Test
@enduml
```

yields to:

![image](https://user-images.githubusercontent.com/1866463/104845295-e7c9b880-58d4-11eb-919d-c0f07204ba27.png)

```
java.lang.IllegalStateException
  net.sourceforge.plantuml.svek.DotStringFactory.solve(DotStringFactory.java:356)
```

## Workaround:

Disable the integrated `plantuml.jar` version and use the one from choco (just like before the update):

```batch
choco install plantuml
```

```json
{
  "plantuml.jar": "C:\\ProgramData\\chocolatey\\lib\\plantuml\\tools\\plantuml.jar"
}
```

**Comment by visma-kimhjortholm** [comment]
See https://github.com/esteinberg/plantuml4idea/issues/204

**PlantUML limits image width and height to 4096. There is a environment variable that you can set to override this limit: PLANTUML_LIMIT_SIZE.** You have to define this variable before launching PlantUML, something like:
set PLANTUML_LIMIT_SIZE=8192 or setenv PLANTUML_LIMIT_SIZE 8192
Another way is an option in the command line:
java -DPLANTUML_LIMIT_SIZE=8192 -jar /path/to/plantuml.jar ...
Note that if you generate very big diagrams, (for example, something like 20 000 x 10 000 pixels), you can have some memory issues. The solution is to add this parameter to the java vm : -Xmx1024m.

**Comment by qjebbs** [comment]
looks like I need to update the embedded jar
