### ISSUE TITLE
Duplicated metadata in PNG?

### ISSUE THREAD

**Issue by zoulja** [qjebbs/vscode-plantuml#370]
Hello good sir!
**Environment:** Windows 10, VS Code 1.52.1, PlantUML extension 2.14.1

**Steps:**
1. Create sequence diagram
2. 'Export Current Diagram' to PNG
3. Press Ctrl+n to create new empty file in VS Code
4. Press F1->Choose 'Extract PlantUML Diagram Source from Image' and select file from step 2.

**Expected result:**
Initial diagram can be extracted and result matches initial diagram

**Actual result:**
Initial diagram can be extracted, but data is duplicated (extracted/displayed twice)

I'm 99% sure it's baseline issue, but could you please confirm it (because I can't submit VS Code issues on PlanUML forum directly) and if possible give some inputs how to explain it to PlanUML developers?

Thanks a lot!

**Comment by qjebbs** [comment]
Several points:
- The extension just helps you work with `plantuml.jar`
- Since you have get the extracted, the extension has done its job
- Sorry, I don't have java installed now, cannot reproduce it

please post your result to  https://forum.plantuml.net/:

```
java -jar platnuml.jar -metadata path/to/your.png
```
