### ISSUE TITLE
!include file works only with full path in Markdown

### ISSUE THREAD

**Issue by Samback** [qjebbs/vscode-plantuml#375]
Hi there,
I've spent almost a day to resolve this issue... but didn't find correct answer.

So, what I have.
I've create a file with my styles that I want to apply at all of my diagrams.
So I'm expecting to have something like this:

```plantuml
@startuml
!include PlantUMLConfig.txt
@enduml
```

It's perfectly works on preview but when I switch to my markdown file where I wanna see my diagrams it shows me an error that 
`cannot include PlantUMLConfig.txt`

when I change 

`!include PlantUMLConfig.txt `-> `!include fullPath/PlantUMLConfig.txt`

everything works fine

I was trying to add folder path at 

`"plantuml.includepaths"`
 also 
 `"plantuml.commandArgs": ["-I/fullpath"]`
`"plantuml.includes": ["fullPath"]`

 But nothing works for me ..
 
 So my question is: Where and how I should put path to my config file?
 
 Regards,
 Max

**Comment by qjebbs** [comment]
![image](https://user-images.githubusercontent.com/16953333/106739781-7cae0f00-6654-11eb-8f24-e84b8557b88a.png)

Works fine here. You should first save md file, until then plantuml knows where to resolve relative paths

**Comment by Samback** [comment]
I've next file 

```
skinparam backgroundColor white
skinparam handwritten false
autonumber "<b>[000]</b>"
actor Customer
participant JBDevice
database Portal
participant Service
skinparam sequence {
    ArrowColor  #00f6ff
    ActorBorderColor #00f6ff
    LifeLineBorderColor #0e2b79
    LifeLineBackgroundColor #A9DCDF

    ParticipantBorderColor #00f6ff
    ParticipantBackgroundColor #0e2b79
    ParticipantFontName Arial
    ParticipantFontSize 17
    ParticipantFontColor white

    ActorBackgroundColor #0e2b79
    ActorFontColor #989fb0
    ActorFontSize 17
    ActorFontName Arial
}
```
I was trying *.txt and *.iuml

Here is an example of my script 

```
```plantuml
@startuml
!include inc.iuml
  JBDevice -> Customer : Detect user
  Customer -> Customer : Check for notifications at local db
  alt find push notification info for current shop 
  Customer -> Customer : generate push notification from local DB
  Customer -> Customer : show push notification on display
  end
@enduml
```

And as a result I've next message on preview.
https://prnt.sc/y5ap5a

**Comment by qjebbs** [comment]
Oh, I see. Basically it's a technical limitation:

- The extension contributes a plugin to VSCode markdown engine
- The engine doesn't tell the plugin any information about where the diagram is located
- So the plugin doesn't know where to resolve relative paths

You have find the solution, use absolute paths instead.

**Comment by qjebbs** [comment]
Just made a small improvement, you will be able to add & apply `includepaths` in global settings for your case with next release:
```
   "plantuml.includepaths": [
        "path/to/global_includes"
    ]
```
> workspace setting is not an option because we don't know where the diagram come from in markdown.

**Comment by Samback** [comment]
That would be great @qjebbs!
Temporary I will use full path and when release gonna be available on vs code, will try to check how it works and response you about results.

P.S.: Is it possible to have a new release on the near furure?

**Comment by qjebbs** [comment]
Yes, it has been released.

**Comment by Samback** [comment]
@qjebbs  it's only 2.14.2 available for me 
https://prnt.sc/y9oayr
And based on git info it seems the same version now marked as new one.

**Comment by Samback** [comment]
> Just made a small improvement, you will be able to add & apply `includepaths` in global settings for your case with next release:
> 
> ```
>    "plantuml.includepaths": [
>         "/absolute/path/to/global_includes"
>     ]
> ```
> 
> > workspace setting is not an option because we don't know where the diagram come from in markdown.
One more question:
What do you mean when you say : global_includes ?
Is is some special things or it could be just my folder with my project where I'm storing my configs that I show you previously ?

**Comment by qjebbs** [comment]
Yes, it's your folder

**Comment by qjebbs** [comment]
Looks like a publish failure, pls try update again.

**Comment by Samback** [comment]
Yes! Now everything works fine! 
Thx for help!

**Comment by Samback** [comment]
@qjebbs one more question. 
Now everything works perfectly but when I push on gitlab and open my *.md file it shows me that it can't to !include <full path on my local mac>
Where I can find solution of this issue?

Regards,
Max

**Comment by qjebbs** [comment]
> @qjebbs one more question.
> Now everything works perfectly but when I push on gitlab and open my *.md file it shows me that it can't to !include 
> Where I can find solution of this issue?
> 
> Regards,
> Max

No，unless that markdown plugin supports include

**Comment by Samback** [comment]
Hmm,

Is there any solution for workaround this issue?

**Comment by jaques-sam** [comment]
Funny also that this works:
```json
    "plantuml.includepaths": [
        "/home/samja/repos/tcs/confero-architecture/plantuml"
    ],
```
But not 
```json
    "plantuml.includepaths": [
        "${workspaceFolder}/plantuml"
    ],
```
