### ISSUE TITLE
The plantuml.jarArgs config not working.

### ISSUE THREAD

**Issue by xiangjihan** [qjebbs/vscode-plantuml#378]
I am using plantuml-stdlib/C4-PlantUML for C4 model. They asked for additional configuration to use the local include files.
https://github.com/plantuml-stdlib/C4-PlantUML#getting-started
But it does not work for me, how did I How do I deal with this configuration item?
{
    "editor.fontSize": 18,
    "files.autoSave": "afterDelay",
    "graphvizPreview.engine": "dot",
    "graphvizPreview.dotPath": "D:\\Program Files\\Graphviz2.38\\bin\\dot.exe",
    "plantuml.includepaths": [
    ],
    "plantuml.urlFormat": "png",
    "plantuml.previewSnapIndicators": true,
    "plantuml.jarArgs": [
        "-DRELATIVE_INCLUDE= \".\""
    ],
    "plantuml.jar": "D:\\Program Files\\plantuml\\plantuml\\plantuml.jar"
}
![微信截图_20210224151653](https://user-images.githubusercontent.com/3070542/108962218-67f0f400-76b3-11eb-8ae2-af305d3daf19.png)

**Comment by qjebbs** [comment]
https://github.com/qjebbs/vscode-plantuml#extension-settings

`plantuml.commandArgs`: commandArgs allows you add command arguments to java command, such as` -DPLANTUML_LIMIT_SIZE=8192`.
