### ISSUE TITLE
Renders on viewing another file, despite plantuml.previewAutoUpdate set to false

### ISSUE THREAD

**Issue by chipbite** [qjebbs/vscode-plantuml#381]
Hi!
Plugin renders when another file is viewed (e g by switching tabs), even if previewAutoUpdate is set to false.
`"plantuml.previewAutoUpdate": false`
AFAICS/IMO autoupdate should not happen, unless it is manually invoked. This enables one to look at other files, return to the diagram, and not have the preview nervously re-render, or rather even more detrimental; render another image.
![image](https://user-images.githubusercontent.com/559199/111039356-f85a6300-842d-11eb-827e-38df74ef393d.png)

Great extension, thanks!
BR! /marcus

**Comment by qjebbs** [comment]
confirmed, thanks
