### ISSUE TITLE
Extracted Diagram Source from Image has wrong encoding

### ISSUE THREAD

**Issue by evilru** [qjebbs/vscode-plantuml#383]
Take the following [Diagram](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhBprVGjLD8IYnIi598p2zLSFGFLJYyvF2smtiK3hSSddPuZiBX-OUsSZcavgK0rGC0) and extract the source on the command line:

```bash
java -Dfile.encoding=UTF-8 -jar plantuml.jar -metadata diagram.png > back_to_text.txt
```
output
```plantuml
------------------------
diagram.png

@startuml

foo -> bar : aou AOU äöü ÄÖÜ ßµ

@enduml

PlantUML version 1.2021.00(Sun Jan 10 11:25:05 CET 2021)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: US

------------------------

```
now do the same with the vscode extension using the same jar and set the encoding in settings.json

```json
{
    "plantuml.jar": "somepath\\plantuml.jar",
    "plantuml.commandArgs": [
    "-Dfile.encoding=UTF-8"
    ]
}
```

```plantuml
------------------------
pathtofile\diagram.png

@startuml

foo -> bar : aou AOU ��� ��� ߵ

@enduml

PlantUML version 1.2021.00(Sun Jan 10 11:25:05 CET 2021)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: US

------------------------

```

**Comment by qjebbs** [comment]
cannot reproduce here, neither with nor without `commandArgs `.

**Comment by evilru** [comment]
It works in a docker container but not on Windows - just verified it.

Just created a pull request for a fix.

**Comment by evilru** [comment]
So it looks like this as a Windows problem.
I thought it the pull request I just closed would fix it, but it would break it on Linux.

Maybe I will find time later this week to continue on this.
