### ISSUE TITLE
Picked up _JAVA_OPTIONS is treated as error

### ISSUE THREAD

**Issue by eladeyal-intel** [qjebbs/vscode-plantuml#384]
If the environment variable _JAVA_OPTIONS is set (for example for setting proxies), then the java runner starts with outputting this to stderr:

```
$ _JAVA_OPTIONS=-Dwhataver java
Picked up _JAVA_OPTIONS: -Dwhataver
[...]
```

It seems that this sentence is captured by the plugin  and yields an error icon

![image](https://user-images.githubusercontent.com/20379005/112514879-6f80e700-8d9e-11eb-9815-70b2742f1f80.png)

A quick google suggests there's no way to suppress this message.

It would be good if the line `Picked up _JAVA_OPTIONS=...`  is not treated as an error.

**Comment by qjebbs** [comment]
It's the plantuml.jar (upstream) not the extension who output messages to stderr, nothing to do from this side, pls report to upstream.

**Comment by eladeyal-intel** [comment]
@qjebbs to the best of my knowledge, it is the java runtime which outputs `Picked up _JAVA_OPTIONS=...` and it does so for every jar (not specifically related to `plantuml.jar`) so there's not a lot we can do about that.

It seems the decision to treat anything on stderr as an error indication, while surely make sense, it is unhelpful in this deployment type.

**Comment by eladeyal-intel** [comment]
@qjebbs can you reopen this ticket please? See my comment above.

I think I see here https://github.com/qjebbs/vscode-plantuml/blob/2e6864d7a75b6143c396522e1b4f8b6035f7f4f5/src/plantuml/renders/processWrapper.ts#L34 that there is some special treatment to the stderr string `JAVA_TOOL_OPTIONS` ; so we need the same thing for `_JAVA_OPTIONS`. that would be very handy.

From looking at the aforementioned code it seems that it will ignore all stderr if `JAVA_TOOL_OPTIONS` is mentioned? Not sure if I understand this correctly. I think the proper action would be to delete the offending lines only and still look at the rest of the output, to identify errors.

**Comment by qjebbs** [comment]
@eladeyal-intel Yes, it ignores all if match. PR is welcome.
