### ISSUE TITLE
Is it possible to scale the PNG output?

### ISSUE THREAD

**Issue by nikoladev** [qjebbs/vscode-plantuml#390]
First, thanks for creating this extension. It's great!

---

Is it possible to scale the PNG output? What I mean is that at the default size the PNG can be hard to read and gets blurry when zooming in.

Would it be possible to export the PNG at other sizes? For example, here's a 10x10 pixel square exported at 1x, 4x, and 10x:

![square-1x](https://user-images.githubusercontent.com/15011519/113754694-c7f5a400-970f-11eb-9f1e-5be6859b81cc.png)
![square-4x](https://user-images.githubusercontent.com/15011519/113754697-c926d100-970f-11eb-88a7-fa14fd3816d1.png)
![square-10x](https://user-images.githubusercontent.com/15011519/113754699-c926d100-970f-11eb-8671-d652423211c5.png)

Having an option to export scaled PNGs would be great.

I'm already using SVG as my standard output format because it is great for zooming in. But not all applications accept SVG files.

If scaled PNGs are not possible with PlantUML, would someone know a workaround?

**Comment by fuhrmanator** [comment]
PlantUML has a `scale 50` command which will make the diagram 50 times bigger, for example. E.g., http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIfEJin9LJ0ru4hEIImkLd1KgEPAiihCA-6gvN98pKi1AW40

**Comment by nikoladev** [comment]
@fuhrmanator This is great, thanks!

Ideally I would like to set it conditionally only for PNGs, but that's just me being nitpicky. Thanks so much!
