### ISSUE TITLE
jarArgs is not working correctly

### ISSUE THREAD

**Issue by IshmaelHeathcliff** [qjebbs/vscode-plantuml#398]
it works without jarArgs.

it works in powershell with the command:
```
java -jar D:\Apps\plantuml.jar .\Character.plantuml  -config plantuml.config
```

my vscode settings:

![Screenshot 2021-05-17 170140](https://user-images.githubusercontent.com/19368812/118462941-c9b07f80-b731-11eb-9b03-99762bf5ffbf.jpg)

error:

![Screenshot 2021-05-17 170209](https://user-images.githubusercontent.com/19368812/118462928-c6b58f00-b731-11eb-9589-f497f87556d6.jpg)

---

it works with the jarArgs bellow:

![Screenshot 2021-05-17 172517](https://user-images.githubusercontent.com/19368812/118465875-eac69f80-b734-11eb-98dc-7e8cfe5ab20c.jpg)

???????

**Comment by qjebbs** [comment]
Wrong settings, use

```
["-config", "plantuml.config"]
```

**Comment by IshmaelHeathcliff** [comment]
> Wrong settings, use
> 
> ```
> ["-config", "plantuml.config"]
> ```

Thanks. 

The description should be updated.
