### ISSUE TITLE
Cannot export Diagrams on macOS

### ISSUE THREAD

**Issue by khacminh** [qjebbs/vscode-plantuml#4]
### Description:
On my machine, all requirements are met:

- `Java` : Platform for PlantUML running.
- `Graphviz` : PlantUML requires it to calculate positions in diagram.
- `PlantUML` : Download and place it in extension root folder.

I can show diagrams on PlantUML Preview. The generate URLs functions (`Generate URL for Current Diagram`, `Generate URLs for Current File Diagrams`) can work perfectly. However, I **cannot export diagrams** (using functions: `Export Current Diagram`, `Export Current File Diagrams`, `Export Workspace Diagrams`). After selecting export function and export file format, **nothing happens**.

**Comment by qjebbs** [comment]
Did you just open a file and have no folder open? If so, this is a known bug, solved, but I haven't publish this fix yet. Open the folder which containing that file will avoid this bug and also is a recommend way for this plugin.

**Comment by khacminh** [comment]
Hi qjebbs,

I've just checked it. As you say, open the folder containing the file will avoid the bug. However, i got the bug `UnsupportedOperationException` for following export file format: pdf, xmi, scxml, and html. The svg exported file cannot be opened by Adobe Illustrator. Should I open new issue for this bug?

**Comment by qjebbs** [comment]
For PDF, please see https://github.com/qjebbs/vscode-plantuml/issues/3

Those errors are related to PlantUML implemention. There is nothing I can do. Sorry.

**Comment by khacminh** [comment]
So, should I close this issue, or leave it until your next release?

**Comment by qjebbs** [comment]
I will close it after I release the fix. Thank you.

**Comment by qjebbs** [comment]
fixed in 1.2.1
