### ISSUE TITLE
Doesn't support multipage diagrams

### ISSUE THREAD

**Issue by locobrain** [qjebbs/vscode-plantuml#40]
Like atom plantuml plugin, supports multipage diagrams.
newpage within @startuml/@enduml
Multiple @startuml/@enduml within file
Combinations of both
Thanks

**Comment by qjebbs** [comment]
Please see https://github.com/qjebbs/vscode-plantuml/issues/1, `stdout` cannot stream multiple files, the atom plugin may export files unmanaged, and I don't want do that.

**Comment by qjebbs** [comment]
Multi-Page support is ready, but wait for the new release of `plantuml.jar`
http://plantuml.sourceforge.net/qa/?qa=6265/specify-page-when-use-stdout

**Comment by locobrain** [comment]
Thank your gread job
