### ISSUE TITLE
cannot priview Class Diagram 

### ISSUE THREAD

**Issue by wust-hm** [qjebbs/vscode-plantuml#401]
my environment:
- win10 10.0.19041.985
- plantuml 2.14.5
- vscode 1.52.1

this is my code:
```
@startuml
class A
@enduml
```

if i just write one class, it works well. 
![QQ截图20210525175204](https://user-images.githubusercontent.com/44540316/119484609-c5671080-bd88-11eb-90f1-e510ca7f7f2a.png)

if i add a new class, like:
```
@startuml
class A
class B
@enduml
```
then it will cause error
![QQ截图20210525175239](https://user-images.githubusercontent.com/44540316/119484560-baac7b80-bd88-11eb-8c74-5bc324c49581.png)

i have installed Graphviz, and the executable path is correct:
this is my environment variable
![QQ截图20210525184444](https://user-images.githubusercontent.com/44540316/119485145-4faf7480-bd89-11eb-932f-d9db1b4692ad.png)

i just set the `plantuml.commandArgs`
![QQ截图20210525184556](https://user-images.githubusercontent.com/44540316/119485336-84233080-bd89-11eb-9727-a66bba9674a9.png)
it failed too

**Comment by fuhrmanator** [comment]
What happens if you try the small example for testdot as suggested?

**Comment by wust-hm** [comment]
**thanks , i have solve this problem**

If i try testdot, it shows
![QQ截图20210526203726](https://user-images.githubusercontent.com/44540316/119661801-3f6bc800-be63-11eb-8dd5-ccb2098ad6dd.png)

I have tried to set the system enviroment variable to "D:\Program Files\Graphviz\bin\dot.exe"
![QQ截图20210526204108](https://user-images.githubusercontent.com/44540316/119661374-d1bf9c00-be62-11eb-87b1-ed9507b8ef3e.png)
but it seems still have this problem.  However after i add this change in **setting.json**
 evetything becomes ok !!!
![QQ截图20210526203842](https://user-images.githubusercontent.com/44540316/119664402-df2a5580-be65-11eb-8a86-62998948d874.png)

![QQ截图20210526203852](https://user-images.githubusercontent.com/44540316/119662356-df295600-be63-11eb-9557-8fa510ffaecd.png)

![QQ截图20210526205027](https://user-images.githubusercontent.com/44540316/119662483-08e27d00-be64-11eb-8934-5304bc6cc831.png)

it seems has nothing to do with the system environment variable,  and can't read the path from system environment. It just read the path from **setting.json** file. 

I try this in another computer haven't installed Graphviz. and i don't change the **setting.json** file. It means i don't add the "-DGRAPHVIZ_DOT=xxx\dot.exe" param. But it has no problem and works well. I don't know others have this problem too .
