### ISSUE TITLE
PlantUML Theme

### ISSUE THREAD

**Issue by mptnt1988** [qjebbs/vscode-plantuml#404]
PlantUML supports [theme](https://plantuml.com/theme) as of v1.2021.6
https://github.com/plantuml/plantuml/tree/v1.2021.6/themes

Are you guys going to update it?

**Comment by qjebbs** [comment]
pls update. next time you can use `plantuml.jar` setting.

**Comment by henrycjchen** [comment]
it seems the theme of vscode-plantuml is not as the same as the official website's. 
`version v2.16.1`
![image](https://user-images.githubusercontent.com/9553319/143026375-8263d27f-6b0c-4aa1-9fe7-4b4654131ab8.png)
