### ISSUE TITLE
VSCode PlantUML extension includes old PlantUML version

### ISSUE THREAD

**Issue by 0n3d3r3r** [qjebbs/vscode-plantuml#407]
Hi!

The plantuml.jar version included (1.2021.0) in the current VSCode extension (2.14.5) is quite old. Is there a way you could update it to PlantUML 1.2021.7 and release it? Because of company restrictions I cannot download and install a local version of PlantUML or access the internet server.

Thanks.

**Comment by agrexgh** [comment]
@0n3d3r3r  I agree with you.

@qjebbs Could you make vs code extension to follow latest Plant UML version automatically?

**Comment by iljapostnovs** [comment]
Hi,

I would vote very much for this as well.
Mainly because of new !theme feature, which makes look the diagrams fantastic :)

**Comment by qjebbs** [comment]
pls update to latest

**Comment by agrexgh** [comment]
@qjebbs 
> pls update to latest

Latest version works! Thanks a lot!!

**Comment by PolarGoose** [comment]
As a workaround you can update it manually:
- Download the latest `plantuml.jar` from https://plantuml.com/download
- Replace it with the one located in `%UserProfile%\.vscode\extensions\jebbs.plantuml-2.15.1`

**Comment by drupol** [comment]
What I did is to download the latest `plantuml.jar`, then, in the VSCode extension setting, I manually set the path to that file and it works.

@qjebbs could you please do something?

**Comment by iajCai** [comment]
@valentinmk 
I also have this question, but I don't know how to set.
Could you get me more info about setting?
by the way, I have downloaded the latest version.

**Comment by valentinmk** [comment]
@iajCai 
Inside extantion folder `~/.vscode/extensions/jebbs.plantuml-{version number}` rename exiting `plantuml.jar` file to i.e. `plantunl.jar_orig` and copy a downloaded one (make sure it is called `plantuml.jar`)

**Comment by rashtapu** [comment]
Easiest way to update is to edit settings of your extension from VS Code, and include the external plantuml.jar location. Download the latest jar from plantuml.com/downloads
