### ISSUE TITLE
Chocolatey installation 

### ISSUE THREAD

**Issue by majkinetor** [qjebbs/vscode-plantuml#42]
It would be good to mention chocolatey installation of plantuml as of way to install it

https://chocolatey.org/packages/plantuml

I maintain the package always [up to date](https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1#plantuml)

You cold even detect chocolaty installation and set it to use its jar by default if present. The location is

`$Env:ChocolateyInstall\lib\plantuml\tools\plantuml.jar`

The benefit is that choco package installs dependencies, reference guide and keeps it up to date.

**Comment by qjebbs** [comment]
With pleasure. Could you write a MD instruction of how to install dependencies with `Chocolatey`? Since I haven't ever use it.

**Comment by majkinetor** [comment]
You don't install dependencies, just a tool: `cinst plantuml`. That will install deps shown on package page:

```
Dependencies
  javaruntime (≥ 6.0.30)
  graphviz (≥ 2.38.0.1)
  chocolatey (≥ 0.10.3)
  chocolatey-core.extension (≥ 1.3)
```

It will also add them to path and so on... Core extension is needed to create desktop shortcut to plantuml, download manual etc.

This assumes chocolatey itself is installed: `https://chocolatey.org/install.ps1 | iex` (in admin shell)

**Comment by qjebbs** [comment]
Firstly, I should have `chocolatey` installed, so I type the command:
```
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```
then I get an error of script is forbidden or something and failed. 

`chocolatey` is a new thing to me or many users like me. I should introduce `chocolatey` to plugin user only when it shorten the time or steps to install dependencies. Not just give them a link, and let them encounter similar problem like what I do right now. That's why I ask you write a detailed instruction.

**Comment by majkinetor** [comment]
You probably have an older windows and you run installer from the Powershell. In that case you need to explicitly allow Powershell script execution. This is what it states on install page:

> Run Get-ExecutionPolicy. If it returns Restricted, then run Set-ExecutionPolicy AllSigned or Set-ExecutionPolicy Bypass.

> chocolatey is a new thing to me or many users like me

I think its out of scope of this project to tutorialize on chocolatey installation. Its eneugh to write something like this:

---

The easiest way to correctly setup plantuml along with its dependencies is via [chocolatey](https://chocolatey.org/) plantuml [package](https://chocolatey.org/packages/plantuml): 
``` 
choco install plantuml
```

**Comment by qjebbs** [comment]
For users who don't use chocolatey,  setting up chocolatey also counts as steps, I should make sure chocolatey way has less steps and easier to understand. If user is trapped in setting up chocolatey, why don't they just download JAVA and DOT, and install them with two double-clicks.

PS: I use lateset win10 (1703)

**Comment by ferventcoder** [comment]
Hi @qjebbs when you look over https://chocolatey.org/install, are you seeing something there that you would suggest we change?

**Comment by qjebbs** [comment]
@ferventcoder No, it is pretty detailed but I missed this part when I was facing the large installation guide:
```
run Set-ExecutionPolicy AllSigned or Set-ExecutionPolicy Bypass.
```
That remind me that if I introduce new concepts to the install guide, it would bring new issues, misunderstandings, etc. 

I test it in virtual machine again, and decide to introduce the choco install way.
