### ISSUE TITLE
Github C4-PlantUML syntax highlighting 

### ISSUE THREAD

**Issue by kirchsth** [qjebbs/vscode-plantuml#428]
I tried to use PlantUML code highlight on Github with my C4 models, but only @startuml is highlighted. E.g.

````
```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml

!include <office/Servers/database_server>
!include <office/Servers/file_server>
!include <office/Servers/application_server>
!include <office/Concepts/service_application>
!include <office/Concepts/firewall>

AddExternalPersonTag("anonymous_ext", $sprite="osa_user_black_hat", $legendText="anonymous user")
AddPersonTag("customer", $sprite="osa_user_large_group", $legendText="aggregated user")
AddPersonTag("admin", $sprite="osa_user_audit,color=red", $legendSprite="osa_user_audit,scale=0.25,color=red", $legendText="administration user")
...
```
```` 

```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml

!include <office/Servers/database_server>
!include <office/Servers/file_server>
!include <office/Servers/application_server>
!include <office/Concepts/service_application>
!include <office/Concepts/firewall>

AddExternalPersonTag("anonymous_ext", $sprite="osa_user_black_hat", $legendText="anonymous user")
AddPersonTag("customer", $sprite="osa_user_large_group", $legendText="aggregated user")
AddPersonTag("admin", $sprite="osa_user_audit,color=red", $legendSprite="osa_user_audit,scale=0.25,color=red", $legendText="administration user")
...
```

(Full sample is [here](https://github.com/plantuml-stdlib/C4-PlantUML/pull/173))

Is it possible to support all macros (!include, ...), procedures, functions, arguments... too? 

Or did I something completely wrong?

Thank you and best regards
Helmut

**Comment by kirchsth** [comment]
I tried it with "Visual Studio Code" and "PlantUML - jebbs.plantuml v.2.15.1" and this version shows more details like 

![grafik](https://user-images.githubusercontent.com/21959385/128633063-cf6bcaea-1aa2-46da-b69b-143e3556cac2.png)

Could it be that a GitHub update is missing?

Thank you and best regards
Helmut

**Comment by The-Lum** [comment]
Hello @kirchsth,

FYI, I have open a question for this issue on Linguist here:
- github/linguist#5530

And for:
> Is it possible to support all macros (!include, ...), **procedures, functions, arguments... too**?

I created this first commit on (qjebbs/vscode-plantuml):
- https://github.com/qjebbs/vscode-plantuml/pull/425/commits/5d9a8e8c0b5f4c40688c33ee9b59e5a6c5edf31f
