### ISSUE TITLE
Add toolbar icon to show/hide Preview

### ISSUE THREAD

**Issue by H-G-Hristov** [qjebbs/vscode-plantuml#431]
Please, add icon similar to Markdown Preview icon to show and hide the preview as an alternative to `alt + D` shortcut.

![Screen Shot 2021-08-18 at 11 51 30 AM](https://user-images.githubusercontent.com/47526411/129868485-35f471ee-b4f3-4ae9-bf4a-7f55c3208014.png)

**Comment by dirk-thomas** [comment]
This would really be a nice enhancement. The [Graphviz Interactive Preview](https://marketplace.visualstudio.com/items?itemName=tintinweb.graphviz-interactive-preview) extension has a similar icon: https://user-images.githubusercontent.com/2865694/155575303-8c429902-5599-47cf-855f-c9694a32b829.png
