### ISSUE TITLE
Markdown plantumlcode doesn't render the code

### ISSUE THREAD

**Issue by estyxx** [qjebbs/vscode-plantuml#455]
👋

Running on Mac OS, version v2.16.0 

In the preview the diagram is shown even when the the syntax is `plantumlcode`, and should be rendered as code with highlighting... 

![CleanShot 2021-11-17 at 20 50 32](https://user-images.githubusercontent.com/28976199/142281292-8d36d893-6559-4950-ba22-279bf8f0054b.png)

**Comment by qjebbs** [comment]
The fence info detect is fixed, but plantuml code highlight in rendered is never provided so far, welcome PR.
