### ISSUE TITLE
Maintain zoom level after autoupdate

### ISSUE THREAD

**Issue by dannief** [qjebbs/vscode-plantuml#46]
First, great extension. Really grateful to you for providing it. I see where we have a new feature to be able to zoom the preview image. I just have one problem with this. Whenever the preview auto updates, the preview image reverts to the fitting its width to the preview pane, which effectively reduces the size (**Edit: I have a wide as against a long diagram**). I have to zoom again to see my change. Is it possible to add a setting to maintain the current zoom level after update? Or have the option for the image to be displayed at the actually size by default?

Thanks.

**Comment by qjebbs** [comment]
Display at actually size doesn't really fix your problem. The HTML page refreshing is what happens when preview updates, it resets both zoom and position. The key to solve this, is to find a way that plugin can communicate with the scripts inside preview page, but I haven't found one.

**Comment by qjebbs** [comment]
I found the way~

**Comment by dannief** [comment]
Great! Thanks for the prompt response. Looking forward to the fix.

**Comment by ybbus** [comment]
Hi.

@qjebbs 
Is there something I have to configure?
For me it is still resetting the zoom after auto-refresh.

Best,
Alex
