### ISSUE TITLE
"buf.slice is not a function" when trying to preview a diagram

### ISSUE THREAD

**Issue by sandersaares** [qjebbs/vscode-plantuml#472]
Fresh install of VSCode and PlantUML, first diagram I tried to make.

```
TypeError: buf.slice is not a function
	at c:\Users\sasaares\.vscode\extensions\jebbs.plantuml-2.17.1\out\src\providers\previewer.js:163:37
	at Array.reduce (<anonymous>)
	at task.promise.then.task (c:\Users\sasaares\.vscode\extensions\jebbs.plantuml-2.17.1\out\src\providers\previewer.js:161:38)
```

```
@startuml

rectangle "foo"

@enduml
```

CPUs | Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 127.81GB (104.85GB free)
Process Argv | --crash-reporter-id 9fad5318-d047-4495-9593-da4f1851c726
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
githistory | don | 0.6.19
xml | Dot | 2.5.1
EditorConfig | Edi | 0.16.4
markdown-table-formatter | fcr | 2.2.4
plantuml | jeb | 2.17.1
cmake-tools | ms- | 1.9.2
powershell | ms- | 2021.12.0
cmake | twx | 0.0.17

**Comment by jadams2305** [comment]
Same problem here. Downgrading to 2.17.0 worked for me.

**Comment by jducobu** [comment]
Same for me. Please fix it asap
