### ISSUE TITLE
Inconsistent filenames

### ISSUE THREAD

**Issue by sandersaares** [qjebbs/vscode-plantuml#48]
There are some magic numbers in my exported diagram filenames, e.g. `DependencyGraph@1-61.png`. These numbers seem to change. This means I cannot reference my diagrams via URL. That's obviously bad.

I want to have static filenames without any special stuff at the end.

**Comment by qjebbs** [comment]
The plugin designed to manage multiple diagrams in one file. You may say file names like `DependencyGraph-1.png`, `DependencyGraph-2.png` (by diagram index in file)  are more consistent, but how about insert diagram to file? Indexes changed.

So the plugin's behavior, scale-up the problem, encourages people to name every diagram.

You can name the diagram when diagram starts (Recommends).
```
@startuml diagram name
sudoku
@enduml
```

Or, give it a title
```
@startuml
title diagram name
a->b: message
@enduml
```

PS: It's not magic numbers, but the start-end line number of the diagram.

**Comment by sandersaares** [comment]
Aha, thank you for a comprehensive answer! The ability to name the diagram solves my problem very nicely.

**Comment by qjebbs** [comment]
Glad it helps ^_^
