### ISSUE TITLE
Markdown always renders from a server, even if local is set in the settings

### ISSUE THREAD

**Issue by ironsm4sh** [qjebbs/vscode-plantuml#494]
When rendering Markdown, this extension will always use the server set in `plantuml.server`, even if `plantuml.render` is set to `"Local"`.
This is unexpected behaviour, and a potential privacy risk.

**Comment by qjebbs** [comment]
1. the Markdown core doesn't support local render, so it always use server render
1. `plantuml.server` default is empty, if you add some server, it means you trust it

**Comment by ironsm4sh** [comment]
Ok, this was not clear to me.
