### ISSUE TITLE
set a specific URL 

### ISSUE THREAD

**Issue by Volkan-Lord-Of-Fire** [qjebbs/vscode-plantuml#5]
The last update with the generating URLs is nice! 
But I miss the function to choose a specific URL like:

www.plantuml.com/example_uml_sequenz_dia_whatever

and every time I update my UML it will be saved on this special URL.

Or a rule

www.plantuml.com/[title]_[autor]_[date]_[nameFromTheUML]

proplaby you will need a passphrase so you can't overwrite other UMLs.

**Comment by qjebbs** [comment]
Thank you for your idea, but it's not the way it works. Your diagram is compressed & base64 encoded into the URL, it is not upload your diagram to server and give it a name. Server doesn't store any data, but generate every time you visit the URL. But your way asks to store diagrams and causes other problems.

Anyway, this server is built by PlantUML library author, I cannot change its behavior. Sorry..
