### ISSUE TITLE
Once fork and mutl-time end fork

### ISSUE THREAD

**Issue by locobrain** [qjebbs/vscode-plantuml#50]
How to describe once fork and mutl-time end fork, like fllow link
[https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.xml#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Flocobrain%2Fdraw%2Fmaster%2FUntitled%2520Diagram.xml](url)

Copy paste to browse to open

**Comment by qjebbs** [comment]
hmm..this is beyond the scope of plugin development, you should ask plantuml author here:
http://plantuml.sourceforge.net/qa/
