### ISSUE TITLE
Support VsCode color theme in render output 

### ISSUE THREAD

**Issue by wirecat** [qjebbs/vscode-plantuml#52]
Not sure if it is possible, but it would be great if the extension could potentially use the color theme currently in use to set the background of the PlantUML Preview. When running a dark theme, that sea of white is glaring.

If at all possible, I would be willing to help if pointed in the right direction.

**Comment by wirecat** [comment]
In case someone else wants a quick & dirty fix. You can update the body.background-color element in templates/preview.html to change the background color of the render window. I changed mine to #303030 to make it easier on my eyes.

**Comment by qjebbs** [comment]
Yes, it's possible, just remove background color style of body in templates, and set `"plantuml.previewFileType": "svg"`.

I intentionally make the background white, because PlantUML is designed to generate white-background images, which makes the preview most consistent with output.

And, with black background, some diagram elements are less recognizable compares to white.

For your concern, I consider to add an option `plantuml.previewForceBackgroundWhite`, then you can:
```
"plantuml.previewForceBackgroundWhite": false,
"plantuml.previewFileType": "svg"
```
PS: Besides "less recognizable", svg type not support all diagrams.

**Comment by qjebbs** [comment]
![qq 20170727101033](https://user-images.githubusercontent.com/16953333/28651373-13f9ad30-72b4-11e7-8898-7b721713b532.png)

To what I said "less recognizable"

**Comment by qjebbs** [comment]
kind of, be solved with new preview since 2.7.0.

**Comment by claudio-salvio** [comment]
Hello, @qjebbs  

Currently many of **my PlantUML diagrams work quite well with both light and dark background**.
As I see it the key elements to achieve this are the use of:
```plantuml
skinparam BackGroundColor transparent
```
and the fact that I usually customize the styling of the diagrams heavily.
For the latter I find the use of `%reverse_hsluv_color` very useful.

Normally, I edit diagrams in **VSCode** with **dark background**.
Unfortunately, in my case, **the configuration detailed previously in this issue does not work**:
```
"plantuml.previewForceBackgroundWhite": false.
```
**The preview always shows white background.**

It is worth noting that the export works correctly. I usually do it in **svg** and the generated files are displayed well on both light and dark background.

Please let me know if you think it is necessary for me to generate a new issue.

**Thank you very much for sharing with the community this excellent plugin.**

Best regards,
Claudio Salvio

**Comment by qjebbs** [comment]
@claudio-salvio  Thanks for your idea, but sorry, I don't use much PlantUML in recently months or years. I wish someone else who has the first-hand experience can add new features for it, while I cannot catch up with latest updates

So welcome PR.
