### ISSUE TITLE
Syntax highlight not working for custom extensions

### ISSUE THREAD

**Issue by lflserg** [qjebbs/vscode-plantuml#53]
Syntax highlight not working for other then built-in extensions. Adding to fileExtension setting does nothing to this. Maybe I am doing something wrong or this feature is not implemented?

**Comment by qjebbs** [comment]
fileExtension setting is the exts to search in the workspace for export, it's nothing to do with syntax highlight. Sadly, there's no way to highlight plantuml code inside .java file (for example).
