### ISSUE TITLE
Preview not working, but executing from cmd yes.

### ISSUE THREAD

**Issue by fazaldegui** [qjebbs/vscode-plantuml#54]
Hello,
The "Preview Current Diagram" is not working. I create a test file like this: "Untitled-1.wsd"
```plantuml
@startuml
 Alice->Bob:test
@enduml
```
Then I execute the command in Visual Studio Code by pressing Ctrl+Shift+P y choose "PlantUML: Preview Current Diagram". A preview panel in the Side is opening and I can see a progress bar that says "Processing" for a few seconds, then an icon of broken image appear.
But If I open a cmd console and execute:
> java -jar C:\Users\XXXXX\\.vscode\extensions\jebbs.plantuml-2.1.1\plantuml.jar -verbose Untitled-1.wsd

A png is generate correctly.

I've tried to change the property "plantuml.previewFileType" to "svg", but no luck, same happen.
How can I see what is happen? Any clue?

Thank you.

**Comment by qjebbs** [comment]
I cannot reproduce it, can you tell what errors do you see which may relevant to it in console of development tool?

**Comment by fazaldegui** [comment]
I guess that the console development tool is the console that appears with "Developer: Toggle Developer Tools".
This console shows the following:

> shell.ts:423 Cannot read property 'document' of undefined: TypeError: Cannot read property 
> 'document' of undefined
>     at vscode.workspace.onDidChangeTextDocument.e (C:\Users\96952\.vscode\extensions\jebbs.plantuml-2.1.1\out\src\providers\previewer.js:200:53)
>     at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:55038)
>     at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:56829)
>     at t.$acceptModelChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:346011)
>     at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
>     at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
>     at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> e.onUnexpectedError @ shell.ts:423
> (anonymous) @ shell.ts:383
> e.onUnexpectedError @ errors.ts:119
> o @ errors.ts:139
> t.onUnexpectedExtHostError @ mainThreadErrors.ts:13
> e.handle @ abstractThreadService.ts:34
> s @ ipcRemoteCom.ts:275
> f @ ipcRemoteCom.ts:231
> _combinedTickCallback @ internal/process/next_tick.js:67
> _tickCallback @ internal/process/next_tick.js:98

I see that the "previewer.js:200:53" file is about "activeTextEditor". If it helps I do the following: I've opened the "Untitled-1.wsd" and the cursor is beetwen the "@startuml" and "@enduml", then I call the command "PlantUML: Preview Current Diagram".

If I can get more information in any other way tell me, an a user of Code and I don't know the debugging or development tools.

Thank you for your time.

**Comment by fazaldegui** [comment]
Sorry I close by accident...

**Comment by qjebbs** [comment]
I still cannot reproduce, but made some changes to code according to you error report. Try update to v2.1.2, see if it's solved or not.

**Comment by fazaldegui** [comment]
Updated. Now it work but only with svg:     "plantuml.previewFileType": "svg"
If I change to "png" the preview fails and now I can't see nothing about plantuml in the console developer.
For me is enought this solution (using svg) so you can close de issue but if you want to try another thing to see why png is not working I'm yours ;)

**Comment by qjebbs** [comment]
It's weird. What's the VSCode Version, X86 or 64? What's your OS and version?

**Comment by fazaldegui** [comment]
VSCode 64-bits
Windows 7 Pro. 64-bits

**Comment by qjebbs** [comment]
I tried in win7 with VM, but still can't reproduce your problem. Maybe we should wait for further information.

**Comment by fazaldegui** [comment]
Ok.
I close the issue and if I have more information I'll reopen it.
Thank you very much for your time :)

**Comment by qjebbs** [comment]
You are welcome

**Comment by qjebbs** [comment]
@edobez I need more information to debug, please try to find any error msg in console, when it fails.
