### ISSUE TITLE
feature request: option to export at same folder of file 

### ISSUE THREAD

**Issue by alanlivio** [qjebbs/vscode-plantuml#540]
Today the extension has the options `plantuml.diagramsRoot` and `plantuml.exportOutDir`, but none enable export in the same folder of the file. 

Therefore, I suggest that change the  `plantuml.diagramsRoot` to accept the value `${fileWorkspaceFolder}` (as defined [here](https://code.visualstudio.com/docs/editor/variables-reference)) while the  `plantuml.exportOutDir` continue with same semantics related to the root.

**Comment by claudio-salvio** [comment]
Hello @alanlivio 

In my `settings.json` files I have the following related lines that I think affect the behavior of this extension:
```json
     "Plantuml.exportoutdir": "."
     "Plantuml.exportsubfolder": false,
     "Plantuml.PreviewFiletype": "SVG",
     "Plantuml.PreviewForcebackGroundwhite": false,
```
With this configuration the exported files are in the same folder as the corresponding PUML file.

Greetings,
Claudio Salvio

**Comment by alanlivio** [comment]
Thank you, @claudio-salvio. Indeed the  code below worked.

```json
  "plantuml.exportOutDir": ".",
  "plantuml.exportSubFolder": false,
```
