### ISSUE TITLE
Support Preview Clipboard copy

### ISSUE THREAD

**Issue by dannyrdavis** [qjebbs/vscode-plantuml#55]
Great extension, thanks - I use it every day.

Just wondered if it would be possible to support copying the preview image to allow pasting straight into Word? 

At the moment I export to a SVG file, preview in the browser, copy, then paste. This gives great quality but would be a lot easier if the copy could be done from within the preview. It would also avoid exporting a lot of files.

**Comment by qjebbs** [comment]
I haven't found a way which is capable to copy images in Win, Linux, and Mac.

**Comment by samageza** [comment]
I have a similar workflow, but I've optimised it by exporting the diagrams as PNG and then just dragging and dropping the png into the correct place in the doc. This is a quicker flow than the one @dannyrdavis describes and works well for my needs.

If you're bulk importing into word, then you've got a different headache. Perhaps you can script the import of the png's into the doc if it happens frequently. Or perhaps you have move to a markdown-based doc that embeds the plantuml and export the markdown as a doc?

Let us know how/if you improved the workflow.

**Comment by fazaldegui** [comment]
Just for you know, there is already a Word plugin that generates the diagram from a PlantUML file.
http://plantuml.com/word
Normally I write the plantuml file in VS Code, and when I happy with it, justo insert or link the file into word and the addin generates the diagram for you.
In this way, if you link the file into the Word document, all changes do to the plantuml file will be automatically translated to the word diagram.

**Comment by flyisland** [comment]
> would be a lot easier if the copy could be done from within the preview

+1

**Comment by dannyrdavis** [comment]
In the end I switched to IntelliJ IDEA. The Plantuml plugin works much better for me as it supports copy and paste.
