### ISSUE TITLE
Blockdiag support in PlantUML

### ISSUE THREAD

**Issue by tomigaprv** [qjebbs/vscode-plantuml#57]
Hello,
First of all thank for great plugin. It really makes life easier :)

I have a question which maybe is a bit out of scope PlantUML plugin but maybe based on this one it is possible to make a bit more general tool for visualization of different languages similar to PlantUML.

While UML is quite powerful not always it is the best language to describe some kind of diagrams. More logical one block diagrams are not well supported there.

But there is similar language which work on similar base concept it is called **blockdiag**
Details can be found: `http://blockdiag.com/en/blockdiag/index.html`

The idea is similar we have text base language which can generate block diagrams.

Question is if it was possible (and not too complicated) to embaded in PlantUML also support for Blockdiag sytax and visualization.

I know that it is a bit out of scope of original idea but to have one common plugin would be very handfull.

Regards
Tomiga

**Comment by qjebbs** [comment]
I believe that most codes are still applicable if we start a new project for `blockdiag` from this. We only have to change the render, diagram extracting, and syntax highlight parts should be enough. The key point is, I don't use `blockdiag` , and maybe won't in the foreseeable future. I cannot keep refining it in daily use, which make it not as good as this one.

So I hope someone who really use `blockdiag`  would do this job, either fork from this (which is welcome), or start a brand new project for better thoughts.

**Comment by tomigaprv** [comment]
Ok, I understand. Thank you for quick feedback.
