### ISSUE TITLE
Unable to render plantuml previews with picoweb - "Error: 302 Found" with v2.18.0

### ISSUE THREAD

**Issue by alyandon** [qjebbs/vscode-plantuml#579]
I use a local plantuml picoweb instance and have the extension configured to use that and I'm unable to render plantuml previews in VSCode with v.2.18.0 of the extension as it appears to consider anything other than a 200 response as an error.  Version 2.17.6 works for me.

```
Error: 302 Found

GET http://localhost:8080/map/0/...
at ClientRequest.closeCallback (/Users/[REMOVED_FOR_PRIVACY]/.vscode/extensions/jebbs.plantuml-2.18.0/out/src/plantuml/renders/httpWrapper.js:78:27)
at ClientRequest.emit (node:events:514:28)
at ClientRequest.emit (node:domain:489:12)
at Socket.socketCloseListener (node:_http_client:464:9)
at Socket.emit (node:events:526:35)
at Socket.emit (node:domain:489:12)
at TCP. (node:net:323:12)
```

**Comment by rolfmadsen** [comment]
Same experience and error message.

Works fine with 2.17.6 using Dot version: dot - graphviz version 2.43.0 (0) and plantuml-gplv2-1.2024.3.

**Comment by mawid6** [comment]
Same issue here. I was about to blame IT that they are messing with the port security of the machine, but then I checked and pico is running fine.

How do I downgrade btw?

**Comment by NenadSteric** [comment]
can confirm the issue with a local plantuml jar 
(if you change to [plantuml.com](https://www.plantuml.com/plantuml) as the server it works also with the latest version) 
and the workaround by downgrading to 2.17.6

**Comment by Zamotic** [comment]
Can confirm that upgrading to 2.18.1 resolved the issue. Thanks!
