### ISSUE TITLE
Simple export names

### ISSUE THREAD

**Issue by wolf99** [qjebbs/vscode-plantuml#58]
More of a feature request or a question than an issue.

I guess the names and directory structure used when doing a simple export is handy for larger web-based projects. In other more simple uses though, for example a single diagram file that is intended to produce a single image, the names and directories are pretty unwieldy.

Is there already some setting, or could ones be added to allow an export to take the name of the wsd file and placed either in the same directory or alternatively directly within the `out` directory?

For example, suppose I make a test UML class diagram named `Bar Class Diagram.wsd` like: 
```
@startuml

abstract class BarBase {
    +{abstract}Field:bool
    +{abstract}Method():int
}

class BarDerived {
    +Field:bool
    +Method():int
}

BarBase <|-down- BarDerived

@enduml
```

And then export to *.png. the exported file would be `./Bar Class Diagram.png` (or at the least be ./out/Bar Class Diagram.png`. Instead of being the current `./out/Bar Class Diagram/Bar Class Diagram@1-15.png`

**Comment by qjebbs** [comment]
See https://github.com/qjebbs/vscode-plantuml/issues/48

**Comment by qjebbs** [comment]
Added diagnosis in case someone ignores naming and name problems

![image](https://user-images.githubusercontent.com/16953333/30105320-cd04745e-932a-11e7-81f4-f6adeb863cb9.png)

**Comment by wolf99** [comment]
@qjebbs Thanks that's great, it's *part* of what I was getting at. Now the output for my class's class diagram will be in:
```
./out/MyClass Class Diagram File Name/MyClass Class Diagram Title.png
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I guess this sub-directory structure is used for the case where there are multiple diagrams in a single file? 
If I tend to only have one diagram per file is there a way I can remove the sub-directory generation?

**Comment by qjebbs** [comment]
Sorry I didn't notice your message.

Yes. you can set this to false:
`plantuml.exportSubFolder`: export diagrams to a folder which has same name with host file.

**Comment by wolf99** [comment]
Awesome, thanks!

**Comment by edhacare** [comment]
[Hindistan'da Kemik İliği Nakli Maliyeti ](https://www.edhacare.com/tr/blogs/bone-marrow-transplant-cost-in-india/), bir dizi faktöre bağlı olarak geniş bir aralıkta değişebilir. Bu faktörler arasında naklin türü (otolog veya allojenik), hastane veya tıp merkezi, hastanın genel sağlığı ve işlem sırasında ortaya çıkabilecek herhangi bir komplikasyon bulunmaktadır.
