### ISSUE TITLE
Layout breaks when describing the connectors and using boundaries

### ISSUE THREAD

**Issue by Vratislav** [qjebbs/vscode-plantuml#6]
Layout breaks when previewing/exporting the diagram from the PlanUML documentation:

```
@startuml
left to right direction
skinparam packageStyle rectangle
actor customer
actor clerk
rectangle checkout {
  customer -- (checkout)
  (checkout) .> (payment) : include
  (help) .> (checkout) : extends
  (checkout) -- clerk
}
@enduml
```

The result has way too long connectors:
![bug 120-131](https://cloud.githubusercontent.com/assets/346066/23101880/914a59e8-f69e-11e6-8bd3-1cb156434952.png)

Rendering from the reference plant UML server looks like this:
![reference](http://s.plantuml.com/imgp/s3-use-case-diagram-014.png)

It happens only when connector description is used together with `rectangle` (or any other boundary) notation.

I am running MacOSX with the following software installed:

- PlantUML VSCode extension v1.2.3
- GraphViz installed thorugh homebrew v2.40.1
- PlantUML.jar Version 8056
- Java version build 1.8.0_65-b17
- VSCode version 1.9.0

Any help with this issue would be greatly appreciated.

Btw, thanks for the awesome extension. 👍

**Comment by qjebbs** [comment]
This issue is beyond plugin implementation. It's more likely a problem related to PlantUML.jar or GraphViz. 
To confirm that, you can try exporting outside vscode, to see if it's correct.

**Comment by qjebbs** [comment]
closed due to no more activities
