### ISSUE TITLE
Code formatting breaks indentation

### ISSUE THREAD

**Issue by biddster** [qjebbs/vscode-plantuml#60]
I'm having trouble with the code formatter. It's quite likely that it's another formatter I have installed within VSCode but I'm not sure how to debug. 

I have 'format on save' enabled and upon save, all the indentation in my plantuml file is removed. 

If I change the '.plantuml' and '.wdsd' file association to Text via settings.json then the formatting doesn't happen and the preview renders fine.

What's the best way for me to debug this?

**Comment by qjebbs** [comment]
What kind of indent you had and lost?

**Comment by biddster** [comment]
If we take a loop as the example, it's removing the loop inner block indentation. So every line gets aligned with the margin.

**Comment by qjebbs** [comment]
Do you mean while loop? I tested and following codes formatted as expected.
```
@startuml
start
repeat
    :read data;
    :generate diagrams;
repeat while (more data?)
stop
@enduml

@startuml
start
while (data available?)
    :read data;
    :generate diagrams;
endwhile
stop
@enduml
```

**Comment by biddster** [comment]
Those examples work fine for me too.

If I do this:
```
@startuml example
loop each Item
    Item->Item: I should be indented
end
@enduml
```
...it gets reformatted to this when I save...
```
@startuml example
loop each Item
Item->Item: I should be indented
end
@enduml
```
