### ISSUE TITLE
local render without internet connection is failing

### ISSUE THREAD

**Issue by nobody19** [qjebbs/vscode-plantuml#605]
When I'm working offline then the live preview from the plantuml is not working. I changed the plantuml.render to Local, installed also the latest JAVA, expecting that the in the extension included plantuml.jar is working. 

Did I some setting wrong or is it a bug?

My settings:

```.json
"plantuml.render": "Local",
"plantuml.java": "C:/Program Files/Java/jre1.8.0_431/bin/",
"plantuml.server": "",
"plantuml.previewAutoUpdate": true
```

VS Code: 1.95.3
PlantUML Simple Viewer: latest (2.17.5)

Thanks in advance for any help
nobody

**Comment by The-Lum** [comment]
Hi @nobody19,

- What is your `"plantuml.jar"` value?
- Could you add `"plantuml.jar"` value?
- Could you also change your `"plantuml.java"` value with the all path and java exe...

See also;
- #359
- #559
- #112

Regards,
Th.

**Comment by nobody19** [comment]
Hi @The-Lum 

Thanks a lot for your help now it is working. Sorry for creating the issue I thought I have tried everything out. At the end the problem was my settings and that I relied to much on the "integrated" plantuml.

Now my settings are:
```.json
    "plantuml.render": "Local",
    "plantuml.jar": "C:\\Tools\\plantuml\\plantuml-1.2024.8.jar",
    "plantuml.java": "C:\\Program Files\\Java\\jre1.8.0_431\\bin\\java.exe",
    "plantuml.server": "",
    "plantuml.previewAutoUpdate": true,
    "plantuml.exportFormat": "svg",
    "plantuml.previewSnapIndicators": true,
```
