### ISSUE TITLE
Preview cuts off and does not display the entire design.

### ISSUE THREAD

**Issue by dmarzan** [qjebbs/vscode-plantuml#61]
When the sequence diagram design is large, the preview cuts off after certain point (Two or three pages down)

**Comment by qjebbs** [comment]
I think the issue is of PlantUML instead of this plugin.
<http://plantuml.sourceforge.net/qa/?qa=4145/is-the-png-output-size-limited-to-4096-pixels-only>

**Comment by qjebbs** [comment]
Closed due to no more feedback, and it's not likely to be a bug.
