### ISSUE TITLE
Preview breaks when cursor is outside of start/end tags

### ISSUE THREAD

**Issue by widL** [qjebbs/vscode-plantuml#62]
The preview is broken when the text cursor is outside of the @startuml and @enduml tags in a source file. It says "No valid diagram found here!". I think this is very unintuitive behavior, if not a bug. It is quite common to have a blank line at the end of files, and this means that preview breaks if you happen to be on the last line of the file.

Ubuntu 16.04
VS Code 1.16.0

**Comment by JekRock** [comment]
Don't know why it's closed, but this is still an issue that causes lots of confusion.

**Comment by Ibrahim-Islam** [comment]
This is definitely an issue and quite confusing one to figure out at that
