### ISSUE TITLE
can't work on macOS high sierra Xcode

### ISSUE THREAD

**Issue by xujipm** [qjebbs/vscode-plantuml#67]
![image](https://user-images.githubusercontent.com/3202911/30909282-251619ba-a346-11e7-8619-f912205c8efe.png)

java has worked in safari
![image](https://user-images.githubusercontent.com/3202911/30909322-467bc960-a346-11e7-896f-ace6352e1e8e.png)

how to deal it

**Comment by qjebbs** [comment]
What message you can see when hover the RED WARING ICON?

**Comment by xujipm** [comment]
![image](https://user-images.githubusercontent.com/3202911/30970265-4de8d2c6-a42a-11e7-816a-974a910d3b9e.png)
@qjebbs java works well in safari

**Comment by qjebbs** [comment]
Try add it to PATH then. If everything's good, below cmd should work in terminal:
```
java -version
```

**Comment by xujipm** [comment]
where is PATH config on Mac?  I add PATH in /etc/profile, but it couldn't work

**Comment by qjebbs** [comment]
I don't use Mac. Google it, I believe there is a way.

**Comment by jonathanhuet** [comment]
Just add the same issue, you need to install the SDK, no the RE.
You can find it here http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html?ssSourceSiteId=otnes

**Comment by BoizZ** [comment]
I don't know why in macOS high Sierra very slow, probably 4-5 seconds to appear preview.
In windows inside soon.

**Comment by jonathanhuet** [comment]
I had the same slowness issue ( I can't compare because I have first installed this plugin in macOS HS ). I figured out by installing (super fast installation) the plantUML server in my personal server ( explained in the main page) and now it's almost instantaneous.

**Comment by qjebbs** [comment]
@BoizZ How about the speed that export in command line?

**Comment by BoizZ** [comment]
@qjebbs How to run in command line？😂

**Comment by qjebbs** [comment]
@BoizZ `java -jar path/to/plantuml.jar sequenceDiagram.wsd`

**Comment by BoizZ** [comment]
@qjebbs Not fast. I think in the docker to build a server will be faster
