### ISSUE TITLE
Export Current Diagram fails

### ISSUE THREAD

**Issue by Fellfalla** [qjebbs/vscode-plantuml#68]
The command  Export Current Diagram (`plantuml.exportCurrent`)  causes following exception on my machine:

```

TypeError: Path must be a string. Received [Function]
	at assertPath (path.js:7:11)
	at Object.isAbsolute (path.js:439:5)
	at Includer._calcIncludes (C:\Users\weber\.vscode\extensions\jebbs.plantuml-2.3.0\out\src\plantuml\diagram\includer.js:24:23)
	at Includer.addIncludes (C:\Users\weber\.vscode\extensions\jebbs.plantuml-2.3.0\out\src\plantuml\diagram\includer.js:11:18)
	at DiagramAt (C:\Users\weber\.vscode\extensions\jebbs.plantuml-2.3.0\out\src\plantuml\diagram\diagram.js:89:48)
	at Diagram.GetCurrent (C:\Users\weber\.vscode\extensions\jebbs.plantuml-2.3.0\out\src\plantuml\diagram\diagram.js:50:18)
	at Object.<anonymous> (C:\Users\weber\.vscode\extensions\jebbs.plantuml-2.3.0\out\src\plantuml\exporter\exportDocument.js:49:50)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\weber\.vscode\extensions\jebbs.plantuml-2.3.0\out\src\plantuml\exporter\exportDocument.js:4:58)
	at <anonymous>
```

the command `plantuml.preview` does not work either.

**Comment by qjebbs** [comment]
Do you config any invalid values in `plantuml.includes`?

**Comment by Fellfalla** [comment]
There are no includes in both, local and global settings.

`"plantuml.includes": [],`

**Comment by qjebbs** [comment]
I've no clue how it happens, How about config `"plantuml.includes": [""]`? how about re-install the plugin?

**Comment by Fellfalla** [comment]
`"plantuml.includes": [""]` makes no difference. Nor as reinstall.

**Comment by qjebbs** [comment]
Sorry, I cannot re-proceduce so I can't tell why. Does it only happen in this single machine? I doubt it has something to do with the environment. How about clear all globally installed npm package, and reinstall?

**Comment by Fellfalla** [comment]
I have no nodejs-lts packages installed and reinstalled nodejs.

Maybe you could try to reproduce by installing "vscode" and "nodejs-lts" with these commands:
First install chocolatey:
`@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"`

Then run these commands in the powershell or cmd:
`choco install visualstudiocode -y`
`choco install nodejs-lts -y`

**Comment by qjebbs** [comment]
I tried in VM with chocolatey, but still cannot reproduce.

**Comment by Fellfalla** [comment]
Maybe I could give you more log data somehow?

**Comment by qjebbs** [comment]
@Fellfalla I've located where the error occurs, but don't known how. If you could clone the project, and debug in your environment would be the best way out.

**Comment by c835722** [comment]
So let's try to advance bug as its a blocker for many but seem only a simple code fix will be required.
It happens for me on a Mac with vscode-insiders. It does not happen with vs-code. Is this issue (#68) specific to a version of vscode or the plugin? 
What other platforms are people seeing the issue on?
I assume from the comments here it cannot be reproduced on the windows platform. Is that correct? What is it about vscode that differs per platform that might suggest why the bug might be platform specific?
Is there a set of specific instruction on how to debug this plugin? 
I notice there are some high-level considerations in https://github.com/qjebbs/vscode-plantuml/blob/master/vsc-extension-quickstart.md which perhaps we could expand to a set of concrete instructions on how to get the code breakpointed at a particular line of code.

**Comment by c835722** [comment]
I backported all my plugins form vscode-insider to vscode.
This reproduced the same issue in vscode.
This suggests to me there is some type of clash between plugins.
This may be why it cannot be reproduced by some.

**Comment by c835722** [comment]
workaround found:
I found that if I disabled the [Spellcheck plugin](https://marketplace.visualstudio.com/items?itemName=ban.spellright) this issue is fixed for me in both vscode and vscode-insider. :smiley:
Can the author perhaps install the plugin and debug the clash? It may be that the bug is introduced completely by the Spellcheck plugin and the issue belongs in their repo.

**Comment by Fellfalla** [comment]
@c835722  That's it! Problem solved :). Thanks a lot.

**Comment by qjebbs** [comment]
@c835722 Thanks for figuring out how it occurs, that I could publish the fix soon. With next version, plugin should work with `Spellcheck plugin ` without error.

**Comment by qjebbs** [comment]
Basically, the fault is mine. `Spellcheck plugin` defines a function `inArray`  in `Array.prototype`, this kind of defines take effects globally for all plugins, that I get a function among strings (use `for...in`, which I shouldn't), and cause the problem.

Since every one may define inArray-like functions, it may cause conflicts & overrides. It's not recommended to do so, in my opinion.
