### ISSUE TITLE
Add a setting to disable @<start>-<end> file name suffix on export

### ISSUE THREAD

**Issue by pgatilov** [qjebbs/vscode-plantuml#69]
Hello,

It would be great to have a setting that disables addition of @<start>-<end> file name suffix for export. I know this is needed to support multiple diagrams in a single source file and is a great default behavior idea. However, it does not work very well with our workflow:

- We do not put multiple diagrams in a file yet (not sure if we will)
- We put exported diagrams into Atlassian Confluence
- Confluence tracks different versions of the same file uploaded into it and keeps change comments, which is helpful

So, the problem is with this version tracking. Since the default behavior makes file name dependent on the content, version tracking is inconsistent. Sometimes you get a new file with the same name and upload creates a new version of the existing file. Sometime you get a new file with a new name, and the version chain is broken, and you have to edit the article text to fix the link.

Right now we have to put diagram name after @startuml in each file to work around this.

We would like to be able to switch the behavior through config. For example, switch from current behavior to producing -<diagram number> suffix.

Thank you.

**Comment by qjebbs** [comment]
Currently, if no name is given to a diagram, it would be exported as `<filename>@<lineBegin>-<lineEnd>`, eg. `Untitled-1@1-10`. If I changed this behavior to `<filename>-<diagramIndex>`, eg:
```
fileName.png
fileName-1.png
fileName-2.png
...
```
This is also how the project PlantUML behaves, and doesn't require an addtional setting. Is it enough for your situation?

**Comment by pgatilov** [comment]
Yes, `<filename>-<diagramIndex>` would be enough for our use case.
