### ISSUE TITLE
Set jre home by settings

### ISSUE THREAD

**Issue by xinkunZ** [qjebbs/vscode-plantuml#72]
My pc have many jdk, and default jdk  in PATH is running as administrator, so I must run vscode as administrator too, it is not cool...
So, can you give a settings to set javaw.exe path for plantuml.jar??

**Comment by qjebbs** [comment]
Add a setting make the plugin behaves more complex to all users while only few users will encounter your situation. Can you install JDK for current account or figure out other ways?

**Comment by xinkunZ** [comment]
ok...😭
