### ISSUE TITLE
change the naming of the exported diagrams by a variable

### ISSUE THREAD

**Issue by FAMOSTester** [qjebbs/vscode-plantuml#75]
First of all: great work! The plugin in VSC is very helpful for my work.

One question: is it possilbe to change the naming of the exported diagram?
Actually the naming is taken from the "title". I want to have the name of the source file.
Maybe there could be a variable analogous to "plantuml.exportSubFolder": true, ...

Would be very helpful!

Greets Wolfgang

**Comment by qjebbs** [comment]
see https://github.com/qjebbs/vscode-plantuml/issues/58, https://github.com/qjebbs/vscode-plantuml/issues/48

**Comment by FAMOSTester** [comment]
Thanks a lot. Sorry that i found the answer not by myself.
--> This helped me: @startuml diagram name
because my "title" is formatted with HTML Tags and different form the name of the source file.

**Comment by qjebbs** [comment]
@FAMOSTester You are welcome.
