### ISSUE TITLE
Integrate plantuml detection into other languages

### ISSUE THREAD

**Issue by rowanG077** [qjebbs/vscode-plantuml#76]
Hello guys,

The feature I want is to be able to detect some kind of tahs like `@startuml` and `@enduml` tags in other languages and if the cursor is between those tags then we get a preview of the uml exactly like it is when using plantuml language.

I want to start working on it but I am new to creating plugins for visual studio code and don't know if this is possible at all. There are a few issues I have no clear idea about how to fix:

- In visual studio code there is no way to detect language within a language so syntax highlighting most likely won't be possible. There is an issue on the visual studio code repo open: https://github.com/Microsoft/vscode/issues/1751 but this has been open for a year allready so I wouldn't really wait for it.

- Detecting whether the cursor is within a plantuml tag. 

- When within plantuml tag strip of comments and show the resulting plantuml code in the preview window.

I would like to implement this but I would to know from one of you guys whether this is at all possible within this plugin.

**Comment by qjebbs** [comment]
It's works already since the initial release, but without highlights, snippets etc. support as you said.

**Comment by rowanG077** [comment]
I see that's awesome. For some reason it doesn't work for me though. If I type `alt+D` it opens the debug menu nothing is happening :/

**Comment by qjebbs** [comment]
I didn't encounter your problem, maybe you can change the key binding and see if it helps

**Comment by rowanG077** [comment]
It doesn't work for me. I rebind the combination to a new key and it works however I get an error while rendering. The same diagram works when I manually render it using plantuml.

![test](https://user-images.githubusercontent.com/7439756/32964160-8f835a9c-cbd2-11e7-854e-76208cb93dda.png)

**Comment by qjebbs** [comment]
Redirect to #81
