### ISSUE TITLE
Exporting image map along with png image??

### ISSUE THREAD

**Issue by kapilverma-udr** [qjebbs/vscode-plantuml#77]
support for exporting image map file (cmapx file)  generated by default from plantuml.jar from command line

**Comment by qjebbs** [comment]
There is some problems with `plantuml.jar` implemention.

- `-pipemap` doesn't suport multiple page diagram and not work with `-pipeimageindex`
- `-pipemap` still outputs "null" when the diagram got no image map data, that I cannot determine to create the cmapx file or not.

As result, the plugin always create cmapx files, and not work right with multi-page diagram. 

PS:

A further request could be support image map in preview, that user can click links in preview window, but according to my test:

- VSCode seems not allowing those links, no response when clicking.
- Image map is not compatible with zoom, zoom leads to link areas dislocation.

So link click in preview won't be implemented in the foreseeable future.

**Comment by arnaudroques** [comment]
Could you post here a simple example of non-working diagram ?
Thanks!

**Comment by LucLaf** [comment]
A sample source file and the result with %filenameNoExtension%  in the footer.

(https://user-images.githubusercontent.com/6849598/33224106-4088c000-d166-11e7-8d9b-6c0f91de3fdf.png)
[SSO OpenId Connect-Logout-V2.0-20171122.puml.txt](https://github.com/qjebbs/vscode-plantuml/files/1502544/SSO.OpenId.Connect-Logout-V2.0-20171122.puml.txt)

**Comment by arnaudroques** [comment]
Thanks but about non-working diagram, I was talking about cmap and multipage diagram (which is not the case of @LucLaf example I think)

**Comment by LucLaf** [comment]
Sorry I put an example for another thread!

**Comment by qjebbs** [comment]
@arnaudroques Please try this,

```
@startuml
participant Bob
Bob -> Alice : [[http://a.com]] hello
newpage
participant Bob
Bob <- Alice : [[http://b.com]] hello
@enduml
```
with `-pipemap` & `-pipeimageindex`, I get the cmapx as follow, but `a.com` and `b.com` are expected to be in two different cmapx files.

```
<map id="plantuml_map" name="plantuml_map">
<area shape="rect" id="id1" href="http://a.com" title="http://a.com" alt="" coords="50,51,132,66"/>
<area shape="rect" id="id2" href="http://b.com" title="http://b.com" alt="" coords="40,81,123,96"/>
</map>
```

**Comment by arnaudroques** [comment]
Last beta should support multiple page diagram now with `-pipemap `
http://beta.plantuml.net/plantuml.jar

Not sure about `-pipeimageindex`, could you try and tell us if it does not work ?

**Comment by qjebbs** [comment]
Thank you.

With latest beta, page 1 is good, both png and cmapx, but page 2 failed both:

```
INSIDE FOR net.sourceforge.plantuml.Url@16150369 http://a.com 0,0,0,0 50.5,51.24609375
INSIDE FOR net.sourceforge.plantuml.Url@16150369 http://a.com 50,51,50,51 132.5,66.556640625
REMOVING net.sourceforge.plantuml.Url@3932c79a http://b.com 0,0,0,0
REMOVING net.sourceforge.plantuml.Url@3932c79a http://b.com 0,0,0,0
REMOVING net.sourceforge.plantuml.Url@3932c79a http://b.com 0,0,0,0
```

**Comment by arnaudroques** [comment]
Ok. This should work better with last beta http://beta.plantuml.net/plantuml.jar

If you try

`cat test1.txt | java -jar plantuml.jar -pipeimageindex 1 -pipemap`

test1.txt beeing:

```
@startuml
Bob -> Alice : [[http://a.com]] hello
newpage
Bob <- Alice : [[http://b.com]] hello
@enduml
```

You should have:

```
<map id="plantuml_map" name="plantuml_map">
<area shape="rect" id="id1" href="http://b.com" title="http://b.com" alt="" coords="46,54,116,70"/>
</map>
```

Does it sound better for you ?

**Comment by qjebbs** [comment]
Yes, it works as expected! But render the simple diagram takes so much time than ever with this beta, is it all because of "beta"? ^_^

**Comment by arnaudroques** [comment]
No, it should no take more time than last official release.
Could you double-check this ?
You can use the `-verbose` flag that print time information and post them here (comparison between beta and last official release).
Thanks!

**Comment by qjebbs** [comment]
Sorry, it should be my misunderstanding. I calculated the time including both export png & cmapx (call jar 2 times), which two times longer.

BTW, regarding plantuml server, what parameter is similar to `-pipeimageindex`?

Thank you!
