### ISSUE TITLE
Auto preview fails. Plugin clash with Spell Right.

### ISSUE THREAD

**Issue by c835722** [qjebbs/vscode-plantuml#79]
Hello,
When I have the PlantUML plugin enabled and the [Spell Right ](https://github.com/bartosz-antosik/vscode-spellright) plugin enabled the preview feature of PlantUML no longer works.
This may be a similar issue to #68.

My vscode PlantuML User settings are as follows: 
  "plantuml.jar": "/usr/local/Cellar/plantuml/1.2017.19/libexec/plantuml.jar",
  "plantuml.render": "PlantUMLServer",
  "plantuml.server": "http://localhost:1608",
  "plantuml.previewFileType": "svg"

Step to reproduce.
Install PlantUML plugin
PlantUML preview works.
Install Spell Right plugin
PlantUML preview fails.

**Comment by qjebbs** [comment]
It works fine with Spell Right in my PC. Please make sure you've updated to v2.3.3. If error continues, paste error messages here (from console of development tool).

**Comment by c835722** [comment]
Looks like it may have been a transitional issue with my machine. Can no longer reproduce.
