### ISSUE TITLE
Plantuml within c++ comments isn't working correctly.

### ISSUE THREAD

**Issue by rowanG077** [qjebbs/vscode-plantuml#81]
According to my question here: https://github.com/qjebbs/vscode-plantuml/issues/76. Using plantuml within comment blocks should work. However I get an error while rendering. The same diagram works when I manually rendering it using plantuml.

![test](https://user-images.githubusercontent.com/7439756/33187482-34b698d0-d092-11e7-92c3-90ef49ec0cc8.png)

**Comment by qjebbs** [comment]
In that post, I piped the commented source to `plantuml.jar`  'as is':

```
// @startuml
// a -> b: test
// a -> d: test
// @enduml
```
`plantuml.jar` did the job that removing the leading `//`, not the plugin.  The plugin won't implement the similar logic again, which may cause conflicts.

I suggest you post this issue to `plantuml.jar` author.

**Comment by qjebbs** [comment]
![image](https://user-images.githubusercontent.com/16953333/40151164-e1ffe9ea-59b0-11e8-9953-089faf911ace.png)
tested good with latest release.

**Comment by franciscorba** [comment]
This issue has appeared again as said on issue #410.
