### ISSUE TITLE
Export without creating the entire path

### ISSUE THREAD

**Issue by ahorn42** [qjebbs/vscode-plantuml#82]
Hello,

it would be nice, to have the possibility to export diagrams without creating the entire path.

If I set the export folder to `diagrams\output` and have stored my diagrams at `diagrams\diag1.puml` I would expect the exported Diagram in `diagrams\output\diag1.png`, but currently it is `diagrams\output\diagrams\diag1.png`

**expected**
```
diagrams
    output
        diag1.png
    diag1.puml
```

**actual**
```
diagrams
    output
        diagrams
            diag1.png
    diag1.puml
```

In general both behaviours are usefull, but I would appreciate to choose via configuration if I want to export the folder structure or not.

I tried to implement it myself but the code was more complex than expected :-/ I hope some who is knowing the code can achieve this faster :)

best regards,
Andreas

**Comment by qjebbs** [comment]
You should:

```json
    "plantuml.exportOutDirName": "output",
    "plantuml.exportSubFolder": false,
```
