### ISSUE TITLE
Dot Executable: null

### ISSUE THREAD

**Issue by holden-s** [qjebbs/vscode-plantuml#86]
I am new to PlantUML in vs code. Thank you for your contribution!

I try to run an easy case but it reports error.

My case:
```
@startuml
class Demo
@enduml
```
![error_case](https://user-images.githubusercontent.com/12414450/33696479-5e89ba38-db3d-11e7-8d87-2daae7c0cd96.png)

Graphviz was installed.

vs code version: 1.18.1
PlantUML version: 2.3.3

Can you tell me why it does't work? Thanks

**Comment by qjebbs** [comment]
This message shows the plugin works fine, but `plantuml.jar` may have some problem with `Graphviz`. Make sure `Graphviz` is properly installed, and try export directly with `plantuml.jar` or as the tip `java -jar plantuml.jar -testdot`, if it still doesn't work, turn to [Plantuml Forum](http://forum.plantuml.net/) for help.
