### ISSUE TITLE
Feature request for "Export current folder diagrams"

### ISSUE THREAD

**Issue by wolf99** [qjebbs/vscode-plantuml#87]
With VS Code now supporting multi folder workspaces I can have several folders of UML diagrams open at the same time. While I may want to export all the diagrams from within one folder, I may not want to export all diagrams from *all* folders open in the workspace.

Would it be possible to add an export command that allows export of all files within the current folder (or one selected by right-click maybe)?

**Comment by qjebbs** [comment]
Next release, you'll be able to right click on a folder, and select export workspace. It'll work as expected.
