### ISSUE TITLE
Alt+D preview not working

### ISSUE THREAD

**Issue by AlanGillespie** [qjebbs/vscode-plantuml#88]
With plugin version 2.4.0 running on VSCode version 1.19.0, pressing Alt+D does not generate a preview, but instead displays an error message "Command 'plantuml.preview' not found"

**Comment by qjebbs** [comment]
pls paste the error msg from development tool console.

**Comment by AlanGillespie** [comment]
Weird. The PlantUML extension is working perfectly today, but I am now having trouble with another extension (Latex Workshop). By the look of the log I suspect a problem with the loading of extensions inside the VSCode platform itself. The log is attached in case it contains any helpful information.

[-1513596232071.log](https://github.com/qjebbs/vscode-plantuml/files/1567687/-1513596232071.log)

**Comment by qjebbs** [comment]
OK. I see the log, but it has nothing to do with plantuml plugin. Close for now. 

If you encounter the issue again, re-open this then.
