### ISSUE TITLE
Can you add math jar files in your extension?

### ISSUE THREAD

**Issue by efairon** [qjebbs/vscode-plantuml#92]
In order to generate nice looking math in plantuml we need some .jar files

To be added in  the plantuml.jar folder: 

* batik-all-1.7.jar
* jlatexmath-minimal-1.0.3.jar
* jlm_cyrillic.jar
* jlm_greek.jar

Then we can generate and preview math in UML like this :

![](https://vgy.me/ymoznY.png)

Sample math:

```
@startuml
:<math>int_0^1f(x)dx</math>;
:<math>x^2+y_1+z_12^34</math>;
note right
Try also
<math>d/dxf(x)=lim_(h->0)(f(x+h)-f(x))/h</math>
<latex>P(y|\mathbf{x}) \mbox{ or } f(\mathbf{x})+\epsilon</latex>
end note
@enduml
```
![](https://goo.gl/964FMe)

See details: http://plantuml.com/ascii-math

**Comment by qjebbs** [comment]
I suggest you organize your own copy of `plantuml.jar` and other required jars, besides math, generating pdf requires other jars too.  All these could be too large to be embedded , VSCode has limits on plugin size.

You can use your own copy of `plantuml.jar` with setting, and keep them updated, which the plugin not always does.
`plantuml.jar`: Alternate plantuml.jar location. Leave it blank to use integrated jar.

**Comment by aihuawu** [comment]
If I download the latest plantuml.jar, and replace the jar you provided, 
~/.vscode/extensions/jebbs.plantuml-2.13.9/plantuml.jar
the preview does not work.
Is there any instruction on how I can add other required jars?
Thanks.

george

**Comment by qjebbs** [comment]
@aihuawu do not replace, make your own jar, with dependencies, config to use this copy with `plantuml.jar` setting

**Comment by tadeaustria** [comment]
Can someone please explain this in detail? I'm no java developer and don't know how .jar files interact and depend.
