### ISSUE TITLE
Disable JDK check

### ISSUE THREAD

**Issue by anoff** [qjebbs/vscode-plantuml#93]
I keep getting prompts that I do not have JDK installed. Since I configured the plantUML plugin to use a server for rendering I also suggest it does not perform this check. I am not 💯% sure this issue is related to plantUML since the JDK check seems to be performed not every time a markdown is opened.

If you point me into the right direction I will try to fix this with a PR but I found several JDK checks in the source and wasn't sure which one to modify.

**Comment by qjebbs** [comment]
Thank you for feedback. I update the code, JDK check won't happen until you really need java.

In your case, check still runs when you call the "extract source" command.

**Comment by anoff** [comment]
Awesome, thanks for the quick solution

**Comment by anoff** [comment]
hey @qjebbs was there a recent change that might have re-activated the java check?

**Comment by qjebbs** [comment]
I don’t think so, if you see it again and again, please consider re-open this issue.

**Comment by anoff** [comment]
keep getting it on `v2.10.2` of the plugin and code `1.30.2`(61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8 x64)

**Comment by anoff** [comment]
I just dug around a bit in the code and think [this commit](https://github.com/anoff/vscode-plantuml/commit/d8f61df268c397a83bba4a98b050bea71aa248b5#diff-113486971d8d930c24f25a214e869935R111) might have caused the issue to reappear? If I understand the code correctly as soon as the config is loaded the Java check is executed.

Not sure why it has taken so long for me to realize it though

**Comment by qjebbs** [comment]
Cannot reproduce, do you config `plantuml.java` to a path that doesn't exists?

Further Info:

`popups when opening a markdown`: No, the extension never show popups. It could be other extension or plugin requires the java, and the OS (like Mac) shows similar popups. 
`keep getting it`: what are the steps which let you keep getting it?

**Comment by qjebbs** [comment]
I see, you have Mac, and don't have java installed, don't you?

MacOS over reacts in this case. Any application who tries to call java if it don't installed, MacOS checks and prompts. It's similar to what I do in the extension, but apparently not so considerate.

For now, you can bypass the OS JDK check by config:

```json
plantuml.java: "no_java"
```

**Comment by anoff** [comment]
> I see, you have Mac, and don't have java installed, don't you?

Yes, correct. The `no_java` setting works, thanks! :)
