### ISSUE TITLE
Cannot specify dot executable with -graphvizdot

### ISSUE THREAD

**Issue by Nonghorn** [qjebbs/vscode-plantuml#94]
Hi, thanks this plugin, I just discover it and I think it will be very useful !
but as I say in the title I have an issue with graphviz, I am on Windows and I can't have graphviz on is regular directory.

In command line I can set my personal path with -graphvizdot "C:\path\to\dot.exe" but in this plugin it doesn't seem to work.

I have set those parameters : 
"plantuml.commandArgs": ["-graphvizdot \"D:\\"Path to my directory"\\graphviz\\bin\\dot.exe\""],
"plantuml.jar": "D:\\"Path to my directory"\\PlanUML\\plantuml.jar"

And i get a "Could not create the Java virtual machine; Unrecognized option..." error.

Tell me if I miss something.
Thanks in advance.

**Comment by qjebbs** [comment]
try

```json
"plantuml.commandArgs": [
    "-graphvizdot",
    "D:\\Path to my directory\\graphviz\\bin\\dot.exe"
]
```

**Comment by qjebbs** [comment]
pay attention to Escape Character `\\`, or replace `\` with `/`, like:

```json
"plantuml.commandArgs": [
    "-graphvizdot",
    "path/to/graphviz/bin/dot.exe"
]
```

**Comment by Nonghorn** [comment]
Thank you for the quick answer !
Unfortunately I still have "Unrecognized option: -graphvizdot"

For the path, if i specify a personal path for the planuml jar it work, so I think my path work.

**Comment by qjebbs** [comment]
No, your path in the first is not right, according to `JSON` specification.

**Comment by Nonghorn** [comment]
That's what I have now : 

With only : "plantuml.jar": "D:/Users/"Path to my directory"/PlanUML/plantuml.jar" -> it work but nothing is generation because it doesn't have grahviz

With : "plantuml.jar": "D:/Users/"Path to my directory"/PlanUML/plantuml.jar",
    "plantuml.commandArgs": [
        "-graphvizdot",
        "D:/Users/"Path to my directory"/graphviz/bin/dot.exe"
-> it still say "Could not create the Java virtual machine; Unrecognized option: -graphvizdot"

**Comment by qjebbs** [comment]
Yes, I look into the code, commandArgs  is for assigning args to java, like `-DPLANTUML_LIMIT_SIZE=8192`. But you cannot use it to assign args to "plantuml.jar". You can try setup the environment variable GRAPHVIZ_DOT, maybe.

**Comment by qjebbs** [comment]
```json
"plantuml.commandArgs": [
    "-DGRAPHVIZ_DOT=\"D:/Users/Nonghorn/Personal App/graphviz/bin/dot.exe\"",
]
```

Can you try this?

**Comment by Nonghorn** [comment]
Yes, that's the right command, thank you !

For information I don't have the authorization to set environment variable so the last comment solve my problem.

**Comment by somaGFX** [comment]
also in Oktober 2024 the problem still exists on macOS ://
