### ISSUE TITLE
Preview update too fast

### ISSUE THREAD

**Issue by anhnhoktvn** [qjebbs/vscode-plantuml#98]
The preview function too fast. I often see syntax errors in preview page because I haven't finish writing. It'd be better if I could set the update time interval or have a setting to update only after saving the file.

Thanks for great extension.

**Comment by qjebbs** [comment]
I've fold errors into a warning icon, error text behind the image will be removed next release. I think this would be less distractive. I don't want the preview logic too complicated at this moment.
